using ErikLieben.FA.ES;
using ErikLieben.FA.ES.Aggregates;
using Microsoft.Extensions.DependencyInjection;
using System.Text.Json.Serialization;
using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using System;
using System.Collections.Generic;
using TaskFlow.Domain.Aggregates;
using TaskFlow.Domain.Events.Epic;
using TaskFlow.Domain.Events.Project;
using TaskFlow.Domain.Events.Release;
using TaskFlow.Domain.Events.Sprint;
using TaskFlow.Domain.Events.UserProfile;
using TaskFlow.Domain.Events.WorkItem;
using TaskFlow.Domain.Projections;
using TaskFlow.Domain.ValueObjects;
using TaskFlow.Domain.ValueObjects.WorkItem;

namespace TaskFlow.Domain;

// <auto-generated />
/// <summary>
/// Factory for creating aggregate instances in the TaskFlow.Domain project.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
[ExcludeFromCodeCoverage]
public partial class TaskFlowDomainFactory : AggregateFactory, IAggregateFactory
{
    /// <summary>
    /// Initializes a new instance of the TaskFlowDomainFactory class.
    /// </summary>
    /// <param name="serviceProvider">Service provider for dependency injection.</param>
    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public TaskFlowDomainFactory(IServiceProvider serviceProvider) : base(serviceProvider)
    {
    }

    /// <summary>
    /// Registers all aggregate factories and repositories with the service collection.
    /// </summary>
    /// <param name="serviceCollection">The service collection to register services with.</param>
    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public static void Register(IServiceCollection serviceCollection)
    {
        serviceCollection.AddSingleton<IAggregateFactory<Epic, EpicId>, EpicFactory>();
        serviceCollection.AddSingleton<IEpicFactory, EpicFactory>();
        serviceCollection.AddScoped<IEpicRepository, EpicRepository>();
        serviceCollection.AddSingleton<IAggregateFactory<Project, ProjectId>, ProjectFactory>();
        serviceCollection.AddSingleton<IProjectFactory, ProjectFactory>();
        serviceCollection.AddScoped<IProjectRepository, ProjectRepository>();
        serviceCollection.AddSingleton<IAggregateFactory<Release, ReleaseId>, ReleaseFactory>();
        serviceCollection.AddSingleton<IReleaseFactory, ReleaseFactory>();
        serviceCollection.AddScoped<IReleaseRepository, ReleaseRepository>();
        serviceCollection.AddSingleton<IAggregateFactory<Sprint, SprintId>, SprintFactory>();
        serviceCollection.AddSingleton<ISprintFactory, SprintFactory>();
        serviceCollection.AddScoped<ISprintRepository, SprintRepository>();
        serviceCollection.AddSingleton<IAggregateFactory<UserProfile, UserProfileId>, UserProfileFactory>();
        serviceCollection.AddSingleton<IUserProfileFactory, UserProfileFactory>();
        serviceCollection.AddScoped<IUserProfileRepository, UserProfileRepository>();
        serviceCollection.AddSingleton<IAggregateFactory<WorkItem, WorkItemId>, WorkItemFactory>();
        serviceCollection.AddSingleton<IWorkItemFactory, WorkItemFactory>();
        serviceCollection.AddScoped<IWorkItemRepository, WorkItemRepository>();

        serviceCollection.AddSingleton<IAggregateFactory, TaskFlowDomainFactory>();
    }

    /// <summary>
    /// Gets the aggregate factory type for a given aggregate type.
    /// </summary>
    /// <param name="type">The aggregate type to get the factory for.</param>
    /// <returns>The factory type for the specified aggregate type.</returns>
    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public static Type Get(Type type)
    {
        return type switch
        {
            Type agg when agg == typeof(Epic) => typeof(IAggregateFactory<Epic, EpicId>),
            Type agg when agg == typeof(Project) => typeof(IAggregateFactory<Project, ProjectId>),
            Type agg when agg == typeof(Release) => typeof(IAggregateFactory<Release, ReleaseId>),
            Type agg when agg == typeof(Sprint) => typeof(IAggregateFactory<Sprint, SprintId>),
            Type agg when agg == typeof(UserProfile) => typeof(IAggregateFactory<UserProfile, UserProfileId>),
            Type agg when agg == typeof(WorkItem) => typeof(IAggregateFactory<WorkItem, WorkItemId>),

            _ => null!
        };
    }

    /// <summary>
    /// Gets the aggregate factory type for a given aggregate type (internal implementation).
    /// </summary>
    /// <param name="type">The aggregate type to get the factory for.</param>
    /// <returns>The factory type for the specified aggregate type.</returns>
    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override Type InternalGet(Type type)
    {
        return Get(type);
    }
}

// <auto-generated />
/// <summary>
/// Extension methods for configuring TaskFlow.Domain aggregate factories.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
[ExcludeFromCodeCoverage]
public static class TaskFlowDomainExtensions
{
    /// <summary>
    /// Configures the TaskFlowDomain aggregate factory and all related services.
    /// </summary>
    /// <param name="services">The service collection to configure.</param>
    /// <returns>The service collection for chaining.</returns>
    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public static IServiceCollection ConfigureTaskFlowDomainFactory(this IServiceCollection services)
    {
        TaskFlowDomainFactory.Register(services);

        // Register aggregate storage registry for cross-storage projections
        // Get or create aggregate storage registry
        var existingRegistry = services.FirstOrDefault(d => d.ServiceType == typeof(ErikLieben.FA.ES.Configuration.IAggregateStorageRegistry));
        if (existingRegistry != null)
        {
            // Registry already exists - merge our mappings into the existing one
            var descriptor = existingRegistry;
            services.Remove(descriptor);
            var existingMap = descriptor.ImplementationInstance is ErikLieben.FA.ES.Configuration.AggregateStorageRegistry reg
                ? typeof(ErikLieben.FA.ES.Configuration.AggregateStorageRegistry)
                    .GetField("_storageMap", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
                    ?.GetValue(reg) as IReadOnlyDictionary<string, string> ?? new Dictionary<string, string>()
                : new Dictionary<string, string>();
            var mergedMap = new Dictionary<string, string>(existingMap);
            mergedMap.TryAdd("userprofile", "UserDataStore");
            services.AddSingleton<ErikLieben.FA.ES.Configuration.IAggregateStorageRegistry>(
                new ErikLieben.FA.ES.Configuration.AggregateStorageRegistry(mergedMap));
        }
        else
        {
            // No existing registry - create a new one
            var storageMap = new Dictionary<string, string>
            {
                ["userprofile"] = "UserDataStore",
            };
            services.AddSingleton<ErikLieben.FA.ES.Configuration.IAggregateStorageRegistry>(
                new ErikLieben.FA.ES.Configuration.AggregateStorageRegistry(storageMap));
        }

        // Register projection factories and projections
        // Register projection factories
        services.AddSingleton<TaskFlow.Domain.Projections.ActiveWorkItemsFactory>();
        services.AddSingleton<TaskFlow.Domain.Projections.EpicSummaryFactory>();
        services.AddSingleton<TaskFlow.Domain.Projections.EventUpcastingDemonstrationFactory>();
        services.AddSingleton<TaskFlow.Domain.Projections.ProjectDashboardFactory>();
        services.AddSingleton<TaskFlow.Domain.Projections.ProjectKanbanBoardFactory>();
        services.AddSingleton<TaskFlow.Domain.Projections.ProjectKanbanDestinationFactory>();
        services.AddSingleton<TaskFlow.Domain.Projections.ProjectKanbanLanguageDestinationFactory>();
        services.AddSingleton<TaskFlow.Domain.Projections.ReleaseDashboardFactory>();
        services.AddSingleton<TaskFlow.Domain.Projections.TeamMembersFactory>();
        services.AddSingleton<TaskFlow.Domain.Projections.UserProfilePageFactory>();
        services.AddSingleton<TaskFlow.Domain.Projections.UserProfilesFactory>();

        // Register projection singletons (loaded from blob storage or created new)
        services.AddSingleton<TaskFlow.Domain.Projections.ActiveWorkItems>(sp =>
        {
            var factory = sp.GetRequiredService<TaskFlow.Domain.Projections.ActiveWorkItemsFactory>();
            var docFactory = sp.GetRequiredService<IObjectDocumentFactory>();
            var streamFactory = sp.GetRequiredService<IEventStreamFactory>();

            try
            {
                return factory.GetOrCreateAsync(docFactory, streamFactory).GetAwaiter().GetResult();
            }
            catch
            {
                return new TaskFlow.Domain.Projections.ActiveWorkItems(docFactory, streamFactory);
            }
        });
        services.AddSingleton<TaskFlow.Domain.Projections.EpicSummary>(sp =>
        {
            var factory = sp.GetRequiredService<TaskFlow.Domain.Projections.EpicSummaryFactory>();
            var docFactory = sp.GetRequiredService<IObjectDocumentFactory>();
            var streamFactory = sp.GetRequiredService<IEventStreamFactory>();

            try
            {
                return factory.GetOrCreateAsync(docFactory, streamFactory).GetAwaiter().GetResult();
            }
            catch
            {
                return new TaskFlow.Domain.Projections.EpicSummary(docFactory, streamFactory);
            }
        });
        services.AddSingleton<TaskFlow.Domain.Projections.EventUpcastingDemonstration>(sp =>
        {
            var factory = sp.GetRequiredService<TaskFlow.Domain.Projections.EventUpcastingDemonstrationFactory>();
            var docFactory = sp.GetRequiredService<IObjectDocumentFactory>();
            var streamFactory = sp.GetRequiredService<IEventStreamFactory>();

            try
            {
                return factory.GetOrCreateAsync(docFactory, streamFactory).GetAwaiter().GetResult();
            }
            catch
            {
                return new TaskFlow.Domain.Projections.EventUpcastingDemonstration(docFactory, streamFactory);
            }
        });
        services.AddSingleton<TaskFlow.Domain.Projections.ProjectDashboard>(sp =>
        {
            var factory = sp.GetRequiredService<TaskFlow.Domain.Projections.ProjectDashboardFactory>();
            var docFactory = sp.GetRequiredService<IObjectDocumentFactory>();
            var streamFactory = sp.GetRequiredService<IEventStreamFactory>();

            try
            {
                return factory.GetOrCreateAsync(docFactory, streamFactory).GetAwaiter().GetResult();
            }
            catch
            {
                return new TaskFlow.Domain.Projections.ProjectDashboard(docFactory, streamFactory);
            }
        });
        services.AddSingleton<TaskFlow.Domain.Projections.ProjectKanbanBoard>(sp =>
        {
            var factory = sp.GetRequiredService<TaskFlow.Domain.Projections.ProjectKanbanBoardFactory>();
            var docFactory = sp.GetRequiredService<IObjectDocumentFactory>();
            var streamFactory = sp.GetRequiredService<IEventStreamFactory>();

            try
            {
                return factory.GetOrCreateAsync(docFactory, streamFactory).GetAwaiter().GetResult();
            }
            catch
            {
                return new TaskFlow.Domain.Projections.ProjectKanbanBoard(docFactory, streamFactory);
            }
        });
        services.AddSingleton<TaskFlow.Domain.Projections.ProjectKanbanDestination>(sp =>
        {
            var factory = sp.GetRequiredService<TaskFlow.Domain.Projections.ProjectKanbanDestinationFactory>();
            var docFactory = sp.GetRequiredService<IObjectDocumentFactory>();
            var streamFactory = sp.GetRequiredService<IEventStreamFactory>();

            try
            {
                return factory.GetOrCreateAsync(docFactory, streamFactory).GetAwaiter().GetResult();
            }
            catch
            {
                return new TaskFlow.Domain.Projections.ProjectKanbanDestination(docFactory, streamFactory);
            }
        });
        services.AddSingleton<TaskFlow.Domain.Projections.ProjectKanbanLanguageDestination>(sp =>
        {
            var factory = sp.GetRequiredService<TaskFlow.Domain.Projections.ProjectKanbanLanguageDestinationFactory>();
            var docFactory = sp.GetRequiredService<IObjectDocumentFactory>();
            var streamFactory = sp.GetRequiredService<IEventStreamFactory>();

            try
            {
                return factory.GetOrCreateAsync(docFactory, streamFactory).GetAwaiter().GetResult();
            }
            catch
            {
                return new TaskFlow.Domain.Projections.ProjectKanbanLanguageDestination(docFactory, streamFactory);
            }
        });
        services.AddSingleton<TaskFlow.Domain.Projections.ReleaseDashboard>(sp =>
        {
            var factory = sp.GetRequiredService<TaskFlow.Domain.Projections.ReleaseDashboardFactory>();
            var docFactory = sp.GetRequiredService<IObjectDocumentFactory>();
            var streamFactory = sp.GetRequiredService<IEventStreamFactory>();

            try
            {
                return factory.GetOrCreateAsync(docFactory, streamFactory).GetAwaiter().GetResult();
            }
            catch
            {
                return new TaskFlow.Domain.Projections.ReleaseDashboard(docFactory, streamFactory);
            }
        });
        services.AddSingleton<TaskFlow.Domain.Projections.TeamMembers>(sp =>
        {
            var factory = sp.GetRequiredService<TaskFlow.Domain.Projections.TeamMembersFactory>();
            var docFactory = sp.GetRequiredService<IObjectDocumentFactory>();
            var streamFactory = sp.GetRequiredService<IEventStreamFactory>();

            try
            {
                return factory.GetOrCreateAsync(docFactory, streamFactory).GetAwaiter().GetResult();
            }
            catch
            {
                return new TaskFlow.Domain.Projections.TeamMembers(docFactory, streamFactory);
            }
        });
        services.AddSingleton<TaskFlow.Domain.Projections.UserProfilePage>(sp =>
        {
            var factory = sp.GetRequiredService<TaskFlow.Domain.Projections.UserProfilePageFactory>();
            var docFactory = sp.GetRequiredService<IObjectDocumentFactory>();
            var streamFactory = sp.GetRequiredService<IEventStreamFactory>();

            try
            {
                return factory.GetOrCreateAsync(docFactory, streamFactory).GetAwaiter().GetResult();
            }
            catch
            {
                return new TaskFlow.Domain.Projections.UserProfilePage(docFactory, streamFactory);
            }
        });
        services.AddSingleton<TaskFlow.Domain.Projections.UserProfiles>(sp =>
        {
            var factory = sp.GetRequiredService<TaskFlow.Domain.Projections.UserProfilesFactory>();
            var docFactory = sp.GetRequiredService<IObjectDocumentFactory>();
            var streamFactory = sp.GetRequiredService<IEventStreamFactory>();

            try
            {
                return factory.GetOrCreateAsync(docFactory, streamFactory).GetAwaiter().GetResult();
            }
            catch
            {
                return new TaskFlow.Domain.Projections.UserProfiles(docFactory, streamFactory);
            }
        });

        return services;
    }
}

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(EpicCreated))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for EpicCreated event type.
/// </summary>
internal partial class EpicCreatedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(EpicRenamed))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for EpicRenamed event type.
/// </summary>
internal partial class EpicRenamedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(EpicDescriptionUpdated))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for EpicDescriptionUpdated event type.
/// </summary>
internal partial class EpicDescriptionUpdatedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ProjectAddedToEpic))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ProjectAddedToEpic event type.
/// </summary>
internal partial class ProjectAddedToEpicJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ProjectRemovedFromEpic))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ProjectRemovedFromEpic event type.
/// </summary>
internal partial class ProjectRemovedFromEpicJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(EpicTargetDateChanged))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for EpicTargetDateChanged event type.
/// </summary>
internal partial class EpicTargetDateChangedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(EpicPriorityChanged))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for EpicPriorityChanged event type.
/// </summary>
internal partial class EpicPriorityChangedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(EpicCompleted))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for EpicCompleted event type.
/// </summary>
internal partial class EpicCompletedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ProjectInitiated))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ProjectInitiated event type.
/// </summary>
internal partial class ProjectInitiatedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ProjectRebranded))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ProjectRebranded event type.
/// </summary>
internal partial class ProjectRebrandedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ProjectScopeRefined))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ProjectScopeRefined event type.
/// </summary>
internal partial class ProjectScopeRefinedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ProjectLanguagesConfigured))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ProjectLanguagesConfigured event type.
/// </summary>
internal partial class ProjectLanguagesConfiguredJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(MemberJoinedProjectV1))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for MemberJoinedProjectV1 event type.
/// </summary>
internal partial class MemberJoinedProjectV1JsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(Boolean))]
[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(MemberJoinedProject))]
[JsonSerializable(typeof(MemberPermissions))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for MemberJoinedProject event type.
/// </summary>
internal partial class MemberJoinedProjectJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(MemberLeftProject))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for MemberLeftProject event type.
/// </summary>
internal partial class MemberLeftProjectJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(WorkItemAddedToProject))]
// <auto-generated />
/// <summary>
/// JSON serializer context for WorkItemAddedToProject event type.
/// </summary>
internal partial class WorkItemAddedToProjectJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(Enum))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(WorkItemStatus))]
[JsonSerializable(typeof(WorkItemStatusChangedInProject))]
// <auto-generated />
/// <summary>
/// JSON serializer context for WorkItemStatusChangedInProject event type.
/// </summary>
internal partial class WorkItemStatusChangedInProjectJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(Enum))]
[JsonSerializable(typeof(Int32))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(WorkItemReordered))]
[JsonSerializable(typeof(WorkItemStatus))]
// <auto-generated />
/// <summary>
/// JSON serializer context for WorkItemReordered event type.
/// </summary>
internal partial class WorkItemReorderedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ProjectCompleted))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ProjectCompleted event type.
/// </summary>
internal partial class ProjectCompletedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ProjectCompletedSuccessfully))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ProjectCompletedSuccessfully event type.
/// </summary>
internal partial class ProjectCompletedSuccessfullyJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ProjectCancelled))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ProjectCancelled event type.
/// </summary>
internal partial class ProjectCancelledJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ProjectFailed))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ProjectFailed event type.
/// </summary>
internal partial class ProjectFailedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ProjectDelivered))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ProjectDelivered event type.
/// </summary>
internal partial class ProjectDeliveredJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ProjectSuspended))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ProjectSuspended event type.
/// </summary>
internal partial class ProjectSuspendedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ProjectMerged))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ProjectMerged event type.
/// </summary>
internal partial class ProjectMergedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ProjectReactivated))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ProjectReactivated event type.
/// </summary>
internal partial class ProjectReactivatedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(DemoNoteAdded))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for DemoNoteAdded event type.
/// </summary>
internal partial class DemoNoteAddedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ReleaseCreated))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ReleaseCreated event type.
/// </summary>
internal partial class ReleaseCreatedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ReleaseNoteAdded))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ReleaseNoteAdded event type.
/// </summary>
internal partial class ReleaseNoteAddedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ReleaseDeployed))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ReleaseDeployed event type.
/// </summary>
internal partial class ReleaseDeployedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ReleaseCompleted))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ReleaseCompleted event type.
/// </summary>
internal partial class ReleaseCompletedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ReleaseStaged))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ReleaseStaged event type.
/// </summary>
internal partial class ReleaseStagedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ReleaseRolledBack))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ReleaseRolledBack event type.
/// </summary>
internal partial class ReleaseRolledBackJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(SprintCreated))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for SprintCreated event type.
/// </summary>
internal partial class SprintCreatedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(WorkItemAddedToSprint))]
// <auto-generated />
/// <summary>
/// JSON serializer context for WorkItemAddedToSprint event type.
/// </summary>
internal partial class WorkItemAddedToSprintJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(WorkItemRemovedFromSprint))]
// <auto-generated />
/// <summary>
/// JSON serializer context for WorkItemRemovedFromSprint event type.
/// </summary>
internal partial class WorkItemRemovedFromSprintJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(SprintGoalUpdated))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for SprintGoalUpdated event type.
/// </summary>
internal partial class SprintGoalUpdatedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(SprintDatesChanged))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for SprintDatesChanged event type.
/// </summary>
internal partial class SprintDatesChangedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(SprintStarted))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for SprintStarted event type.
/// </summary>
internal partial class SprintStartedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(SprintCompleted))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for SprintCompleted event type.
/// </summary>
internal partial class SprintCompletedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(SprintCancelled))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for SprintCancelled event type.
/// </summary>
internal partial class SprintCancelledJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(UserProfileCreated))]
// <auto-generated />
/// <summary>
/// JSON serializer context for UserProfileCreated event type.
/// </summary>
internal partial class UserProfileCreatedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(UserProfileUpdated))]
// <auto-generated />
/// <summary>
/// JSON serializer context for UserProfileUpdated event type.
/// </summary>
internal partial class UserProfileUpdatedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(Dictionary<String, String>))]
[JsonSerializable(typeof(Enum))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(WorkItemPlanned))]
[JsonSerializable(typeof(WorkItemPriority))]
// <auto-generated />
/// <summary>
/// JSON serializer context for WorkItemPlanned event type.
/// </summary>
internal partial class WorkItemPlannedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ResponsibilityAssigned))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ResponsibilityAssigned event type.
/// </summary>
internal partial class ResponsibilityAssignedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(ResponsibilityRelinquished))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ResponsibilityRelinquished event type.
/// </summary>
internal partial class ResponsibilityRelinquishedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(WorkCommenced))]
// <auto-generated />
/// <summary>
/// JSON serializer context for WorkCommenced event type.
/// </summary>
internal partial class WorkCommencedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(WorkCompleted))]
// <auto-generated />
/// <summary>
/// JSON serializer context for WorkCompleted event type.
/// </summary>
internal partial class WorkCompletedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(WorkItemRevived))]
// <auto-generated />
/// <summary>
/// JSON serializer context for WorkItemRevived event type.
/// </summary>
internal partial class WorkItemRevivedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(Enum))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(WorkItemPriority))]
[JsonSerializable(typeof(WorkItemReprioritized))]
// <auto-generated />
/// <summary>
/// JSON serializer context for WorkItemReprioritized event type.
/// </summary>
internal partial class WorkItemReprioritizedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(EffortReestimated))]
[JsonSerializable(typeof(Int32))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for EffortReestimated event type.
/// </summary>
internal partial class EffortReestimatedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(RequirementsRefined))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for RequirementsRefined event type.
/// </summary>
internal partial class RequirementsRefinedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(FeedbackProvided))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for FeedbackProvided event type.
/// </summary>
internal partial class FeedbackProvidedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(WorkItemRelocated))]
// <auto-generated />
/// <summary>
/// JSON serializer context for WorkItemRelocated event type.
/// </summary>
internal partial class WorkItemRelocatedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(WorkItemRetagged))]
// <auto-generated />
/// <summary>
/// JSON serializer context for WorkItemRetagged event type.
/// </summary>
internal partial class WorkItemRetaggedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(DeadlineEstablished))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for DeadlineEstablished event type.
/// </summary>
internal partial class DeadlineEstablishedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(DeadlineRemoved))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for DeadlineRemoved event type.
/// </summary>
internal partial class DeadlineRemovedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(MovedBackFromCompletedToInProgress))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for MovedBackFromCompletedToInProgress event type.
/// </summary>
internal partial class MovedBackFromCompletedToInProgressJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(MovedBackFromCompletedToPlanned))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for MovedBackFromCompletedToPlanned event type.
/// </summary>
internal partial class MovedBackFromCompletedToPlannedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(MovedBackFromInProgressToPlanned))]
[JsonSerializable(typeof(String))]
// <auto-generated />
/// <summary>
/// JSON serializer context for MovedBackFromInProgressToPlanned event type.
/// </summary>
internal partial class MovedBackFromInProgressToPlannedJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(DragMarkedAsAccidental))]
[JsonSerializable(typeof(Enum))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(WorkItemStatus))]
// <auto-generated />
/// <summary>
/// JSON serializer context for DragMarkedAsAccidental event type.
/// </summary>
internal partial class DragMarkedAsAccidentalJsonSerializerContext : JsonSerializerContext { }

