using Azure.Storage.Blobs;
using ErikLieben.FA.ES;
using ErikLieben.FA.ES.AzureStorage.Blob;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Projections;
using ErikLieben.FA.ES.VersionTokenParts;
using Microsoft.Extensions.Azure;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.WorkItem;

namespace TaskFlow.Domain.Projections;

// <auto-generated />
[GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
[ExcludeFromCodeCoverage]
public partial class ActiveWorkItems : IActiveWorkItems
{

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public ActiveWorkItems() : base()
    {
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public ActiveWorkItems(IObjectDocumentFactory documentFactory, IEventStreamFactory eventStreamFactory)
      : base(documentFactory, eventStreamFactory)
    {
    }

#nullable enable
    /// <summary>
    /// Applies an event to the projection by dispatching to the appropriate When method using version token.
    /// This is the primary implementation that avoids redundant document lookups.
    /// </summary>
    /// <typeparam name="T">The type of additional data passed through the execution context.</typeparam>
    /// <param name="event">The event to apply to the projection.</param>
    /// <param name="versionToken">The version token associated with the event.</param>
    /// <param name="data">Optional data to pass through the execution context.</param>
    /// <param name="parentContext">Optional parent execution context for nested projections.</param>
    /// <returns>A task representing the asynchronous fold operation.</returns>
    public override Task Fold<T>(IEvent @event, VersionToken versionToken, T? data = default(T?), IExecutionContext? parentContext = null) where T : class
    {

        switch (@event.EventType)
        {
            case "WorkItem.Planned":
                When(JsonEvent.ToEvent(@event, WorkItemPlannedJsonSerializerContext.Default.WorkItemPlanned).Data(), GetWhenParameterValue<String, WorkItemPlanned>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.ResponsibilityAssigned":
                When(JsonEvent.ToEvent(@event, ResponsibilityAssignedJsonSerializerContext.Default.ResponsibilityAssigned).Data(), GetWhenParameterValue<String, ResponsibilityAssigned>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.ResponsibilityRelinquished":
                When(JsonEvent.ToEvent(@event, ResponsibilityRelinquishedJsonSerializerContext.Default.ResponsibilityRelinquished).Data(), GetWhenParameterValue<String, ResponsibilityRelinquished>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.WorkCommenced":
                When(JsonEvent.ToEvent(@event, WorkCommencedJsonSerializerContext.Default.WorkCommenced).Data(), GetWhenParameterValue<String, WorkCommenced>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.WorkCompleted":
                When(JsonEvent.ToEvent(@event, WorkCompletedJsonSerializerContext.Default.WorkCompleted).Data(), GetWhenParameterValue<String, WorkCompleted>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.Revived":
                When(JsonEvent.ToEvent(@event, WorkItemRevivedJsonSerializerContext.Default.WorkItemRevived).Data(), GetWhenParameterValue<String, WorkItemRevived>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.Reprioritized":
                When(JsonEvent.ToEvent(@event, WorkItemReprioritizedJsonSerializerContext.Default.WorkItemReprioritized).Data(), GetWhenParameterValue<String, WorkItemReprioritized>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.Relocated":
                When(JsonEvent.ToEvent(@event, WorkItemRelocatedJsonSerializerContext.Default.WorkItemRelocated).Data(), GetWhenParameterValue<String, WorkItemRelocated>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.DeadlineEstablished":
                When(JsonEvent.ToEvent(@event, DeadlineEstablishedJsonSerializerContext.Default.DeadlineEstablished).Data(), GetWhenParameterValue<String, DeadlineEstablished>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.DeadlineRemoved":
                When(JsonEvent.ToEvent(@event, DeadlineRemovedJsonSerializerContext.Default.DeadlineRemoved).Data(), GetWhenParameterValue<String, DeadlineRemoved>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.MovedBackFromCompletedToInProgress":
                When(JsonEvent.ToEvent(@event, MovedBackFromCompletedToInProgressJsonSerializerContext.Default.MovedBackFromCompletedToInProgress).Data(), GetWhenParameterValue<String, MovedBackFromCompletedToInProgress>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.MovedBackFromCompletedToPlanned":
                When(JsonEvent.ToEvent(@event, MovedBackFromCompletedToPlannedJsonSerializerContext.Default.MovedBackFromCompletedToPlanned).Data(), GetWhenParameterValue<String, MovedBackFromCompletedToPlanned>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.MovedBackFromInProgressToPlanned":
                When(JsonEvent.ToEvent(@event, MovedBackFromInProgressToPlannedJsonSerializerContext.Default.MovedBackFromInProgressToPlanned).Data(), GetWhenParameterValue<String, MovedBackFromInProgressToPlanned>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.DragMarkedAsAccidental":
                When(JsonEvent.ToEvent(@event, DragMarkedAsAccidentalJsonSerializerContext.Default.DragMarkedAsAccidental).Data(), GetWhenParameterValue<String, DragMarkedAsAccidental>(
                         "String",
                         versionToken, @event)!);
                break;
        }

        return Task.CompletedTask;
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override Task PostWhenAll(IObjectDocument document) { return Task.CompletedTask; }
#nullable restore

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override Dictionary<string, IProjectionWhenParameterValueFactory> WhenParameterValueFactories { get; } =
          new Dictionary<string, IProjectionWhenParameterValueFactory>(){
              {"String", new TaskFlow.Domain.Projections.ObjectIdWhenValueFactory()}
          };

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public static ActiveWorkItems? LoadFromJson(string json, IObjectDocumentFactory documentFactory, IEventStreamFactory eventStreamFactory)
    {
        // Deserialize each property manually to preserve data
        System.Collections.Generic.Dictionary<System.String, TaskFlow.Domain.Projections.WorkItemSummary>? workItems = null;
        System.String? checkpointFingerprint = null;
        Checkpoint checkpoint = [];

        var reader = new Utf8JsonReader(System.Text.Encoding.UTF8.GetBytes(json));

        if (!reader.Read() || reader.TokenType != JsonTokenType.StartObject)
            return null;

        while (reader.Read())
        {
            if (reader.TokenType == JsonTokenType.EndObject)
                break;

            if (reader.TokenType != JsonTokenType.PropertyName)
                continue;

            string? propertyName = reader.GetString();
            reader.Read();

            switch (propertyName)
            {
                case "WorkItems":
                    workItems = JsonSerializer.Deserialize<System.Collections.Generic.Dictionary<System.String, TaskFlow.Domain.Projections.WorkItemSummary>>(ref reader, ActiveWorkItemsJsonSerializerContext.Default.Options);
                    break;
                case "$checkpoint":
                    checkpoint = JsonSerializer.Deserialize<ErikLieben.FA.ES.Checkpoint>(ref reader, ActiveWorkItemsJsonSerializerContext.Default.Options) ?? [];
                    break;
                case "$checkpointFingerprint":
                    checkpointFingerprint = JsonSerializer.Deserialize<System.String>(ref reader, ActiveWorkItemsJsonSerializerContext.Default.Options);
                    break;
            }
        }

        // Create instance with factories and deserialized properties
        var instance = new ActiveWorkItems(documentFactory, eventStreamFactory);

        if (workItems != null)
        {
            foreach (var kvp in workItems)
            {
                instance.WorkItems[kvp.Key] = kvp.Value;
            }
        }
        instance.Checkpoint = checkpoint;
        instance.CheckpointFingerprint = checkpointFingerprint;

        return instance;
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public override string ToJson()
    {
        return JsonSerializer.Serialize(this, ActiveWorkItemsJsonSerializerContext.Default.ActiveWorkItems);
    }

    /// <summary>
    /// Gets or sets the checkpoint tracking the last processed event position.
    /// </summary>
    [JsonIgnore]
    public override Checkpoint Checkpoint { get; set; } = [];
}

/// <summary>
/// Factory for creating and managing ActiveWorkItems blob-based projections.
/// </summary>
public partial class ActiveWorkItemsFactory(
    IAzureClientFactory<BlobServiceClient> blobServiceClientFactory,
    IObjectDocumentFactory objectDocumentFactory,
    IEventStreamFactory eventStreamFactory)
    : BlobProjectionFactory<ActiveWorkItems>(
        blobServiceClientFactory,
        "BlobStorage",
        "projections")
{
    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override bool HasExternalCheckpoint => true;

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override ActiveWorkItems New()
    {
        return new ActiveWorkItems(objectDocumentFactory, eventStreamFactory);
    }

    /// <summary>
    /// Loads a ActiveWorkItems instance from JSON with complete state restoration.
    /// </summary>
    /// <param name="json">The JSON string containing the serialized projection state.</param>
    /// <param name="documentFactory">Factory for managing object documents.</param>
    /// <param name="eventStreamFactory">Factory for creating event streams.</param>
    /// <returns>A ActiveWorkItems instance with restored state, or null if deserialization fails.</returns>
    protected override ActiveWorkItems? LoadFromJson(string json, IObjectDocumentFactory documentFactory, IEventStreamFactory eventStreamFactory)
    {
        return ActiveWorkItems.LoadFromJson(json, documentFactory, eventStreamFactory);
    }
}

#nullable enable
// <auto-generated />
/// <summary>
/// Interface defining the public state properties of ActiveWorkItems.
/// </summary>
public interface IActiveWorkItems
{
    public Dictionary<System.String, TaskFlow.Domain.Projections.WorkItemSummary>? WorkItems { get; }
    public String? CheckpointFingerprint { get; }
}
#nullable restore

[JsonSerializable(typeof(WorkItemPlanned))]
[JsonSerializable(typeof(ResponsibilityAssigned))]
[JsonSerializable(typeof(ResponsibilityRelinquished))]
[JsonSerializable(typeof(WorkCommenced))]
[JsonSerializable(typeof(WorkCompleted))]
[JsonSerializable(typeof(WorkItemRevived))]
[JsonSerializable(typeof(WorkItemReprioritized))]
[JsonSerializable(typeof(WorkItemRelocated))]
[JsonSerializable(typeof(DeadlineEstablished))]
[JsonSerializable(typeof(DeadlineRemoved))]
[JsonSerializable(typeof(MovedBackFromCompletedToInProgress))]
[JsonSerializable(typeof(MovedBackFromCompletedToPlanned))]
[JsonSerializable(typeof(MovedBackFromInProgressToPlanned))]
[JsonSerializable(typeof(DragMarkedAsAccidental))]
[JsonSerializable(typeof(System.Collections.Generic.Dictionary<System.String, TaskFlow.Domain.Projections.WorkItemSummary>))]
[JsonSerializable(typeof(TaskFlow.Domain.Projections.WorkItemSummary))]
[JsonSerializable(typeof(System.Enum))]
[JsonSerializable(typeof(System.Collections.Generic.Dictionary<System.String, ErikLieben.FA.ES.Projections.IProjectionWhenParameterValueFactory>))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Projections.IProjectionWhenParameterValueFactory))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Checkpoint))]
[JsonSerializable(typeof(ActiveWorkItems))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ActiveWorkItems types.
/// </summary>
internal partial class ActiveWorkItemsJsonSerializerContext : JsonSerializerContext
{
}

