using Azure.Storage.Blobs;
using ErikLieben.FA.ES;
using ErikLieben.FA.ES.AzureStorage.Blob;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Projections;
using ErikLieben.FA.ES.VersionTokenParts;
using Microsoft.Extensions.Azure;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.Project;

namespace TaskFlow.Domain.Projections;

// <auto-generated />
[GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
[ExcludeFromCodeCoverage]
public partial class EventUpcastingDemonstration : IEventUpcastingDemonstration
{

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public EventUpcastingDemonstration() : base()
    {
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public EventUpcastingDemonstration(IObjectDocumentFactory documentFactory, IEventStreamFactory eventStreamFactory)
      : base(documentFactory, eventStreamFactory)
    {
    }

#nullable enable
    /// <summary>
    /// Applies an event to the projection by dispatching to the appropriate When method using version token.
    /// This is the primary implementation that avoids redundant document lookups.
    /// </summary>
    /// <typeparam name="T">The type of additional data passed through the execution context.</typeparam>
    /// <param name="event">The event to apply to the projection.</param>
    /// <param name="versionToken">The version token associated with the event.</param>
    /// <param name="data">Optional data to pass through the execution context.</param>
    /// <param name="parentContext">Optional parent execution context for nested projections.</param>
    /// <returns>A task representing the asynchronous fold operation.</returns>
    public override Task Fold<T>(IEvent @event, VersionToken versionToken, T? data = default(T?), IExecutionContext? parentContext = null) where T : class
    {

        switch (@event.EventType)
        {
            case "Project.Initiated":
                When(JsonEvent.ToEvent(@event, ProjectInitiatedJsonSerializerContext.Default.ProjectInitiated).Data(), GetWhenParameterValue<String, ProjectInitiated>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.Rebranded":
                When(JsonEvent.ToEvent(@event, ProjectRebrandedJsonSerializerContext.Default.ProjectRebranded).Data(), GetWhenParameterValue<String, ProjectRebranded>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.Completed":
                When(JsonEvent.ToEvent(@event, ProjectCompletedJsonSerializerContext.Default.ProjectCompleted).Data(), GetWhenParameterValue<String, ProjectCompleted>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.CompletedSuccessfully":
                When(JsonEvent.ToEvent(@event, ProjectCompletedSuccessfullyJsonSerializerContext.Default.ProjectCompletedSuccessfully).Data(), GetWhenParameterValue<String, ProjectCompletedSuccessfully>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.Cancelled":
                When(JsonEvent.ToEvent(@event, ProjectCancelledJsonSerializerContext.Default.ProjectCancelled).Data(), GetWhenParameterValue<String, ProjectCancelled>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.Failed":
                When(JsonEvent.ToEvent(@event, ProjectFailedJsonSerializerContext.Default.ProjectFailed).Data(), GetWhenParameterValue<String, ProjectFailed>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.Delivered":
                When(JsonEvent.ToEvent(@event, ProjectDeliveredJsonSerializerContext.Default.ProjectDelivered).Data(), GetWhenParameterValue<String, ProjectDelivered>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.Suspended":
                When(JsonEvent.ToEvent(@event, ProjectSuspendedJsonSerializerContext.Default.ProjectSuspended).Data(), GetWhenParameterValue<String, ProjectSuspended>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.Reactivated":
                When(JsonEvent.ToEvent(@event, ProjectReactivatedJsonSerializerContext.Default.ProjectReactivated).Data(), GetWhenParameterValue<String, ProjectReactivated>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.MemberJoined":
                When(JsonEvent.ToEvent(@event, MemberJoinedProjectJsonSerializerContext.Default.MemberJoinedProject).Data(), GetWhenParameterValue<String, MemberJoinedProject>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.MemberLeft":
                When(JsonEvent.ToEvent(@event, MemberLeftProjectJsonSerializerContext.Default.MemberLeftProject).Data(), GetWhenParameterValue<String, MemberLeftProject>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.Merged":
                When(JsonEvent.ToEvent(@event, ProjectMergedJsonSerializerContext.Default.ProjectMerged).Data(), GetWhenParameterValue<String, ProjectMerged>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.ScopeRefined":
                When(JsonEvent.ToEvent(@event, ProjectScopeRefinedJsonSerializerContext.Default.ProjectScopeRefined).Data(), GetWhenParameterValue<String, ProjectScopeRefined>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.WorkItemReordered":
                When(JsonEvent.ToEvent(@event, WorkItemReorderedJsonSerializerContext.Default.WorkItemReordered).Data(), GetWhenParameterValue<String, WorkItemReordered>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.WorkItemAddedToProject":
                When(JsonEvent.ToEvent(@event, WorkItemAddedToProjectJsonSerializerContext.Default.WorkItemAddedToProject).Data(), GetWhenParameterValue<String, WorkItemAddedToProject>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.WorkItemStatusChangedInProject":
                When(JsonEvent.ToEvent(@event, WorkItemStatusChangedInProjectJsonSerializerContext.Default.WorkItemStatusChangedInProject).Data(), GetWhenParameterValue<String, WorkItemStatusChangedInProject>(
                         "String",
                         versionToken, @event)!);
                break;
        }

        PostWhen(JsonEvent.ToEvent(@event, @event.EventType), versionToken);

        return Task.CompletedTask;
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override Task PostWhenAll(IObjectDocument document) { return Task.CompletedTask; }
#nullable restore

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override Dictionary<string, IProjectionWhenParameterValueFactory> WhenParameterValueFactories { get; } =
          new Dictionary<string, IProjectionWhenParameterValueFactory>(){
              {"String", new TaskFlow.Domain.Projections.ObjectIdWhenValueFactory()}
          };

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public static EventUpcastingDemonstration? LoadFromJson(string json, IObjectDocumentFactory documentFactory, IEventStreamFactory eventStreamFactory)
    {
        // Deserialize each property manually to preserve data
        System.Collections.Generic.Dictionary<System.String, TaskFlow.Domain.Projections.UpcastingDemoProject>? demoProjects = null;
        System.String? checkpointFingerprint = null;
        Checkpoint checkpoint = [];

        var reader = new Utf8JsonReader(System.Text.Encoding.UTF8.GetBytes(json));

        if (!reader.Read() || reader.TokenType != JsonTokenType.StartObject)
            return null;

        while (reader.Read())
        {
            if (reader.TokenType == JsonTokenType.EndObject)
                break;

            if (reader.TokenType != JsonTokenType.PropertyName)
                continue;

            string? propertyName = reader.GetString();
            reader.Read();

            switch (propertyName)
            {
                case "DemoProjects":
                    demoProjects = JsonSerializer.Deserialize<System.Collections.Generic.Dictionary<System.String, TaskFlow.Domain.Projections.UpcastingDemoProject>>(ref reader, EventUpcastingDemonstrationJsonSerializerContext.Default.Options);
                    break;
                case "$checkpoint":
                    checkpoint = JsonSerializer.Deserialize<ErikLieben.FA.ES.Checkpoint>(ref reader, EventUpcastingDemonstrationJsonSerializerContext.Default.Options) ?? [];
                    break;
                case "$checkpointFingerprint":
                    checkpointFingerprint = JsonSerializer.Deserialize<System.String>(ref reader, EventUpcastingDemonstrationJsonSerializerContext.Default.Options);
                    break;
            }
        }

        // Create instance with factories and deserialized properties
        var instance = new EventUpcastingDemonstration(documentFactory, eventStreamFactory);

        if (demoProjects != null)
        {
            foreach (var kvp in demoProjects)
            {
                instance.DemoProjects[kvp.Key] = kvp.Value;
            }
        }
        instance.Checkpoint = checkpoint;
        instance.CheckpointFingerprint = checkpointFingerprint;

        return instance;
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public override string ToJson()
    {
        return JsonSerializer.Serialize(this, EventUpcastingDemonstrationJsonSerializerContext.Default.EventUpcastingDemonstration);
    }

    /// <summary>
    /// Gets or sets the checkpoint tracking the last processed event position.
    /// </summary>
    [JsonPropertyName("$checkpoint")]
    public override Checkpoint Checkpoint { get; set; } = [];
}

/// <summary>
/// Factory for creating and managing EventUpcastingDemonstration blob-based projections.
/// </summary>
public partial class EventUpcastingDemonstrationFactory(
    IAzureClientFactory<BlobServiceClient> blobServiceClientFactory,
    IObjectDocumentFactory objectDocumentFactory,
    IEventStreamFactory eventStreamFactory)
    : BlobProjectionFactory<EventUpcastingDemonstration>(
        blobServiceClientFactory,
        "BlobStorage",
        "projections")
{
    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override bool HasExternalCheckpoint => false;

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override EventUpcastingDemonstration New()
    {
        return new EventUpcastingDemonstration(objectDocumentFactory, eventStreamFactory);
    }

    /// <summary>
    /// Loads a EventUpcastingDemonstration instance from JSON with complete state restoration.
    /// </summary>
    /// <param name="json">The JSON string containing the serialized projection state.</param>
    /// <param name="documentFactory">Factory for managing object documents.</param>
    /// <param name="eventStreamFactory">Factory for creating event streams.</param>
    /// <returns>A EventUpcastingDemonstration instance with restored state, or null if deserialization fails.</returns>
    protected override EventUpcastingDemonstration? LoadFromJson(string json, IObjectDocumentFactory documentFactory, IEventStreamFactory eventStreamFactory)
    {
        return EventUpcastingDemonstration.LoadFromJson(json, documentFactory, eventStreamFactory);
    }
}

#nullable enable
// <auto-generated />
/// <summary>
/// Interface defining the public state properties of EventUpcastingDemonstration.
/// </summary>
public interface IEventUpcastingDemonstration
{
    public Dictionary<System.String, TaskFlow.Domain.Projections.UpcastingDemoProject>? DemoProjects { get; }
    public String? CheckpointFingerprint { get; }
}
#nullable restore

[JsonSerializable(typeof(ProjectInitiated))]
[JsonSerializable(typeof(ProjectRebranded))]
[JsonSerializable(typeof(ProjectCompleted))]
[JsonSerializable(typeof(ProjectCompletedSuccessfully))]
[JsonSerializable(typeof(ProjectCancelled))]
[JsonSerializable(typeof(ProjectFailed))]
[JsonSerializable(typeof(ProjectDelivered))]
[JsonSerializable(typeof(ProjectSuspended))]
[JsonSerializable(typeof(ProjectReactivated))]
[JsonSerializable(typeof(MemberJoinedProject))]
[JsonSerializable(typeof(MemberLeftProject))]
[JsonSerializable(typeof(ProjectMerged))]
[JsonSerializable(typeof(ProjectScopeRefined))]
[JsonSerializable(typeof(WorkItemReordered))]
[JsonSerializable(typeof(WorkItemAddedToProject))]
[JsonSerializable(typeof(WorkItemStatusChangedInProject))]
[JsonSerializable(typeof(System.Collections.Generic.Dictionary<System.String, TaskFlow.Domain.Projections.UpcastingDemoProject>))]
[JsonSerializable(typeof(TaskFlow.Domain.Projections.UpcastingDemoProject))]
[JsonSerializable(typeof(System.Boolean))]
[JsonSerializable(typeof(TaskFlow.Domain.ValueObjects.Project.ProjectOutcome))]
[JsonSerializable(typeof(System.Enum))]
[JsonSerializable(typeof(TaskFlow.Domain.Projections.EventSummary))]
[JsonSerializable(typeof(System.Collections.Generic.Dictionary<System.String, ErikLieben.FA.ES.Projections.IProjectionWhenParameterValueFactory>))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Projections.IProjectionWhenParameterValueFactory))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Checkpoint))]
[JsonSerializable(typeof(EventUpcastingDemonstration))]
// <auto-generated />
/// <summary>
/// JSON serializer context for EventUpcastingDemonstration types.
/// </summary>
internal partial class EventUpcastingDemonstrationJsonSerializerContext : JsonSerializerContext
{
}

