using Azure.Storage.Blobs;
using ErikLieben.FA.ES;
using ErikLieben.FA.ES.AzureStorage.Blob;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Projections;
using ErikLieben.FA.ES.VersionTokenParts;
using Microsoft.Extensions.Azure;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.Project;
using TaskFlow.Domain.Events.WorkItem;

namespace TaskFlow.Domain.Projections;

// <auto-generated />
[GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
[ExcludeFromCodeCoverage]
public partial class ProjectKanbanBoard : IProjectKanbanBoard
{

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public ProjectKanbanBoard() : base()
    {
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public ProjectKanbanBoard(IObjectDocumentFactory documentFactory, IEventStreamFactory eventStreamFactory)
      : base(documentFactory, eventStreamFactory)
    {
    }

#nullable enable
    /// <summary>
    /// Dispatches events to When methods. Called by base RoutedProjection.Fold after routing context setup.
    /// </summary>
    protected override void DispatchToWhen(IEvent @event, VersionToken versionToken)
    {
        switch (@event.EventType)
        {
            case "Project.Initiated":
                When(JsonEvent.ToEvent(@event, ProjectInitiatedJsonSerializerContext.Default.ProjectInitiated).Data(), GetWhenParameterValue<String, ProjectInitiated>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.Planned":
                When(JsonEvent.ToEvent(@event, WorkItemPlannedJsonSerializerContext.Default.WorkItemPlanned).Data(), GetWhenParameterValue<String, WorkItemPlanned>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.ResponsibilityAssigned":
                When(JsonEvent.ToEvent(@event, ResponsibilityAssignedJsonSerializerContext.Default.ResponsibilityAssigned).Data(), GetWhenParameterValue<String, ResponsibilityAssigned>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.WorkCommenced":
                When(JsonEvent.ToEvent(@event, WorkCommencedJsonSerializerContext.Default.WorkCommenced).Data(), GetWhenParameterValue<String, WorkCommenced>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.WorkCompleted":
                When(JsonEvent.ToEvent(@event, WorkCompletedJsonSerializerContext.Default.WorkCompleted).Data(), GetWhenParameterValue<String, WorkCompleted>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.ResponsibilityRelinquished":
                When(JsonEvent.ToEvent(@event, ResponsibilityRelinquishedJsonSerializerContext.Default.ResponsibilityRelinquished).Data(), GetWhenParameterValue<String, ResponsibilityRelinquished>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.DeadlineEstablished":
                When(JsonEvent.ToEvent(@event, DeadlineEstablishedJsonSerializerContext.Default.DeadlineEstablished).Data(), GetWhenParameterValue<String, DeadlineEstablished>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.DeadlineRemoved":
                When(JsonEvent.ToEvent(@event, DeadlineRemovedJsonSerializerContext.Default.DeadlineRemoved).Data(), GetWhenParameterValue<String, DeadlineRemoved>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.EffortReestimated":
                When(JsonEvent.ToEvent(@event, EffortReestimatedJsonSerializerContext.Default.EffortReestimated).Data(), GetWhenParameterValue<String, EffortReestimated>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.FeedbackProvided":
                When(JsonEvent.ToEvent(@event, FeedbackProvidedJsonSerializerContext.Default.FeedbackProvided).Data(), GetWhenParameterValue<String, FeedbackProvided>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.RequirementsRefined":
                When(JsonEvent.ToEvent(@event, RequirementsRefinedJsonSerializerContext.Default.RequirementsRefined).Data(), GetWhenParameterValue<String, RequirementsRefined>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.MovedBackFromCompletedToInProgress":
                When(JsonEvent.ToEvent(@event, MovedBackFromCompletedToInProgressJsonSerializerContext.Default.MovedBackFromCompletedToInProgress).Data(), GetWhenParameterValue<String, MovedBackFromCompletedToInProgress>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.MovedBackFromCompletedToPlanned":
                When(JsonEvent.ToEvent(@event, MovedBackFromCompletedToPlannedJsonSerializerContext.Default.MovedBackFromCompletedToPlanned).Data(), GetWhenParameterValue<String, MovedBackFromCompletedToPlanned>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.MovedBackFromInProgressToPlanned":
                When(JsonEvent.ToEvent(@event, MovedBackFromInProgressToPlannedJsonSerializerContext.Default.MovedBackFromInProgressToPlanned).Data(), GetWhenParameterValue<String, MovedBackFromInProgressToPlanned>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.Relocated":
                When(JsonEvent.ToEvent(@event, WorkItemRelocatedJsonSerializerContext.Default.WorkItemRelocated).Data(), GetWhenParameterValue<String, WorkItemRelocated>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.Reprioritized":
                When(JsonEvent.ToEvent(@event, WorkItemReprioritizedJsonSerializerContext.Default.WorkItemReprioritized).Data(), GetWhenParameterValue<String, WorkItemReprioritized>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.Retagged":
                When(JsonEvent.ToEvent(@event, WorkItemRetaggedJsonSerializerContext.Default.WorkItemRetagged).Data(), GetWhenParameterValue<String, WorkItemRetagged>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.Revived":
                When(JsonEvent.ToEvent(@event, WorkItemRevivedJsonSerializerContext.Default.WorkItemRevived).Data(), GetWhenParameterValue<String, WorkItemRevived>(
                         "String",
                         versionToken, @event)!);
                break;
            case "WorkItem.DragMarkedAsAccidental":
                When(JsonEvent.ToEvent(@event, DragMarkedAsAccidentalJsonSerializerContext.Default.DragMarkedAsAccidental).Data(), GetWhenParameterValue<String, DragMarkedAsAccidental>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Project.LanguagesConfigured":
                When(JsonEvent.ToEvent(@event, ProjectLanguagesConfiguredJsonSerializerContext.Default.ProjectLanguagesConfigured).Data(), GetWhenParameterValue<String, ProjectLanguagesConfigured>(
                         "String",
                         versionToken, @event)!);
                break;
        }
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override Task PostWhenAll(IObjectDocument document) { return Task.CompletedTask; }
#nullable restore

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override Dictionary<string, IProjectionWhenParameterValueFactory> WhenParameterValueFactories { get; } =
          new Dictionary<string, IProjectionWhenParameterValueFactory>(){
              {"String", new TaskFlow.Domain.Projections.ObjectIdWhenValueFactory()}
          };

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public static ProjectKanbanBoard? LoadFromJson(string json, IObjectDocumentFactory documentFactory, IEventStreamFactory eventStreamFactory)
    {
        // Deserialize each property manually to preserve data
        System.Collections.Generic.Dictionary<System.String, TaskFlow.Domain.Projections.ProjectInfo>? projects = null;
        System.Collections.Generic.IReadOnlyDictionary<System.String, ErikLieben.FA.ES.Projections.Projection>? destinations = null;
        ErikLieben.FA.ES.Projections.RoutedProjectionMetadata? routingMetadata = null;
        ErikLieben.FA.ES.Projections.DestinationRegistry? registry = null;
        System.String? pathTemplate = null;
        System.Object? metadata = null;
        ErikLieben.FA.ES.Documents.IObjectDocument? currentDocument = null;
        System.String? checkpointFingerprint = null;
        ErikLieben.FA.ES.Projections.ProjectionStatus? status = null;
        System.Nullable<System.DateTimeOffset> statusChangedAt = null;
        ErikLieben.FA.ES.Projections.RebuildInfo? rebuildInfo = null;
        System.Int32? schemaVersion = null;
        System.Int32? codeSchemaVersion = null;
        System.Boolean? needsSchemaUpgrade = null;
        Checkpoint checkpoint = [];

        var reader = new Utf8JsonReader(System.Text.Encoding.UTF8.GetBytes(json));

        if (!reader.Read() || reader.TokenType != JsonTokenType.StartObject)
            return null;

        while (reader.Read())
        {
            if (reader.TokenType == JsonTokenType.EndObject)
                break;

            if (reader.TokenType != JsonTokenType.PropertyName)
                continue;

            string? propertyName = reader.GetString();
            reader.Read();

            switch (propertyName)
            {
                case "Projects":
                    projects = JsonSerializer.Deserialize<System.Collections.Generic.Dictionary<System.String, TaskFlow.Domain.Projections.ProjectInfo>>(ref reader, ProjectKanbanBoardJsonSerializerContext.Default.Options);
                    break;
                case "Destinations":
                    destinations = JsonSerializer.Deserialize<System.Collections.Generic.IReadOnlyDictionary<System.String, ErikLieben.FA.ES.Projections.Projection>>(ref reader, ProjectKanbanBoardJsonSerializerContext.Default.Options);
                    break;
                case "RoutingMetadata":
                    routingMetadata = JsonSerializer.Deserialize<ErikLieben.FA.ES.Projections.RoutedProjectionMetadata>(ref reader, ProjectKanbanBoardJsonSerializerContext.Default.Options);
                    break;
                case "Registry":
                    registry = JsonSerializer.Deserialize<ErikLieben.FA.ES.Projections.DestinationRegistry>(ref reader, ProjectKanbanBoardJsonSerializerContext.Default.Options);
                    break;
                case "PathTemplate":
                    pathTemplate = JsonSerializer.Deserialize<System.String>(ref reader, ProjectKanbanBoardJsonSerializerContext.Default.Options);
                    break;
                case "Metadata":
                    metadata = JsonSerializer.Deserialize<System.Object>(ref reader, ProjectKanbanBoardJsonSerializerContext.Default.Options);
                    break;
                case "$checkpoint":
                    checkpoint = JsonSerializer.Deserialize<ErikLieben.FA.ES.Checkpoint>(ref reader, ProjectKanbanBoardJsonSerializerContext.Default.Options) ?? [];
                    break;
                case "CurrentDocument":
                    currentDocument = JsonSerializer.Deserialize<ErikLieben.FA.ES.Documents.IObjectDocument>(ref reader, ProjectKanbanBoardJsonSerializerContext.Default.Options);
                    break;
                case "$checkpointFingerprint":
                    checkpointFingerprint = JsonSerializer.Deserialize<System.String>(ref reader, ProjectKanbanBoardJsonSerializerContext.Default.Options);
                    break;
                case "Status":
                    status = JsonSerializer.Deserialize<ErikLieben.FA.ES.Projections.ProjectionStatus>(ref reader, ProjectKanbanBoardJsonSerializerContext.Default.Options);
                    break;
                case "StatusChangedAt":
                    statusChangedAt = JsonSerializer.Deserialize<System.Nullable<System.DateTimeOffset>>(ref reader, ProjectKanbanBoardJsonSerializerContext.Default.Options);
                    break;
                case "RebuildInfo":
                    rebuildInfo = JsonSerializer.Deserialize<ErikLieben.FA.ES.Projections.RebuildInfo>(ref reader, ProjectKanbanBoardJsonSerializerContext.Default.Options);
                    break;
                case "SchemaVersion":
                    schemaVersion = JsonSerializer.Deserialize<System.Int32>(ref reader, ProjectKanbanBoardJsonSerializerContext.Default.Options);
                    break;
                case "CodeSchemaVersion":
                    codeSchemaVersion = JsonSerializer.Deserialize<System.Int32>(ref reader, ProjectKanbanBoardJsonSerializerContext.Default.Options);
                    break;
                case "NeedsSchemaUpgrade":
                    needsSchemaUpgrade = JsonSerializer.Deserialize<System.Boolean>(ref reader, ProjectKanbanBoardJsonSerializerContext.Default.Options);
                    break;
            }
        }

        // Create instance with factories and deserialized properties
        var instance = new ProjectKanbanBoard();

        if (projects != null)
        {
            foreach (var kvp in projects)
            {
                instance.Projects[kvp.Key] = kvp.Value;
            }
        }
        instance.Checkpoint = checkpoint;
        instance.CheckpointFingerprint = checkpointFingerprint;

        return instance;
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public override string ToJson()
    {
        return JsonSerializer.Serialize(this, ProjectKanbanBoardJsonSerializerContext.Default.ProjectKanbanBoard);
    }

    /// <summary>
    /// Gets or sets the checkpoint tracking the last processed event position.
    /// </summary>
    [JsonIgnore]
    public override Checkpoint Checkpoint { get; set; } = [];

    /// <summary>
    /// Gets the schema version defined in code via [ProjectionVersion] attribute.
    /// </summary>
    [JsonIgnore]
    public override int CodeSchemaVersion => 1;

    /// <summary>
    /// Creates a destination instance with proper initialization.
    /// AOT-compatible implementation without reflection.
    /// </summary>
    protected override TDestination CreateDestinationInstance<TDestination>(string destinationKey)
    {
        if (typeof(TDestination) == typeof(ProjectKanbanDestination))
        {
            var destination = new ProjectKanbanDestination(DocumentFactory!, EventStreamFactory!);
            return (TDestination)(Projection)destination;
        }
        else if (typeof(TDestination) == typeof(ProjectKanbanLanguageDestination))
        {
            var destination = new ProjectKanbanLanguageDestination(DocumentFactory!, EventStreamFactory!);
            return (TDestination)(Projection)destination;
        }

        throw new ArgumentException($"Unknown destination type: {typeof(TDestination).Name}", nameof(TDestination));
    }
}

/// <summary>
/// Factory for creating and managing ProjectKanbanBoard routed blob-based projections.
/// Main file at [BlobJsonProjection] path contains $checkpoint and $metadata.
/// Each destination is stored in a separate file.
/// </summary>
public partial class ProjectKanbanBoardFactory(
    IAzureClientFactory<BlobServiceClient> blobServiceClientFactory,
    IObjectDocumentFactory objectDocumentFactory,
    IEventStreamFactory eventStreamFactory)
    : RoutedBlobProjectionFactory<ProjectKanbanBoard>(
        blobServiceClientFactory,
        "BlobStorage",
        "projections/kanban.json")
{
    /// <summary>
    /// Gets the JSON serializer context for the projection.
    /// </summary>
    protected override JsonSerializerContext GetProjectionJsonContext()
    {
        return ProjectKanbanBoardJsonSerializerContext.Default;
    }

    /// <summary>
    /// Loads the main projection (checkpoint and metadata) from JSON.
    /// </summary>
    protected override ProjectKanbanBoard? LoadMainProjectionFromJson(
        string json,
        IObjectDocumentFactory documentFactory,
        IEventStreamFactory eventStreamFactory)
    {
        return ProjectKanbanBoard.LoadFromJson(json, documentFactory, eventStreamFactory);
    }

    /// <summary>
    /// Loads a destination projection from JSON.
    /// </summary>
    protected override Projection LoadDestinationFromJson(
        string json,
        IObjectDocumentFactory documentFactory,
        IEventStreamFactory eventStreamFactory,
        string destinationKey)
    {
        // Multiple destination types - try to deserialize based on registry
        Projection? result;
        result = ProjectKanbanDestination.LoadFromJson(json, documentFactory, eventStreamFactory);
        if (result != null) return result;
        result = ProjectKanbanLanguageDestination.LoadFromJson(json, documentFactory, eventStreamFactory);
        if (result != null) return result;
        throw new ArgumentException($"Failed to deserialize destination {destinationKey}", nameof(destinationKey));
    }

    /// <summary>
    /// Checks if a destination type has external checkpoint enabled.
    /// </summary>
    protected override bool DestinationHasExternalCheckpoint(string destinationTypeName)
    {
        return false;
    }

    /// <summary>
    /// Serializes the main projection (checkpoint and metadata) to JSON.
    /// </summary>
    protected override string SerializeMainProjection(ProjectKanbanBoard projection)
    {
        return projection.ToJson();
    }

    /// <summary>
    /// Gets save tasks for all destinations.
    /// </summary>
    protected override IEnumerable<Task> GetDestinationSaveTasks(
        ProjectKanbanBoard projection,
        BlobContainerClient containerClient,
        CancellationToken cancellationToken)
    {
        if (projection.Destinations == null)
        {
            yield break;
        }

        foreach (var kvp in projection.Destinations)
        {
            var destinationKey = kvp.Key;
            var destination = kvp.Value;

            // Get the blob path from registry
            if (projection.Registry.Destinations.TryGetValue(destinationKey, out var metadata) &&
                metadata.Metadata.TryGetValue("blobPath", out var blobPath))
            {
                var json = destination.ToJson();
                yield return UploadBlobAsync(containerClient, blobPath, json, cancellationToken);

                // Save external checkpoint if the destination type has it enabled
                if (DestinationHasExternalCheckpoint(metadata.DestinationTypeName))
                {
                    yield return SaveDestinationCheckpointAsync(blobPath, destination, cancellationToken);
                }
            }
        }
    }

    /// <summary>
    /// Adds a loaded destination to the projection.
    /// </summary>
    protected override void AddDestinationToProjection(
        ProjectKanbanBoard projection,
        string destinationKey,
        Projection destination)
    {
        // Use reflection to access the private _destinations field in RoutedProjection
        var destinationsField = typeof(RoutedProjection).GetField("_destinations", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
        var destinations = destinationsField?.GetValue(projection) as System.Collections.Concurrent.ConcurrentDictionary<string, Projection>;

        if (destinations != null)
        {
            destinations[destinationKey] = destination;
        }
    }

    /// <summary>
    /// Sets the factories on the projection.
    /// </summary>
    protected override void SetFactories(
        ProjectKanbanBoard projection,
        IObjectDocumentFactory documentFactory,
        IEventStreamFactory eventStreamFactory)
    {
        // Use reflection to set the private readonly fields
        var docField = typeof(Projection).GetField("DocumentFactory", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
        var streamField = typeof(Projection).GetField("EventStreamFactory", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);

        docField?.SetValue(projection, documentFactory);
        streamField?.SetValue(projection, eventStreamFactory);
    }

    /// <summary>
    /// Gets the path template for a destination type from its [BlobJsonProjection] attribute.
    /// </summary>
    protected override string? GetDestinationPathTemplate(string destinationTypeName)
    {
        return destinationTypeName switch
        {
            "ProjectKanbanDestination" => "projections/kanban/{projectId}.json",
            "ProjectKanbanLanguageDestination" => "projections/kanban/{projectId}/{languageCode}.json",
            _ => null
        };
    }
}

/// <summary>
/// JSON serializer context for DestinationRegistry and related types.
/// </summary>
[JsonSerializable(typeof(DestinationRegistry))]
[JsonSerializable(typeof(DestinationMetadata))]
[JsonSerializable(typeof(RoutedProjectionMetadata))]
[JsonSerializable(typeof(ProjectKanbanDestination))]
[JsonSourceGenerationOptions(WriteIndented = true)]
internal partial class ProjectKanbanBoardDestinationRegistryJsonContext : JsonSerializerContext
{
}

#nullable enable
// <auto-generated />
/// <summary>
/// Interface defining the public state properties of ProjectKanbanBoard.
/// </summary>
public interface IProjectKanbanBoard
{
    public Dictionary<System.String, TaskFlow.Domain.Projections.ProjectInfo>? Projects { get; }
    public IReadOnlyDictionary<System.String, ErikLieben.FA.ES.Projections.Projection>? Destinations { get; }
    public RoutedProjectionMetadata? RoutingMetadata { get; }
    public DestinationRegistry? Registry { get; }
    public String? PathTemplate { get; }
    public Object? Metadata { get; }
    public IObjectDocument? CurrentDocument { get; }
    public String? CheckpointFingerprint { get; }
    public ProjectionStatus Status { get; }
    public Nullable<System.DateTimeOffset> StatusChangedAt { get; }
    public RebuildInfo? RebuildInfo { get; }
    public Int32 SchemaVersion { get; }
    public Int32 CodeSchemaVersion { get; }
    public Boolean NeedsSchemaUpgrade { get; }
}
#nullable restore

[JsonSerializable(typeof(ProjectInitiated))]
[JsonSerializable(typeof(WorkItemPlanned))]
[JsonSerializable(typeof(ResponsibilityAssigned))]
[JsonSerializable(typeof(WorkCommenced))]
[JsonSerializable(typeof(WorkCompleted))]
[JsonSerializable(typeof(ResponsibilityRelinquished))]
[JsonSerializable(typeof(DeadlineEstablished))]
[JsonSerializable(typeof(DeadlineRemoved))]
[JsonSerializable(typeof(EffortReestimated))]
[JsonSerializable(typeof(FeedbackProvided))]
[JsonSerializable(typeof(RequirementsRefined))]
[JsonSerializable(typeof(MovedBackFromCompletedToInProgress))]
[JsonSerializable(typeof(MovedBackFromCompletedToPlanned))]
[JsonSerializable(typeof(MovedBackFromInProgressToPlanned))]
[JsonSerializable(typeof(WorkItemRelocated))]
[JsonSerializable(typeof(WorkItemReprioritized))]
[JsonSerializable(typeof(WorkItemRetagged))]
[JsonSerializable(typeof(WorkItemRevived))]
[JsonSerializable(typeof(DragMarkedAsAccidental))]
[JsonSerializable(typeof(ProjectLanguagesConfigured))]
[JsonSerializable(typeof(System.Collections.Generic.Dictionary<System.String, TaskFlow.Domain.Projections.ProjectInfo>))]
[JsonSerializable(typeof(TaskFlow.Domain.Projections.ProjectInfo))]
[JsonSerializable(typeof(System.Collections.Generic.IReadOnlyDictionary<System.String, ErikLieben.FA.ES.Projections.Projection>))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Projections.Projection))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Checkpoint))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Projections.ProjectionStatus))]
[JsonSerializable(typeof(System.Enum))]
[JsonSerializable(typeof(System.DateTimeOffset))]
[JsonSerializable(typeof(System.DayOfWeek))]
[JsonSerializable(typeof(System.TimeSpan))]
[JsonSerializable(typeof(System.Double))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Projections.RebuildInfo))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Projections.RebuildStrategy))]
[JsonSerializable(typeof(System.Boolean))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Projections.RoutedProjectionMetadata))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Projections.DestinationRegistry))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Projections.DestinationMetadata))]
[JsonSerializable(typeof(System.Object))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Documents.IObjectDocument))]
[JsonSerializable(typeof(System.Collections.Generic.Dictionary<System.String, ErikLieben.FA.ES.Projections.IProjectionWhenParameterValueFactory>))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Projections.IProjectionWhenParameterValueFactory))]
[JsonSerializable(typeof(System.Nullable<System.DateTimeOffset>))]
[JsonSerializable(typeof(ProjectKanbanBoard))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ProjectKanbanBoard types.
/// </summary>
internal partial class ProjectKanbanBoardJsonSerializerContext : JsonSerializerContext
{
}

