using Azure.Storage.Blobs;
using ErikLieben.FA.ES;
using ErikLieben.FA.ES.AzureStorage.Blob;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Projections;
using ErikLieben.FA.ES.VersionTokenParts;
using Microsoft.Extensions.Azure;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.Release;

namespace TaskFlow.Domain.Projections;

// <auto-generated />
[GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
[ExcludeFromCodeCoverage]
public partial class ReleaseDashboard : IReleaseDashboard
{

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public ReleaseDashboard() : base()
    {
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public ReleaseDashboard(IObjectDocumentFactory documentFactory, IEventStreamFactory eventStreamFactory)
      : base(documentFactory, eventStreamFactory)
    {
    }

#nullable enable
    /// <summary>
    /// Applies an event to the projection by dispatching to the appropriate When method using version token.
    /// This is the primary implementation that avoids redundant document lookups.
    /// </summary>
    /// <typeparam name="T">The type of additional data passed through the execution context.</typeparam>
    /// <param name="event">The event to apply to the projection.</param>
    /// <param name="versionToken">The version token associated with the event.</param>
    /// <param name="data">Optional data to pass through the execution context.</param>
    /// <param name="parentContext">Optional parent execution context for nested projections.</param>
    /// <returns>A task representing the asynchronous fold operation.</returns>
    public override Task Fold<T>(IEvent @event, VersionToken versionToken, T? data = default(T?), IExecutionContext? parentContext = null) where T : class
    {

        switch (@event.EventType)
        {
            case "Release.Created":
                When(JsonEvent.ToEvent(@event, ReleaseCreatedJsonSerializerContext.Default.ReleaseCreated).Data(), GetWhenParameterValue<String, ReleaseCreated>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Release.Staged":
                When(JsonEvent.ToEvent(@event, ReleaseStagedJsonSerializerContext.Default.ReleaseStaged).Data(), GetWhenParameterValue<String, ReleaseStaged>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Release.Deployed":
                When(JsonEvent.ToEvent(@event, ReleaseDeployedJsonSerializerContext.Default.ReleaseDeployed).Data(), GetWhenParameterValue<String, ReleaseDeployed>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Release.Completed":
                When(JsonEvent.ToEvent(@event, ReleaseCompletedJsonSerializerContext.Default.ReleaseCompleted).Data(), GetWhenParameterValue<String, ReleaseCompleted>(
                         "String",
                         versionToken, @event)!);
                break;
            case "Release.RolledBack":
                When(JsonEvent.ToEvent(@event, ReleaseRolledBackJsonSerializerContext.Default.ReleaseRolledBack).Data(), GetWhenParameterValue<String, ReleaseRolledBack>(
                         "String",
                         versionToken, @event)!);
                break;
        }

        return Task.CompletedTask;
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override Task PostWhenAll(IObjectDocument document) { return Task.CompletedTask; }
#nullable restore

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override Dictionary<string, IProjectionWhenParameterValueFactory> WhenParameterValueFactories { get; } =
          new Dictionary<string, IProjectionWhenParameterValueFactory>(){
              {"String", new TaskFlow.Domain.Projections.ObjectIdWhenValueFactory()}
          };

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public static ReleaseDashboard? LoadFromJson(string json, IObjectDocumentFactory documentFactory, IEventStreamFactory eventStreamFactory)
    {
        // Deserialize each property manually to preserve data
        System.Collections.Generic.Dictionary<System.String, TaskFlow.Domain.Projections.ReleaseSummary>? releases = null;
        System.String? checkpointFingerprint = null;
        ErikLieben.FA.ES.Projections.ProjectionStatus? status = null;
        System.Nullable<System.DateTimeOffset> statusChangedAt = null;
        ErikLieben.FA.ES.Projections.RebuildInfo? rebuildInfo = null;
        System.Int32? schemaVersion = null;
        System.Int32? codeSchemaVersion = null;
        System.Boolean? needsSchemaUpgrade = null;
        Checkpoint checkpoint = [];

        var reader = new Utf8JsonReader(System.Text.Encoding.UTF8.GetBytes(json));

        if (!reader.Read() || reader.TokenType != JsonTokenType.StartObject)
            return null;

        while (reader.Read())
        {
            if (reader.TokenType == JsonTokenType.EndObject)
                break;

            if (reader.TokenType != JsonTokenType.PropertyName)
                continue;

            string? propertyName = reader.GetString();
            reader.Read();

            switch (propertyName)
            {
                case "Releases":
                    releases = JsonSerializer.Deserialize<System.Collections.Generic.Dictionary<System.String, TaskFlow.Domain.Projections.ReleaseSummary>>(ref reader, ReleaseDashboardJsonSerializerContext.Default.Options);
                    break;
                case "$checkpoint":
                    checkpoint = JsonSerializer.Deserialize<ErikLieben.FA.ES.Checkpoint>(ref reader, ReleaseDashboardJsonSerializerContext.Default.Options) ?? [];
                    break;
                case "$checkpointFingerprint":
                    checkpointFingerprint = JsonSerializer.Deserialize<System.String>(ref reader, ReleaseDashboardJsonSerializerContext.Default.Options);
                    break;
                case "Status":
                    status = JsonSerializer.Deserialize<ErikLieben.FA.ES.Projections.ProjectionStatus>(ref reader, ReleaseDashboardJsonSerializerContext.Default.Options);
                    break;
                case "StatusChangedAt":
                    statusChangedAt = JsonSerializer.Deserialize<System.Nullable<System.DateTimeOffset>>(ref reader, ReleaseDashboardJsonSerializerContext.Default.Options);
                    break;
                case "RebuildInfo":
                    rebuildInfo = JsonSerializer.Deserialize<ErikLieben.FA.ES.Projections.RebuildInfo>(ref reader, ReleaseDashboardJsonSerializerContext.Default.Options);
                    break;
                case "SchemaVersion":
                    schemaVersion = JsonSerializer.Deserialize<System.Int32>(ref reader, ReleaseDashboardJsonSerializerContext.Default.Options);
                    break;
                case "CodeSchemaVersion":
                    codeSchemaVersion = JsonSerializer.Deserialize<System.Int32>(ref reader, ReleaseDashboardJsonSerializerContext.Default.Options);
                    break;
                case "NeedsSchemaUpgrade":
                    needsSchemaUpgrade = JsonSerializer.Deserialize<System.Boolean>(ref reader, ReleaseDashboardJsonSerializerContext.Default.Options);
                    break;
            }
        }

        // Create instance with factories and deserialized properties
        var instance = new ReleaseDashboard();

        if (releases != null)
        {
            foreach (var kvp in releases)
            {
                instance.Releases[kvp.Key] = kvp.Value;
            }
        }
        instance.Checkpoint = checkpoint;
        instance.CheckpointFingerprint = checkpointFingerprint;

        return instance;
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public override string ToJson()
    {
        return JsonSerializer.Serialize(this, ReleaseDashboardJsonSerializerContext.Default.ReleaseDashboard);
    }

    /// <summary>
    /// Gets or sets the checkpoint tracking the last processed event position.
    /// </summary>
    [JsonIgnore]
    public override Checkpoint Checkpoint { get; set; } = [];
}

/// <summary>
/// Factory for creating and managing ReleaseDashboard blob-based projections.
/// </summary>
public partial class ReleaseDashboardFactory(
    IAzureClientFactory<BlobServiceClient> blobServiceClientFactory,
    IObjectDocumentFactory objectDocumentFactory,
    IEventStreamFactory eventStreamFactory)
    : BlobProjectionFactory<ReleaseDashboard>(
        blobServiceClientFactory,
        "BlobStorage",
        "projections")
{
    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override bool HasExternalCheckpoint => true;

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override ReleaseDashboard New()
    {
        return new ReleaseDashboard(objectDocumentFactory, eventStreamFactory);
    }

    /// <summary>
    /// Loads a ReleaseDashboard instance from JSON with complete state restoration.
    /// </summary>
    /// <param name="json">The JSON string containing the serialized projection state.</param>
    /// <param name="documentFactory">Factory for managing object documents.</param>
    /// <param name="eventStreamFactory">Factory for creating event streams.</param>
    /// <returns>A ReleaseDashboard instance with restored state, or null if deserialization fails.</returns>
    protected override ReleaseDashboard? LoadFromJson(string json, IObjectDocumentFactory documentFactory, IEventStreamFactory eventStreamFactory)
    {
        return ReleaseDashboard.LoadFromJson(json, documentFactory, eventStreamFactory);
    }
}

#nullable enable
// <auto-generated />
/// <summary>
/// Interface defining the public state properties of ReleaseDashboard.
/// </summary>
public interface IReleaseDashboard
{
    public Dictionary<System.String, TaskFlow.Domain.Projections.ReleaseSummary>? Releases { get; }
    public String? CheckpointFingerprint { get; }
    public ProjectionStatus Status { get; }
    public Nullable<System.DateTimeOffset> StatusChangedAt { get; }
    public RebuildInfo? RebuildInfo { get; }
    public Int32 SchemaVersion { get; }
    public Int32 CodeSchemaVersion { get; }
    public Boolean NeedsSchemaUpgrade { get; }
}
#nullable restore

[JsonSerializable(typeof(ReleaseCreated))]
[JsonSerializable(typeof(ReleaseStaged))]
[JsonSerializable(typeof(ReleaseDeployed))]
[JsonSerializable(typeof(ReleaseCompleted))]
[JsonSerializable(typeof(ReleaseRolledBack))]
[JsonSerializable(typeof(System.Collections.Generic.Dictionary<System.String, TaskFlow.Domain.Projections.ReleaseSummary>))]
[JsonSerializable(typeof(TaskFlow.Domain.Projections.ReleaseSummary))]
[JsonSerializable(typeof(TaskFlow.Domain.ValueObjects.Release.ReleaseStatus))]
[JsonSerializable(typeof(System.Enum))]
[JsonSerializable(typeof(System.Collections.Generic.Dictionary<System.String, ErikLieben.FA.ES.Projections.IProjectionWhenParameterValueFactory>))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Projections.IProjectionWhenParameterValueFactory))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Checkpoint))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Projections.ProjectionStatus))]
[JsonSerializable(typeof(System.Nullable<System.DateTimeOffset>))]
[JsonSerializable(typeof(System.DateTimeOffset))]
[JsonSerializable(typeof(System.DayOfWeek))]
[JsonSerializable(typeof(System.TimeSpan))]
[JsonSerializable(typeof(System.Double))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Projections.RebuildInfo))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Projections.RebuildStrategy))]
[JsonSerializable(typeof(System.Boolean))]
[JsonSerializable(typeof(System.Int32))]
[JsonSerializable(typeof(ReleaseDashboard))]
// <auto-generated />
/// <summary>
/// JSON serializer context for ReleaseDashboard types.
/// </summary>
internal partial class ReleaseDashboardJsonSerializerContext : JsonSerializerContext
{
}

