using Azure.Storage.Blobs;
using ErikLieben.FA.ES;
using ErikLieben.FA.ES.AzureStorage.Blob;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Projections;
using ErikLieben.FA.ES.VersionTokenParts;
using Microsoft.Extensions.Azure;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.UserProfile;

namespace TaskFlow.Domain.Projections;

// <auto-generated />
[GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
[ExcludeFromCodeCoverage]
public partial class TeamMembers : ITeamMembers
{

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public TeamMembers() : base()
    {
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public TeamMembers(IObjectDocumentFactory documentFactory, IEventStreamFactory eventStreamFactory)
      : base(documentFactory, eventStreamFactory)
    {
    }

#nullable enable
    /// <summary>
    /// Applies an event to the projection by dispatching to the appropriate When method using version token.
    /// This is the primary implementation that avoids redundant document lookups.
    /// </summary>
    /// <typeparam name="T">The type of additional data passed through the execution context.</typeparam>
    /// <param name="event">The event to apply to the projection.</param>
    /// <param name="versionToken">The version token associated with the event.</param>
    /// <param name="data">Optional data to pass through the execution context.</param>
    /// <param name="parentContext">Optional parent execution context for nested projections.</param>
    /// <returns>A task representing the asynchronous fold operation.</returns>
    public override Task Fold<T>(IEvent @event, VersionToken versionToken, T? data = default(T?), IExecutionContext? parentContext = null) where T : class
    {

        switch (@event.EventType)
        {
            case "UserProfile.Created":
                When(JsonEvent.ToEvent(@event, UserProfileCreatedJsonSerializerContext.Default.UserProfileCreated).Data(), GetWhenParameterValue<String, UserProfileCreated>(
                         "String",
                         versionToken, @event)!);
                break;
            case "UserProfile.Updated":
                When(JsonEvent.ToEvent(@event, UserProfileUpdatedJsonSerializerContext.Default.UserProfileUpdated).Data(), GetWhenParameterValue<String, UserProfileUpdated>(
                         "String",
                         versionToken, @event)!);
                break;
        }

        return Task.CompletedTask;
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override Task PostWhenAll(IObjectDocument document) { return Task.CompletedTask; }
#nullable restore

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override Dictionary<string, IProjectionWhenParameterValueFactory> WhenParameterValueFactories { get; } =
          new Dictionary<string, IProjectionWhenParameterValueFactory>(){
              {"String", new TaskFlow.Domain.Projections.ObjectIdWhenValueFactory()}
          };

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public static TeamMembers? LoadFromJson(string json, IObjectDocumentFactory documentFactory, IEventStreamFactory eventStreamFactory)
    {
        // Deserialize each property manually to preserve data
        System.Collections.Generic.Dictionary<System.String, TaskFlow.Domain.Projections.TeamMemberInfo>? members = null;
        System.String? checkpointFingerprint = null;
        Checkpoint checkpoint = [];

        var reader = new Utf8JsonReader(System.Text.Encoding.UTF8.GetBytes(json));

        if (!reader.Read() || reader.TokenType != JsonTokenType.StartObject)
            return null;

        while (reader.Read())
        {
            if (reader.TokenType == JsonTokenType.EndObject)
                break;

            if (reader.TokenType != JsonTokenType.PropertyName)
                continue;

            string? propertyName = reader.GetString();
            reader.Read();

            switch (propertyName)
            {
                case "Members":
                    members = JsonSerializer.Deserialize<System.Collections.Generic.Dictionary<System.String, TaskFlow.Domain.Projections.TeamMemberInfo>>(ref reader, TeamMembersJsonSerializerContext.Default.Options);
                    break;
                case "$checkpoint":
                    checkpoint = JsonSerializer.Deserialize<ErikLieben.FA.ES.Checkpoint>(ref reader, TeamMembersJsonSerializerContext.Default.Options) ?? [];
                    break;
                case "$checkpointFingerprint":
                    checkpointFingerprint = JsonSerializer.Deserialize<System.String>(ref reader, TeamMembersJsonSerializerContext.Default.Options);
                    break;
            }
        }

        // Create instance with factories and deserialized properties
        var instance = new TeamMembers(documentFactory, eventStreamFactory);

        if (members != null)
        {
            foreach (var kvp in members)
            {
                instance.Members[kvp.Key] = kvp.Value;
            }
        }
        instance.Checkpoint = checkpoint;
        instance.CheckpointFingerprint = checkpointFingerprint;

        return instance;
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    public override string ToJson()
    {
        return JsonSerializer.Serialize(this, TeamMembersJsonSerializerContext.Default.TeamMembers);
    }

    /// <summary>
    /// Gets or sets the checkpoint tracking the last processed event position.
    /// </summary>
    [JsonIgnore]
    public override Checkpoint Checkpoint { get; set; } = [];
}

/// <summary>
/// Factory for creating and managing TeamMembers blob-based projections.
/// </summary>
public partial class TeamMembersFactory(
    IAzureClientFactory<BlobServiceClient> blobServiceClientFactory,
    IObjectDocumentFactory objectDocumentFactory,
    IEventStreamFactory eventStreamFactory)
    : BlobProjectionFactory<TeamMembers>(
        blobServiceClientFactory,
        "BlobStorage",
        "projections/userprofiles/team-members.json")
{
    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override bool HasExternalCheckpoint => true;

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0.0")]
    [ExcludeFromCodeCoverage]
    protected override TeamMembers New()
    {
        return new TeamMembers(objectDocumentFactory, eventStreamFactory);
    }

    /// <summary>
    /// Loads a TeamMembers instance from JSON with complete state restoration.
    /// </summary>
    /// <param name="json">The JSON string containing the serialized projection state.</param>
    /// <param name="documentFactory">Factory for managing object documents.</param>
    /// <param name="eventStreamFactory">Factory for creating event streams.</param>
    /// <returns>A TeamMembers instance with restored state, or null if deserialization fails.</returns>
    protected override TeamMembers? LoadFromJson(string json, IObjectDocumentFactory documentFactory, IEventStreamFactory eventStreamFactory)
    {
        return TeamMembers.LoadFromJson(json, documentFactory, eventStreamFactory);
    }
}

#nullable enable
// <auto-generated />
/// <summary>
/// Interface defining the public state properties of TeamMembers.
/// </summary>
public interface ITeamMembers
{
    public Dictionary<System.String, TaskFlow.Domain.Projections.TeamMemberInfo>? Members { get; }
    public String? CheckpointFingerprint { get; }
}
#nullable restore

[JsonSerializable(typeof(UserProfileCreated))]
[JsonSerializable(typeof(UserProfileUpdated))]
[JsonSerializable(typeof(System.Collections.Generic.Dictionary<System.String, TaskFlow.Domain.Projections.TeamMemberInfo>))]
[JsonSerializable(typeof(TaskFlow.Domain.Projections.TeamMemberInfo))]
[JsonSerializable(typeof(System.Collections.Generic.Dictionary<System.String, ErikLieben.FA.ES.Projections.IProjectionWhenParameterValueFactory>))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Projections.IProjectionWhenParameterValueFactory))]
[JsonSerializable(typeof(ErikLieben.FA.ES.Checkpoint))]
[JsonSerializable(typeof(TeamMembers))]
// <auto-generated />
/// <summary>
/// JSON serializer context for TeamMembers types.
/// </summary>
internal partial class TeamMembersJsonSerializerContext : JsonSerializerContext
{
}

