trigger: none

pr:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: 'Release'

resources:
  repositories:
    - repository: templates
      type: git
      name: ErikLieben.FA/build-templates
    - repository: self
      type: github
      name: eriklieben/ErikLieben.FA.ES
      endpoint: github.com_eriklieben

extends:
    template: NuGet/pr_template.yaml@templates
    parameters:
      repositoryName: 'eriklieben/ErikLieben.FA.ES'
      solutionPath: 'ErikLieben.FA.ES.sln'
      sonarCloudProjectKey: 'eriklieben_ErikLieben.FA.ES'
      buildConfiguration: '$(BuildConfiguration)'
