import { Component, inject, signal, OnInit, effect, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatDividerModule } from '@angular/material/divider';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { CodeHighlighterService } from '../../../core/services/code-highlighter.service';
import { ThemeService } from '../../../core/services/theme.service';

interface NavItem {
  id: string;
  label: string;
  icon: string;
}

@Component({
  selector: 'app-cli-docs',
  imports: [
    CommonModule,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatDividerModule
  ],
  templateUrl: './cli.component.html',
  styleUrl: './cli.component.css'
})
export class CliComponent implements OnInit {
  private readonly codeHighlighter = inject(CodeHighlighterService);
  private readonly themeService = inject(ThemeService);
  private readonly sanitizer = inject(DomSanitizer);

  readonly navItems: NavItem[] = [
    { id: 'overview', label: 'Overview', icon: 'info' },
    { id: 'installation', label: 'Installation', icon: 'download' },
    { id: 'commands', label: 'Commands', icon: 'terminal' },
    { id: 'generated', label: 'Generated Code', icon: 'code' },
    { id: 'example', label: 'Example Output', icon: 'description' },
    { id: 'analysis', label: 'Analysis Process', icon: 'analytics' },
    { id: 'integration', label: 'Build Integration', icon: 'build' },
    { id: 'troubleshooting', label: 'Troubleshooting', icon: 'build_circle' }
  ];

  activeSection = signal<string>('overview');

  installCodeHtml = signal<SafeHtml>('');
  generateCommandCodeHtml = signal<SafeHtml>('');
  watchCommandCodeHtml = signal<SafeHtml>('');
  generatedExampleCodeHtml = signal<SafeHtml>('');
  extensionsExampleCodeHtml = signal<SafeHtml>('');
  cicdCodeHtml = signal<SafeHtml>('');

  private readonly installCode = `# Create tool manifest (first time only)
dotnet new tool-manifest

# Install the CLI tool
dotnet tool install ErikLieben.FA.ES.CLI

# Verify installation
dotnet tool run faes --version`;

  private readonly generateCommandCode = `# Generate code for current solution
dotnet tool run faes generate

# Or specify solution path
dotnet tool run faes generate ./MyApp.sln

# With diff view in VS Code (shows changes)
dotnet tool run faes generate --with-diff`;

  private readonly watchCommandCode = `# Watch for changes and regenerate (full-screen TUI)
dotnet tool run faes watch

# With verbose output
dotnet tool run faes watch --verbose

# Simple output mode (no TUI)
dotnet tool run faes watch --simple`;

  private readonly generatedExampleCode = `// <auto-generated />
namespace MyApp.Domain;

public partial class Customer : Aggregate, ICustomer
{
    // Dispatches events to When methods based on EventType
    public override void Fold(IEvent @event)
    {
        switch (@event.EventType)
        {
            case "Customer.Registered":
                When(JsonEvent.To(@event, CustomerRegisteredJsonSerializerContext.Default.CustomerRegistered));
                break;
            case "Customer.EmailUpdated":
                When(JsonEvent.To(@event, CustomerEmailUpdatedJsonSerializerContext.Default.CustomerEmailUpdated));
                break;
            case "Customer.Deactivated":
                WhenCustomerDeactivated();
                break;
        }
    }

    // Registers all events with their serializers
    protected override void GeneratedSetup()
    {
        Stream.RegisterEvent<CustomerRegistered>(
            "Customer.Registered",
            CustomerRegisteredJsonSerializerContext.Default.CustomerRegistered);
        Stream.RegisterEvent<CustomerEmailUpdated>(
            "Customer.EmailUpdated",
            CustomerEmailUpdatedJsonSerializerContext.Default.CustomerEmailUpdated);
        Stream.RegisterEvent<CustomerDeactivated>(
            "Customer.Deactivated",
            CustomerDeactivatedJsonSerializerContext.Default.CustomerDeactivated);
        Stream.EventTypeRegistry.Freeze();
    }
}

// Generated state interface
public interface ICustomer
{
    string? Name { get; }
    string? Email { get; }
    bool IsActive { get; }
}

// Generated factory interface
public interface ICustomerFactory : IAggregateFactory<Customer, CustomerId> { }

// Generated factory implementation
public class CustomerFactory : ICustomerFactory
{
    public static string ObjectName => "customer";

    public async Task<Customer> CreateAsync(CustomerId id)
    {
        var document = await objectDocumentFactory.GetOrCreateAsync(ObjectName, id.ToString());
        var obj = Create(document);
        await obj.Fold();
        return obj;
    }

    public async Task<Customer> GetAsync(CustomerId id, int? upToVersion = null) { ... }
}

// Generated repository interface and implementation
public interface ICustomerRepository
{
    Task<Customer?> GetByIdAsync(CustomerId id, int? upToVersion = null, CancellationToken ct = default);
    Task<bool> ExistsAsync(CustomerId id, CancellationToken ct = default);
    Task<long> CountAsync(CancellationToken ct = default);
}

public class CustomerRepository : ICustomerRepository { ... }`;

  private readonly extensionsExampleCode = `// <auto-generated />
namespace MyApp.Domain;

// Factory class for creating aggregates
public partial class MyAppDomainFactory : AggregateFactory, IAggregateFactory
{
    public static void Register(IServiceCollection serviceCollection)
    {
        // Aggregate factories
        serviceCollection.AddSingleton<IAggregateFactory<Customer, CustomerId>, CustomerFactory>();
        serviceCollection.AddSingleton<ICustomerFactory, CustomerFactory>();
        serviceCollection.AddScoped<ICustomerRepository, CustomerRepository>();

        serviceCollection.AddSingleton<IAggregateFactory<Order, OrderId>, OrderFactory>();
        serviceCollection.AddSingleton<IOrderFactory, OrderFactory>();
        serviceCollection.AddScoped<IOrderRepository, OrderRepository>();

        serviceCollection.AddSingleton<IAggregateFactory, MyAppDomainFactory>();
    }
}

// Extension method for easy DI registration
public static class MyAppDomainExtensions
{
    public static IServiceCollection ConfigureMyAppDomainFactory(
        this IServiceCollection services)
    {
        MyAppDomainFactory.Register(services);
        return services;
    }
}

// Per-event serializer contexts (AOT-compatible)
[JsonSerializable(typeof(CustomerRegistered))]
internal partial class CustomerRegisteredJsonSerializerContext : JsonSerializerContext { }

[JsonSerializable(typeof(CustomerEmailUpdated))]
internal partial class CustomerEmailUpdatedJsonSerializerContext : JsonSerializerContext { }`;

  private readonly cicdCode = `steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'

# Restore tools (including faes CLI)
- script: dotnet tool restore
  displayName: 'Restore .NET tools'

# Generate code
- script: dotnet tool run faes generate
  displayName: 'Generate event sourcing code'

# Build and test
- script: dotnet build --configuration Release
  displayName: 'Build solution'`;

  constructor() {
    effect(() => {
      this.themeService.theme();
      this.highlightCodeSamples();
    });
  }

  ngOnInit(): void {
    this.highlightCodeSamples();
    this.updateActiveSection();
  }

  @HostListener('window:scroll')
  onScroll(): void {
    this.updateActiveSection();
  }

  private updateActiveSection(): void {
    const sections = this.navItems.map(item => ({
      id: item.id,
      element: document.getElementById(item.id)
    }));

    const scrollPosition = window.scrollY + 100;

    for (let i = sections.length - 1; i >= 0; i--) {
      const section = sections[i];
      if (section.element && section.element.offsetTop <= scrollPosition) {
        this.activeSection.set(section.id);
        return;
      }
    }

    this.activeSection.set('overview');
  }

  scrollToSection(event: Event, sectionId: string): void {
    event.preventDefault();
    const element = document.getElementById(sectionId);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'start' });
      this.activeSection.set(sectionId);
    }
  }

  private async highlightCodeSamples(): Promise<void> {
    const [install, generate, watch, generated, extensions, cicd] = await Promise.all([
      this.codeHighlighter.highlight(this.installCode, { language: 'bash' }),
      this.codeHighlighter.highlight(this.generateCommandCode, { language: 'bash' }),
      this.codeHighlighter.highlight(this.watchCommandCode, { language: 'bash' }),
      this.codeHighlighter.highlight(this.generatedExampleCode, { language: 'csharp' }),
      this.codeHighlighter.highlight(this.extensionsExampleCode, { language: 'csharp' }),
      this.codeHighlighter.highlight(this.cicdCode, { language: 'yaml' })
    ]);

    this.installCodeHtml.set(this.sanitizer.bypassSecurityTrustHtml(install));
    this.generateCommandCodeHtml.set(this.sanitizer.bypassSecurityTrustHtml(generate));
    this.watchCommandCodeHtml.set(this.sanitizer.bypassSecurityTrustHtml(watch));
    this.generatedExampleCodeHtml.set(this.sanitizer.bypassSecurityTrustHtml(generated));
    this.extensionsExampleCodeHtml.set(this.sanitizer.bypassSecurityTrustHtml(extensions));
    this.cicdCodeHtml.set(this.sanitizer.bypassSecurityTrustHtml(cicd));
  }
}
