using ErikLieben.FA.ES;
using ErikLieben.FA.ES.Aggregates;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Processors;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.Epic;
using TaskFlow.Domain.ValueObjects;

#nullable enable

namespace TaskFlow.Domain.Aggregates;

// <auto-generated />
/// <summary>
/// Epic aggregate root implementing event sourcing patterns.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public partial class Epic : Aggregate, IBase, IEpic
{

    /// <summary>
    /// Gets the logical object name for this aggregate type (AOT-friendly static member).
    /// </summary>
    public static string ObjectName => "epic";

    /// <summary>
    /// Creates a new instance of the aggregate from an event stream (AOT-friendly factory).
    /// </summary>
    /// <param name="stream">The event stream for the aggregate.</param>
    /// <returns>A new instance of the aggregate.</returns>
    public static Epic Create(IEventStream stream) => new Epic(stream);

    /// <summary>
    /// Applies an event to the aggregate state by dispatching to the appropriate When method.
    /// </summary>
    /// <param name="event">The event to apply to the aggregate.</param>
    public override void Fold(IEvent @event)
    {
        switch (@event.EventType)
        {
            case "Epic.Created":
                When(JsonEvent.To(@event, EpicCreatedJsonSerializerContext.Default.EpicCreated));
                break;
            case "Epic.Renamed":
                When(JsonEvent.To(@event, EpicRenamedJsonSerializerContext.Default.EpicRenamed));
                break;
            case "Epic.DescriptionUpdated":
                When(JsonEvent.To(@event, EpicDescriptionUpdatedJsonSerializerContext.Default.EpicDescriptionUpdated));
                break;
            case "Epic.ProjectAdded":
                When(JsonEvent.To(@event, ProjectAddedToEpicJsonSerializerContext.Default.ProjectAddedToEpic));
                break;
            case "Epic.ProjectRemoved":
                When(JsonEvent.To(@event, ProjectRemovedFromEpicJsonSerializerContext.Default.ProjectRemovedFromEpic));
                break;
            case "Epic.TargetDateChanged":
                When(JsonEvent.To(@event, EpicTargetDateChangedJsonSerializerContext.Default.EpicTargetDateChanged));
                break;
            case "Epic.PriorityChanged":
                When(JsonEvent.To(@event, EpicPriorityChangedJsonSerializerContext.Default.EpicPriorityChanged));
                break;
            case "Epic.Completed":
                WhenEpicCompleted();
                break;
        }

        PostWhen(Stream.Document, @event);
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    protected override void GeneratedSetup()
    {
        Stream.RegisterEvent<EpicCreated>(
      "Epic.Created",
      EpicCreatedJsonSerializerContext.Default.EpicCreated);
        Stream.RegisterEvent<EpicRenamed>(
            "Epic.Renamed",
            EpicRenamedJsonSerializerContext.Default.EpicRenamed);
        Stream.RegisterEvent<EpicDescriptionUpdated>(
            "Epic.DescriptionUpdated",
            EpicDescriptionUpdatedJsonSerializerContext.Default.EpicDescriptionUpdated);
        Stream.RegisterEvent<ProjectAddedToEpic>(
            "Epic.ProjectAdded",
            ProjectAddedToEpicJsonSerializerContext.Default.ProjectAddedToEpic);
        Stream.RegisterEvent<ProjectRemovedFromEpic>(
            "Epic.ProjectRemoved",
            ProjectRemovedFromEpicJsonSerializerContext.Default.ProjectRemovedFromEpic);
        Stream.RegisterEvent<EpicTargetDateChanged>(
            "Epic.TargetDateChanged",
            EpicTargetDateChangedJsonSerializerContext.Default.EpicTargetDateChanged);
        Stream.RegisterEvent<EpicPriorityChanged>(
            "Epic.PriorityChanged",
            EpicPriorityChangedJsonSerializerContext.Default.EpicPriorityChanged);
        Stream.RegisterEvent<EpicCompleted>(
            "Epic.Completed",
            EpicCompletedJsonSerializerContext.Default.EpicCompleted);
        Stream.SetSnapShotType(EpicJsonSerializerContext.Default.EpicSnapshot);
        Stream.SetAggregateType(EpicJsonSerializerContext.Default.Epic);

        // Freeze the EventTypeRegistry for optimized lookups (~50% faster)
        Stream.EventTypeRegistry.Freeze();
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    public override void ProcessSnapshot(object snapshot)
    {
        throw new NotImplementedException();
    }
}

// <auto-generated />
/// <summary>
/// Interface defining the public state properties of Epic.
/// </summary>
public interface IEpic
{
    public String? Name { get; }
    public String? Description { get; }
    public UserProfileId? OwnerId { get; }
    public Nullable<System.DateTime> TargetCompletionDate { get; }
    public DateTime CreatedAt { get; }
    public Boolean IsCompleted { get; }
    public EpicPriority Priority { get; }
    public List<TaskFlow.Domain.ValueObjects.ProjectId>? Projects { get; }
    public ObjectMetadata<TaskFlow.Domain.ValueObjects.EpicId>? Metadata { get; }
}

// <auto-generated />
/// <summary>
/// Snapshot record for persisting Epic aggregate state.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public record EpicSnapshot : IEpic
{
    public required String? Name { get; init; }
    public required String? Description { get; init; }
    public required UserProfileId? OwnerId { get; init; }
    public required Nullable<System.DateTime> TargetCompletionDate { get; init; }
    public required DateTime CreatedAt { get; init; }
    public required Boolean IsCompleted { get; init; }
    public required EpicPriority Priority { get; init; }
    public required List<TaskFlow.Domain.ValueObjects.ProjectId>? Projects { get; init; }
    public required ObjectMetadata<TaskFlow.Domain.ValueObjects.EpicId>? Metadata { get; init; }
}

[JsonSerializable(typeof(EpicCreated))]
[JsonSerializable(typeof(EpicRenamed))]
[JsonSerializable(typeof(EpicDescriptionUpdated))]
[JsonSerializable(typeof(ProjectAddedToEpic))]
[JsonSerializable(typeof(ProjectRemovedFromEpic))]
[JsonSerializable(typeof(EpicTargetDateChanged))]
[JsonSerializable(typeof(EpicPriorityChanged))]
[JsonSerializable(typeof(EpicCompleted))]
[JsonSerializable(typeof(EpicSnapshot))]
[JsonSerializable(typeof(Epic))]
[JsonSerializable(typeof(EpicId))]
[JsonSerializable(typeof(ErikLieben.FA.StronglyTypedIds.StronglyTypedId<String>))]
[JsonSerializable(typeof(System.Enum))]
[JsonSerializable(typeof(System.String))]
[JsonSerializable(typeof(TaskFlow.Domain.ValueObjects.EpicId))]
// <auto-generated />
/// <summary>
/// JSON serializer context for Epic types.
/// </summary>
internal partial class EpicJsonSerializerContext : JsonSerializerContext
{
}

//<auto-generated />
/// <summary>
/// Factory interface for creating Epic aggregate instances.
/// </summary>
public partial interface IEpicFactory : IAggregateFactory<Epic, EpicId>
{
}

//<auto-generated />
/// <summary>
/// Factory for creating and loading Epic aggregate instances from documents and event streams.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public partial class EpicFactory : IEpicFactory
{
    private readonly IEventStreamFactory eventStreamFactory;
    private readonly IObjectDocumentFactory objectDocumentFactory;
    private readonly IServiceProvider serviceProvider;

    /// <summary>
    /// Gets the object name used for document storage.
    /// </summary>
    public static string ObjectName => "epic";

    /// <summary>
    /// Gets the object name used for document storage.
    /// </summary>
    /// <returns>The object name.</returns>
    public string GetObjectName()
    {
        return ObjectName;
    }

    /// <summary>
    /// Initializes a new instance of the EpicFactory class.
    /// </summary>
    /// <param name="serviceProvider">Service provider for dependency injection.</param>
    /// <param name="eventStreamFactory">Factory for creating event streams.</param>
    /// <param name="objectDocumentFactory">Factory for creating and managing object documents.</param>
    public EpicFactory(
      IServiceProvider serviceProvider,
      IEventStreamFactory eventStreamFactory,
      IObjectDocumentFactory objectDocumentFactory)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        ArgumentNullException.ThrowIfNull(eventStreamFactory);
        ArgumentNullException.ThrowIfNull(objectDocumentFactory);

        this.serviceProvider = serviceProvider;
        this.eventStreamFactory = eventStreamFactory;
        this.objectDocumentFactory = objectDocumentFactory;
    }

    /// <summary>
    /// Creates a Epic instance from an event stream.
    /// </summary>
    /// <param name="eventStream">The event stream to create the aggregate from.</param>
    /// <returns>A new Epic instance.</returns>
    public Epic Create(IEventStream eventStream)
    {
        ArgumentNullException.ThrowIfNull(eventStream);

        // get the params required from DI

        return new Epic(eventStream);
    }

    /// <summary>
    /// Creates a Epic instance from an object document.
    /// </summary>
    /// <param name="document">The object document to create the aggregate from.</param>
    /// <returns>A new Epic instance.</returns>
    public Epic Create(IObjectDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        // get the params required from DI

        var eventStream = eventStreamFactory.Create(document);
        return new Epic(eventStream);
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    /// <summary>
    /// Creates a new Epic aggregate with the specified identifier.
    /// </summary>
    /// <param name="id">The identifier for the new aggregate.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A new Epic instance.</returns>
    public async Task<Epic> CreateAsync(EpicId id, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetOrCreateAsync(ObjectName, id.ToString(), null, "table");

        // Apply aggregate-specific settings for new documents
        if (document.Active.CurrentStreamVersion == -1)
        {
            document.Active.StreamType = "table";
            document.Active.DocumentType = "table";
            await this.objectDocumentFactory.SetAsync(document);
        }
        var obj = Create(document);
        await obj.Fold();
        return obj;
    }

    /// <summary>
    /// Creates a new Epic aggregate with the specified identifier and first event.
    /// </summary>
    /// <typeparam name="T">The type of the first event.</typeparam>
    /// <param name="id">The identifier for the new aggregate.</param>
    /// <param name="firstEvent">The first event to append to the aggregate's event stream.</param>
    /// <param name="metadata">Optional metadata to attach to the event.</param>
    /// <returns>A new Epic instance with the event applied.</returns>
    protected async Task<Epic> CreateAsync<T>(EpicId id, T firstEvent, ActionMetadata? metadata = null) where T : class
    {
        var document = await this.objectDocumentFactory.GetOrCreateAsync(ObjectName, id.ToString(), null, "table");

        // Apply aggregate-specific settings for new documents
        if (document.Active.CurrentStreamVersion == -1)
        {
            document.Active.StreamType = "table";
            document.Active.DocumentType = "table";
            await this.objectDocumentFactory.SetAsync(document);
        }
        var eventStream = eventStreamFactory.Create(document);
        var obj = new Epic(eventStream);
        await eventStream.Session(context => context.Append(firstEvent, metadata));
        await obj.Fold();
        return obj;
    }

    /// <summary>
    /// Gets an existing Epic aggregate by identifier.
    /// </summary>
    /// <param name="id">The identifier of the aggregate to retrieve.</param>
    /// <param name="upToVersion">Optional maximum event version to fold. If null, loads to current state.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The loaded Epic instance.</returns>
    [Obsolete("Use IEpicRepository.GetByIdAsync instead. This method will be removed in a future version.")]
    public async Task<Epic> GetAsync(EpicId id, int? upToVersion = null, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetAsync(ObjectName, id.ToString(), null, "table");

        // Create event stream
        var eventStream = eventStreamFactory.Create(document);

        // Create aggregate FIRST to register upcasters and event handlers
        var obj = new Epic(eventStream);

        // Read events up to version WITH upcasting applied
        var events = await eventStream.ReadAsync(0, upToVersion);

        // Fold events into the aggregate
        foreach (var e in events)
        {
            obj.Fold(e);
        }

        return obj;
    }

    /// <summary>
    /// Gets an existing Epic aggregate by identifier along with its document.
    /// </summary>
    /// <param name="id">The identifier of the aggregate to retrieve.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A tuple containing the loaded Epic instance and its document.</returns>
    [Obsolete("Use IEpicRepository.GetByIdWithDocumentAsync instead. This method will be removed in a future version.")]
    public async Task<(Epic, IObjectDocument)> GetWithDocumentAsync(EpicId id, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetAsync(ObjectName, id.ToString(), null, "table");
        var obj = Create(document);
        await obj.Fold();
        return (obj, document);
    }

    /// <summary>
    /// Gets the first Epic aggregate with the specified document tag.
    /// </summary>
    /// <param name="tag">The document tag to search for.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The first matching Epic instance, or null if not found.</returns>
    [Obsolete("Use IEpicRepository.GetFirstByDocumentTagAsync instead. This method will be removed in a future version.")]
    public async Task<Epic?> GetFirstByDocumentTag(string tag, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetFirstByObjectDocumentTag(ObjectName, tag);
        if (document == null)
        {
            return null;
        }
        var obj = Create(document);
        await obj.Fold();
        return obj;
    }

    /// <summary>
    /// Gets all Epic aggregates with the specified document tag.
    /// </summary>
    /// <param name="tag">The document tag to search for.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A collection of all matching Epic instances.</returns>
    [Obsolete("Use IEpicRepository.GetAllByDocumentTagAsync instead. This method will be removed in a future version.")]
    public async Task<IEnumerable<Epic>> GetAllByDocumentTag(string tag, CancellationToken cancellationToken = default)
    {
        var documents = (await this.objectDocumentFactory.GetByObjectDocumentTag(ObjectName, tag));
        var items = new List<Epic>();
        foreach (var document in documents)
        {
            var obj = Create(document);
            await obj.Fold();
            items.Add(obj);
        }
        return items;
    }
}

//<auto-generated />
public partial interface IEpicRepository
{
    /// <summary>
    /// Gets a paginated list of all Epic object IDs using continuation tokens.
    /// </summary>
    Task<PagedResult<string>> GetObjectIdsAsync(
        string? continuationToken = null,
        int pageSize = 100,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a single aggregate by ID.
    /// </summary>
    /// <param name="upToVersion">Optional: The maximum event version to fold. If null, loads to current state.</param>
    Task<Epic?> GetByIdAsync(
        EpicId id,
        int? upToVersion = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a single aggregate by ID along with its document.
    /// </summary>
    Task<(Epic?, IObjectDocument?)> GetByIdWithDocumentAsync(
        EpicId id,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the first aggregate with the specified document tag.
    /// </summary>
    Task<Epic?> GetFirstByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all aggregates with the specified document tag.
    /// </summary>
    Task<IEnumerable<Epic>> GetAllByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Checks if an aggregate with the given ID exists.
    /// </summary>
    Task<bool> ExistsAsync(
        EpicId id,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the total count of aggregates.
    /// Warning: This may be expensive for large datasets.
    /// </summary>
    Task<long> CountAsync(CancellationToken cancellationToken = default);
}

//<auto-generated />
/// <summary>
/// Repository for querying and managing Epic aggregates.
/// </summary>
public partial class EpicRepository : IEpicRepository
{
    private readonly IEpicFactory epicFactory;
    private readonly IObjectDocumentFactory objectDocumentFactory;
    private readonly IObjectIdProvider objectIdProvider;

    /// <summary>
    /// Gets the object name used for document storage.
    /// </summary>
    public static string ObjectName => "epic";

    /// <summary>
    /// Initializes a new instance of the EpicRepository class.
    /// </summary>
    /// <param name="epicFactory">Factory for creating Epic instances.</param>
    /// <param name="objectDocumentFactory">Factory for managing object documents.</param>
    /// <param name="objectIdProvider">Provider for querying object identifiers.</param>
    public EpicRepository(
        IEpicFactory epicFactory,
        IObjectDocumentFactory objectDocumentFactory,
        IObjectIdProvider objectIdProvider)
    {
        ArgumentNullException.ThrowIfNull(epicFactory);
        ArgumentNullException.ThrowIfNull(objectDocumentFactory);
        ArgumentNullException.ThrowIfNull(objectIdProvider);

        this.epicFactory = epicFactory;
        this.objectDocumentFactory = objectDocumentFactory;
        this.objectIdProvider = objectIdProvider;
    }

    public async Task<PagedResult<string>> GetObjectIdsAsync(
        string? continuationToken = null,
        int pageSize = 100,
        CancellationToken cancellationToken = default)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(pageSize, 1);
        ArgumentOutOfRangeException.ThrowIfGreaterThan(pageSize, 1000);

        return await objectIdProvider.GetObjectIdsAsync(
            ObjectName,
            continuationToken,
            pageSize,
            cancellationToken);
    }

    public async Task<Epic?> GetByIdAsync(
        EpicId id,
        int? upToVersion = null,
        CancellationToken cancellationToken = default)
    {
        try
        {
            return await epicFactory.GetAsync(id, upToVersion);
        }
        catch (Exception)
        {
            return null;
        }
    }

    public async Task<(Epic?, IObjectDocument?)> GetByIdWithDocumentAsync(
        EpicId id,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var document = await objectDocumentFactory.GetAsync(ObjectName, id.ToString(), null, "table");
            var obj = epicFactory.Create(document);
            await obj.Fold();
            return (obj, document);
        }
        catch (Exception)
        {
            return (null, null);
        }
    }

    public async Task<Epic?> GetFirstByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tag);

        var document = await objectDocumentFactory.GetFirstByObjectDocumentTag(ObjectName, tag);
        if (document == null)
        {
            return null;
        }

        var obj = epicFactory.Create(document);
        await obj.Fold();
        return obj;
    }

    public async Task<IEnumerable<Epic>> GetAllByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tag);

        var documents = await objectDocumentFactory.GetByObjectDocumentTag(ObjectName, tag);
        var items = new List<Epic>();

        foreach (var document in documents)
        {
            var obj = epicFactory.Create(document);
            await obj.Fold();
            items.Add(obj);
        }

        return items;
    }

    public async Task<bool> ExistsAsync(
        EpicId id,
        CancellationToken cancellationToken = default)
    {
        return await objectIdProvider.ExistsAsync(
            ObjectName,
            id.ToString(),
            cancellationToken);
    }

    public async Task<long> CountAsync(CancellationToken cancellationToken = default)
    {
        return await objectIdProvider.CountAsync(ObjectName, cancellationToken);
    }
}
