using ErikLieben.FA.ES;
using ErikLieben.FA.ES.Aggregates;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Processors;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.Epic;
using TaskFlow.Domain.ValueObjects;

#nullable enable

namespace TaskFlow.Domain.Aggregates;

// <auto-generated />
/// <summary>
/// Epic aggregate root implementing event sourcing patterns.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public partial class Epic : Aggregate, IBase, IEpic
{

    /// <summary>
    /// Gets the logical object name for this aggregate type (AOT-friendly static member).
    /// </summary>
    public static string ObjectName => "epic";

    /// <summary>
    /// Creates a new instance of the aggregate from an event stream (AOT-friendly factory).
    /// </summary>
    /// <param name="stream">The event stream for the aggregate.</param>
    /// <returns>A new instance of the aggregate.</returns>
    public static Epic Create(IEventStream stream) => new Epic(stream);

    /// <summary>
    /// Applies an event to the aggregate state by dispatching to the appropriate When method.
    /// </summary>
    /// <param name="event">The event to apply to the aggregate.</param>
    public override void Fold(IEvent @event)
    {
        switch (@event.EventType)
        {
            case "Epic.Created":
                When(JsonEvent.To(@event, EpicCreatedJsonSerializerContext.Default.EpicCreated));
                break;
            case "Epic.Renamed":
                When(JsonEvent.To(@event, EpicRenamedJsonSerializerContext.Default.EpicRenamed));
                break;
            case "Epic.DescriptionUpdated":
                When(JsonEvent.To(@event, EpicDescriptionUpdatedJsonSerializerContext.Default.EpicDescriptionUpdated));
                break;
            case "Epic.ProjectAdded":
                When(JsonEvent.To(@event, ProjectAddedToEpicJsonSerializerContext.Default.ProjectAddedToEpic));
                break;
            case "Epic.ProjectRemoved":
                When(JsonEvent.To(@event, ProjectRemovedFromEpicJsonSerializerContext.Default.ProjectRemovedFromEpic));
                break;
            case "Epic.TargetDateChanged":
                When(JsonEvent.To(@event, EpicTargetDateChangedJsonSerializerContext.Default.EpicTargetDateChanged));
                break;
            case "Epic.PriorityChanged":
                When(JsonEvent.To(@event, EpicPriorityChangedJsonSerializerContext.Default.EpicPriorityChanged));
                break;
            case "Epic.Completed":
                WhenEpicCompleted();
                break;
        }

        PostWhen(Stream.Document, @event);
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    protected override void GeneratedSetup()
    {
        Stream.RegisterEvent<EpicCreated>(
      "Epic.Created",
      EpicCreatedJsonSerializerContext.Default.EpicCreated);
        Stream.RegisterEvent<EpicRenamed>(
            "Epic.Renamed",
            EpicRenamedJsonSerializerContext.Default.EpicRenamed);
        Stream.RegisterEvent<EpicDescriptionUpdated>(
            "Epic.DescriptionUpdated",
            EpicDescriptionUpdatedJsonSerializerContext.Default.EpicDescriptionUpdated);
        Stream.RegisterEvent<ProjectAddedToEpic>(
            "Epic.ProjectAdded",
            ProjectAddedToEpicJsonSerializerContext.Default.ProjectAddedToEpic);
        Stream.RegisterEvent<ProjectRemovedFromEpic>(
            "Epic.ProjectRemoved",
            ProjectRemovedFromEpicJsonSerializerContext.Default.ProjectRemovedFromEpic);
        Stream.RegisterEvent<EpicTargetDateChanged>(
            "Epic.TargetDateChanged",
            EpicTargetDateChangedJsonSerializerContext.Default.EpicTargetDateChanged);
        Stream.RegisterEvent<EpicPriorityChanged>(
            "Epic.PriorityChanged",
            EpicPriorityChangedJsonSerializerContext.Default.EpicPriorityChanged);
        Stream.RegisterEvent<EpicCompleted>(
            "Epic.Completed",
            EpicCompletedJsonSerializerContext.Default.EpicCompleted);
        Stream.SetSnapShotType(EpicJsonSerializerContext.Default.EpicSnapshot);
        Stream.SetAggregateType(EpicJsonSerializerContext.Default.Epic);

        // Freeze the EventTypeRegistry for optimized lookups (~50% faster)
        Stream.EventTypeRegistry.Freeze();
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    public override void ProcessSnapshot(object snapshot)
    {
        throw new NotImplementedException();
    }
}

// <auto-generated />
/// <summary>
/// Interface defining the public state properties of Epic.
/// </summary>
public partial interface IEpic
{
    public String? Name { get; }
    public String? Description { get; }
    public UserProfileId? OwnerId { get; }
    public Nullable<System.DateTime> TargetCompletionDate { get; }
    public DateTime CreatedAt { get; }
    public Boolean IsCompleted { get; }
    public EpicPriority Priority { get; }
    public List<TaskFlow.Domain.ValueObjects.ProjectId>? Projects { get; }
    public ObjectMetadata<TaskFlow.Domain.ValueObjects.EpicId>? Metadata { get; }
}

// <auto-generated />
/// <summary>
/// Snapshot record for persisting Epic aggregate state.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public record EpicSnapshot : IEpic
{
    public required String? Name { get; init; }
    public required String? Description { get; init; }
    public required UserProfileId? OwnerId { get; init; }
    public required Nullable<System.DateTime> TargetCompletionDate { get; init; }
    public required DateTime CreatedAt { get; init; }
    public required Boolean IsCompleted { get; init; }
    public required EpicPriority Priority { get; init; }
    public required List<TaskFlow.Domain.ValueObjects.ProjectId>? Projects { get; init; }
    public required ObjectMetadata<TaskFlow.Domain.ValueObjects.EpicId>? Metadata { get; init; }
}

[JsonSerializable(typeof(EpicCreated))]
[JsonSerializable(typeof(EpicRenamed))]
[JsonSerializable(typeof(EpicDescriptionUpdated))]
[JsonSerializable(typeof(ProjectAddedToEpic))]
[JsonSerializable(typeof(ProjectRemovedFromEpic))]
[JsonSerializable(typeof(EpicTargetDateChanged))]
[JsonSerializable(typeof(EpicPriorityChanged))]
[JsonSerializable(typeof(EpicCompleted))]
[JsonSerializable(typeof(EpicSnapshot))]
[JsonSerializable(typeof(Epic))]
[JsonSerializable(typeof(EpicId))]
[JsonSerializable(typeof(ErikLieben.FA.StronglyTypedIds.StronglyTypedId<String>))]
[JsonSerializable(typeof(System.Enum))]
[JsonSerializable(typeof(System.String))]
[JsonSerializable(typeof(TaskFlow.Domain.ValueObjects.EpicId))]
// <auto-generated />
/// <summary>
/// JSON serializer context for Epic types.
/// </summary>
internal partial class EpicJsonSerializerContext : JsonSerializerContext
{
}

//<auto-generated />
/// <summary>
/// Factory interface for creating Epic aggregate instances.
/// </summary>
public partial interface IEpicFactory : IAggregateFactory<Epic, EpicId>
{
}
