using ErikLieben.FA.ES;
using ErikLieben.FA.ES.Aggregates;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Processors;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.Note;
using TaskFlow.Domain.ValueObjects;

#nullable enable

namespace TaskFlow.Domain.Aggregates;

// <auto-generated />
/// <summary>
/// Note aggregate root implementing event sourcing patterns.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public partial class Note : Aggregate, IBase, INote
{

    /// <summary>
    /// Gets the logical object name for this aggregate type (AOT-friendly static member).
    /// </summary>
    public static string ObjectName => "note";

    /// <summary>
    /// Creates a new instance of the aggregate from an event stream (AOT-friendly factory).
    /// </summary>
    /// <param name="stream">The event stream for the aggregate.</param>
    /// <returns>A new instance of the aggregate.</returns>
    public static Note Create(IEventStream stream) => new Note(stream);

    /// <summary>
    /// Applies an event to the aggregate state by dispatching to the appropriate When method.
    /// </summary>
    /// <param name="event">The event to apply to the aggregate.</param>
    public override void Fold(IEvent @event)
    {
        switch (@event.EventType)
        {
            case "Note.Created":
                When(JsonEvent.To(@event, NoteCreatedJsonSerializerContext.Default.NoteCreated));
                break;
            case "Note.Edited":
                When(JsonEvent.To(@event, NoteEditedJsonSerializerContext.Default.NoteEdited));
                break;
        }

        PostWhen(Stream.Document, @event);
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    protected override void GeneratedSetup()
    {
        Stream.RegisterEvent<NoteCreated>(
      "Note.Created",
      NoteCreatedJsonSerializerContext.Default.NoteCreated);
        Stream.RegisterEvent<NoteEdited>(
            "Note.Edited",
            NoteEditedJsonSerializerContext.Default.NoteEdited);
        Stream.SetSnapShotType(NoteJsonSerializerContext.Default.NoteSnapshot);
        Stream.SetAggregateType(NoteJsonSerializerContext.Default.Note);

        // Freeze the EventTypeRegistry for optimized lookups (~50% faster)
        Stream.EventTypeRegistry.Freeze();
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    public override void ProcessSnapshot(object snapshot)
    {
        throw new NotImplementedException();
    }
}

// <auto-generated />
/// <summary>
/// Interface defining the public state properties of Note.
/// </summary>
public partial interface INote
{
    public String? Title { get; }
    public String? Body { get; }
    public DateTime CreatedAt { get; }
    public Nullable<System.DateTime> EditedAt { get; }
    public ObjectMetadata<TaskFlow.Domain.ValueObjects.NoteId>? Metadata { get; }
}

// <auto-generated />
/// <summary>
/// Snapshot record for persisting Note aggregate state.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public record NoteSnapshot : INote
{
    public required String? Title { get; init; }
    public required String? Body { get; init; }
    public required DateTime CreatedAt { get; init; }
    public required Nullable<System.DateTime> EditedAt { get; init; }
    public required ObjectMetadata<TaskFlow.Domain.ValueObjects.NoteId>? Metadata { get; init; }
}

[JsonSerializable(typeof(NoteCreated))]
[JsonSerializable(typeof(NoteEdited))]
[JsonSerializable(typeof(NoteSnapshot))]
[JsonSerializable(typeof(Note))]
[JsonSerializable(typeof(NoteId))]
[JsonSerializable(typeof(System.String))]
[JsonSerializable(typeof(TaskFlow.Domain.ValueObjects.NoteId))]
// <auto-generated />
/// <summary>
/// JSON serializer context for Note types.
/// </summary>
internal partial class NoteJsonSerializerContext : JsonSerializerContext
{
}

//<auto-generated />
/// <summary>
/// Factory interface for creating Note aggregate instances.
/// </summary>
public partial interface INoteFactory : IAggregateFactory<Note, NoteId>
{
}
