using ErikLieben.FA.ES;
using ErikLieben.FA.ES.Aggregates;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Processors;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.Release;
using TaskFlow.Domain.ValueObjects;
using TaskFlow.Domain.ValueObjects.Release;

#nullable enable

namespace TaskFlow.Domain.Aggregates;

// <auto-generated />
/// <summary>
/// Release aggregate root implementing event sourcing patterns.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public partial class Release : Aggregate, IBase, IRelease
{

    /// <summary>
    /// Gets the logical object name for this aggregate type (AOT-friendly static member).
    /// </summary>
    public static string ObjectName => "release";

    /// <summary>
    /// Creates a new instance of the aggregate from an event stream (AOT-friendly factory).
    /// </summary>
    /// <param name="stream">The event stream for the aggregate.</param>
    /// <returns>A new instance of the aggregate.</returns>
    public static Release Create(IEventStream stream) => new Release(stream);

    /// <summary>
    /// Applies an event to the aggregate state by dispatching to the appropriate When method.
    /// </summary>
    /// <param name="event">The event to apply to the aggregate.</param>
    public override void Fold(IEvent @event)
    {
        switch (@event.EventType)
        {
            case "Release.Created":
                When(JsonEvent.To(@event, ReleaseCreatedJsonSerializerContext.Default.ReleaseCreated));
                break;
            case "Release.NoteAdded":
                When(JsonEvent.To(@event, ReleaseNoteAddedJsonSerializerContext.Default.ReleaseNoteAdded));
                break;
            case "Release.Deployed":
                When(JsonEvent.To(@event, ReleaseDeployedJsonSerializerContext.Default.ReleaseDeployed));
                break;
            case "Release.Completed":
                When(JsonEvent.To(@event, ReleaseCompletedJsonSerializerContext.Default.ReleaseCompleted));
                break;
            case "Release.Staged":
                WhenReleaseStaged();
                break;
            case "Release.RolledBack":
                WhenReleaseRolledBack();
                break;
        }

        PostWhen(Stream.Document, @event);
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    protected override void GeneratedSetup()
    {
        Stream.RegisterEvent<ReleaseCreated>(
      "Release.Created",
      ReleaseCreatedJsonSerializerContext.Default.ReleaseCreated);
        Stream.RegisterEvent<ReleaseNoteAdded>(
            "Release.NoteAdded",
            ReleaseNoteAddedJsonSerializerContext.Default.ReleaseNoteAdded);
        Stream.RegisterEvent<ReleaseDeployed>(
            "Release.Deployed",
            ReleaseDeployedJsonSerializerContext.Default.ReleaseDeployed);
        Stream.RegisterEvent<ReleaseCompleted>(
            "Release.Completed",
            ReleaseCompletedJsonSerializerContext.Default.ReleaseCompleted);
        Stream.RegisterEvent<ReleaseStaged>(
            "Release.Staged",
            ReleaseStagedJsonSerializerContext.Default.ReleaseStaged);
        Stream.RegisterEvent<ReleaseRolledBack>(
            "Release.RolledBack",
            ReleaseRolledBackJsonSerializerContext.Default.ReleaseRolledBack);
        Stream.SetSnapShotType(ReleaseJsonSerializerContext.Default.ReleaseSnapshot);
        Stream.SetAggregateType(ReleaseJsonSerializerContext.Default.Release);

        // Freeze the EventTypeRegistry for optimized lookups (~50% faster)
        Stream.EventTypeRegistry.Freeze();
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    public override void ProcessSnapshot(object snapshot)
    {
        throw new NotImplementedException();
    }
}

// <auto-generated />
/// <summary>
/// Interface defining the public state properties of Release.
/// </summary>
public interface IRelease
{
    public String? Name { get; }
    public String? Version { get; }
    public ProjectId? ProjectId { get; }
    public ReleaseStatus Status { get; }
    public List<System.String>? Notes { get; }
    public Nullable<System.DateTime> DeployedAt { get; }
    public Nullable<System.DateTime> CompletedAt { get; }
    public DateTime CreatedAt { get; }
    public UserProfileId? CreatedBy { get; }
    public ObjectMetadata<TaskFlow.Domain.ValueObjects.ReleaseId>? Metadata { get; }
}

// <auto-generated />
/// <summary>
/// Snapshot record for persisting Release aggregate state.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public record ReleaseSnapshot : IRelease
{
    public required String? Name { get; init; }
    public required String? Version { get; init; }
    public required ProjectId? ProjectId { get; init; }
    public required ReleaseStatus Status { get; init; }
    public required List<System.String>? Notes { get; init; }
    public required Nullable<System.DateTime> DeployedAt { get; init; }
    public required Nullable<System.DateTime> CompletedAt { get; init; }
    public required DateTime CreatedAt { get; init; }
    public required UserProfileId? CreatedBy { get; init; }
    public required ObjectMetadata<TaskFlow.Domain.ValueObjects.ReleaseId>? Metadata { get; init; }
}

[JsonSerializable(typeof(ReleaseCreated))]
[JsonSerializable(typeof(ReleaseNoteAdded))]
[JsonSerializable(typeof(ReleaseDeployed))]
[JsonSerializable(typeof(ReleaseCompleted))]
[JsonSerializable(typeof(ReleaseStaged))]
[JsonSerializable(typeof(ReleaseRolledBack))]
[JsonSerializable(typeof(ReleaseSnapshot))]
[JsonSerializable(typeof(Release))]
[JsonSerializable(typeof(ReleaseId))]
[JsonSerializable(typeof(ErikLieben.FA.StronglyTypedIds.StronglyTypedId<Guid>))]
[JsonSerializable(typeof(ErikLieben.FA.StronglyTypedIds.StronglyTypedId<String>))]
[JsonSerializable(typeof(System.Enum))]
[JsonSerializable(typeof(System.Guid))]
[JsonSerializable(typeof(System.String))]
[JsonSerializable(typeof(TaskFlow.Domain.ValueObjects.ReleaseId))]
// <auto-generated />
/// <summary>
/// JSON serializer context for Release types.
/// </summary>
internal partial class ReleaseJsonSerializerContext : JsonSerializerContext
{
}

//<auto-generated />
/// <summary>
/// Factory interface for creating Release aggregate instances.
/// </summary>
public partial interface IReleaseFactory : IAggregateFactory<Release, ReleaseId>
{
}

//<auto-generated />
/// <summary>
/// Factory for creating and loading Release aggregate instances from documents and event streams.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public partial class ReleaseFactory : IReleaseFactory
{
    private readonly IEventStreamFactory eventStreamFactory;
    private readonly IObjectDocumentFactory objectDocumentFactory;
    private readonly IServiceProvider serviceProvider;

    /// <summary>
    /// Gets the object name used for document storage.
    /// </summary>
    public static string ObjectName => "release";

    /// <summary>
    /// Gets the object name used for document storage.
    /// </summary>
    /// <returns>The object name.</returns>
    public string GetObjectName()
    {
        return ObjectName;
    }

    /// <summary>
    /// Initializes a new instance of the ReleaseFactory class.
    /// </summary>
    /// <param name="serviceProvider">Service provider for dependency injection.</param>
    /// <param name="eventStreamFactory">Factory for creating event streams.</param>
    /// <param name="objectDocumentFactory">Factory for creating and managing object documents.</param>
    public ReleaseFactory(
      IServiceProvider serviceProvider,
      IEventStreamFactory eventStreamFactory,
      IObjectDocumentFactory objectDocumentFactory)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        ArgumentNullException.ThrowIfNull(eventStreamFactory);
        ArgumentNullException.ThrowIfNull(objectDocumentFactory);

        this.serviceProvider = serviceProvider;
        this.eventStreamFactory = eventStreamFactory;
        this.objectDocumentFactory = objectDocumentFactory;
    }

    /// <summary>
    /// Creates a Release instance from an event stream.
    /// </summary>
    /// <param name="eventStream">The event stream to create the aggregate from.</param>
    /// <returns>A new Release instance.</returns>
    public Release Create(IEventStream eventStream)
    {
        ArgumentNullException.ThrowIfNull(eventStream);

        // get the params required from DI

        return new Release(eventStream);
    }

    /// <summary>
    /// Creates a Release instance from an object document.
    /// </summary>
    /// <param name="document">The object document to create the aggregate from.</param>
    /// <returns>A new Release instance.</returns>
    public Release Create(IObjectDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        // get the params required from DI

        var eventStream = eventStreamFactory.Create(document);
        return new Release(eventStream);
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    /// <summary>
    /// Creates a new Release aggregate with the specified identifier.
    /// </summary>
    /// <param name="id">The identifier for the new aggregate.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A new Release instance.</returns>
    public async Task<Release> CreateAsync(ReleaseId id, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetOrCreateAsync(ObjectName, id.ToString(), null, "s3");

        // Apply aggregate-specific settings for new documents
        if (document.Active.CurrentStreamVersion == -1)
        {
            document.Active.StreamType = "s3";
            document.Active.DocumentType = "s3";
            await this.objectDocumentFactory.SetAsync(document);
        }
        var obj = Create(document);
        await obj.Fold();
        return obj;
    }

    /// <summary>
    /// Creates a new Release aggregate with the specified identifier and first event.
    /// </summary>
    /// <typeparam name="T">The type of the first event.</typeparam>
    /// <param name="id">The identifier for the new aggregate.</param>
    /// <param name="firstEvent">The first event to append to the aggregate's event stream.</param>
    /// <param name="metadata">Optional metadata to attach to the event.</param>
    /// <returns>A new Release instance with the event applied.</returns>
    protected async Task<Release> CreateAsync<T>(ReleaseId id, T firstEvent, ActionMetadata? metadata = null) where T : class
    {
        var document = await this.objectDocumentFactory.GetOrCreateAsync(ObjectName, id.ToString(), null, "s3");

        // Apply aggregate-specific settings for new documents
        if (document.Active.CurrentStreamVersion == -1)
        {
            document.Active.StreamType = "s3";
            document.Active.DocumentType = "s3";
            await this.objectDocumentFactory.SetAsync(document);
        }
        var eventStream = eventStreamFactory.Create(document);
        var obj = new Release(eventStream);
        await eventStream.Session(context => context.Append(firstEvent, metadata));
        await obj.Fold();
        return obj;
    }

    /// <summary>
    /// Gets an existing Release aggregate by identifier.
    /// </summary>
    /// <param name="id">The identifier of the aggregate to retrieve.</param>
    /// <param name="upToVersion">Optional maximum event version to fold. If null, loads to current state.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The loaded Release instance.</returns>
    [Obsolete("Use IReleaseRepository.GetByIdAsync instead. This method will be removed in a future version.")]
    public async Task<Release> GetAsync(ReleaseId id, int? upToVersion = null, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetAsync(ObjectName, id.ToString(), null, "s3");

        // Create event stream
        var eventStream = eventStreamFactory.Create(document);

        // Create aggregate FIRST to register upcasters and event handlers
        var obj = new Release(eventStream);

        // Read events up to version WITH upcasting applied
        var events = await eventStream.ReadAsync(0, upToVersion);

        // Fold events into the aggregate
        foreach (var e in events)
        {
            obj.Fold(e);
        }

        return obj;
    }

    /// <summary>
    /// Gets an existing Release aggregate by identifier along with its document.
    /// </summary>
    /// <param name="id">The identifier of the aggregate to retrieve.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A tuple containing the loaded Release instance and its document.</returns>
    [Obsolete("Use IReleaseRepository.GetByIdWithDocumentAsync instead. This method will be removed in a future version.")]
    public async Task<(Release, IObjectDocument)> GetWithDocumentAsync(ReleaseId id, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetAsync(ObjectName, id.ToString(), null, "s3");
        var obj = Create(document);
        await obj.Fold();
        return (obj, document);
    }

    /// <summary>
    /// Gets the first Release aggregate with the specified document tag.
    /// </summary>
    /// <param name="tag">The document tag to search for.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The first matching Release instance, or null if not found.</returns>
    [Obsolete("Use IReleaseRepository.GetFirstByDocumentTagAsync instead. This method will be removed in a future version.")]
    public async Task<Release?> GetFirstByDocumentTag(string tag, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetFirstByObjectDocumentTag(ObjectName, tag);
        if (document == null)
        {
            return null;
        }
        var obj = Create(document);
        await obj.Fold();
        return obj;
    }

    /// <summary>
    /// Gets all Release aggregates with the specified document tag.
    /// </summary>
    /// <param name="tag">The document tag to search for.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A collection of all matching Release instances.</returns>
    [Obsolete("Use IReleaseRepository.GetAllByDocumentTagAsync instead. This method will be removed in a future version.")]
    public async Task<IEnumerable<Release>> GetAllByDocumentTag(string tag, CancellationToken cancellationToken = default)
    {
        var documents = (await this.objectDocumentFactory.GetByObjectDocumentTag(ObjectName, tag));
        var items = new List<Release>();
        foreach (var document in documents)
        {
            var obj = Create(document);
            await obj.Fold();
            items.Add(obj);
        }
        return items;
    }
}

//<auto-generated />
public partial interface IReleaseRepository
{
    /// <summary>
    /// Gets a paginated list of all Release object IDs using continuation tokens.
    /// </summary>
    Task<PagedResult<string>> GetObjectIdsAsync(
        string? continuationToken = null,
        int pageSize = 100,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a single aggregate by ID.
    /// </summary>
    /// <param name="upToVersion">Optional: The maximum event version to fold. If null, loads to current state.</param>
    Task<Release?> GetByIdAsync(
        ReleaseId id,
        int? upToVersion = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a single aggregate by ID along with its document.
    /// </summary>
    Task<(Release?, IObjectDocument?)> GetByIdWithDocumentAsync(
        ReleaseId id,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the first aggregate with the specified document tag.
    /// </summary>
    Task<Release?> GetFirstByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all aggregates with the specified document tag.
    /// </summary>
    Task<IEnumerable<Release>> GetAllByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Checks if an aggregate with the given ID exists.
    /// </summary>
    Task<bool> ExistsAsync(
        ReleaseId id,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the total count of aggregates.
    /// Warning: This may be expensive for large datasets.
    /// </summary>
    Task<long> CountAsync(CancellationToken cancellationToken = default);
}

//<auto-generated />
/// <summary>
/// Repository for querying and managing Release aggregates.
/// </summary>
public partial class ReleaseRepository : IReleaseRepository
{
    private readonly IReleaseFactory releaseFactory;
    private readonly IObjectDocumentFactory objectDocumentFactory;
    private readonly IObjectIdProvider objectIdProvider;

    /// <summary>
    /// Gets the object name used for document storage.
    /// </summary>
    public static string ObjectName => "release";

    /// <summary>
    /// Initializes a new instance of the ReleaseRepository class.
    /// </summary>
    /// <param name="releaseFactory">Factory for creating Release instances.</param>
    /// <param name="objectDocumentFactory">Factory for managing object documents.</param>
    /// <param name="objectIdProvider">Provider for querying object identifiers.</param>
    public ReleaseRepository(
        IReleaseFactory releaseFactory,
        IObjectDocumentFactory objectDocumentFactory,
        IObjectIdProvider objectIdProvider)
    {
        ArgumentNullException.ThrowIfNull(releaseFactory);
        ArgumentNullException.ThrowIfNull(objectDocumentFactory);
        ArgumentNullException.ThrowIfNull(objectIdProvider);

        this.releaseFactory = releaseFactory;
        this.objectDocumentFactory = objectDocumentFactory;
        this.objectIdProvider = objectIdProvider;
    }

    public async Task<PagedResult<string>> GetObjectIdsAsync(
        string? continuationToken = null,
        int pageSize = 100,
        CancellationToken cancellationToken = default)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(pageSize, 1);
        ArgumentOutOfRangeException.ThrowIfGreaterThan(pageSize, 1000);

        return await objectIdProvider.GetObjectIdsAsync(
            ObjectName,
            continuationToken,
            pageSize,
            cancellationToken);
    }

    public async Task<Release?> GetByIdAsync(
        ReleaseId id,
        int? upToVersion = null,
        CancellationToken cancellationToken = default)
    {
        try
        {
            return await releaseFactory.GetAsync(id, upToVersion);
        }
        catch (Exception)
        {
            return null;
        }
    }

    public async Task<(Release?, IObjectDocument?)> GetByIdWithDocumentAsync(
        ReleaseId id,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var document = await objectDocumentFactory.GetAsync(ObjectName, id.ToString(), null, "s3");
            var obj = releaseFactory.Create(document);
            await obj.Fold();
            return (obj, document);
        }
        catch (Exception)
        {
            return (null, null);
        }
    }

    public async Task<Release?> GetFirstByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tag);

        var document = await objectDocumentFactory.GetFirstByObjectDocumentTag(ObjectName, tag);
        if (document == null)
        {
            return null;
        }

        var obj = releaseFactory.Create(document);
        await obj.Fold();
        return obj;
    }

    public async Task<IEnumerable<Release>> GetAllByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tag);

        var documents = await objectDocumentFactory.GetByObjectDocumentTag(ObjectName, tag);
        var items = new List<Release>();

        foreach (var document in documents)
        {
            var obj = releaseFactory.Create(document);
            await obj.Fold();
            items.Add(obj);
        }

        return items;
    }

    public async Task<bool> ExistsAsync(
        ReleaseId id,
        CancellationToken cancellationToken = default)
    {
        return await objectIdProvider.ExistsAsync(
            ObjectName,
            id.ToString(),
            cancellationToken);
    }

    public async Task<long> CountAsync(CancellationToken cancellationToken = default)
    {
        return await objectIdProvider.CountAsync(ObjectName, cancellationToken);
    }
}
