using ErikLieben.FA.ES;
using ErikLieben.FA.ES.Aggregates;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Processors;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.Sprint;
using TaskFlow.Domain.ValueObjects;
using TaskFlow.Domain.ValueObjects.Sprint;

#nullable enable

namespace TaskFlow.Domain.Aggregates;

// <auto-generated />
/// <summary>
/// Sprint aggregate root implementing event sourcing patterns.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public partial class Sprint : Aggregate, IBase, ISprint
{

    /// <summary>
    /// Gets the logical object name for this aggregate type (AOT-friendly static member).
    /// </summary>
    public static string ObjectName => "sprint";

    /// <summary>
    /// Creates a new instance of the aggregate from an event stream (AOT-friendly factory).
    /// </summary>
    /// <param name="stream">The event stream for the aggregate.</param>
    /// <returns>A new instance of the aggregate.</returns>
    public static Sprint Create(IEventStream stream) => new Sprint(stream);

    /// <summary>
    /// Applies an event to the aggregate state by dispatching to the appropriate When method.
    /// </summary>
    /// <param name="event">The event to apply to the aggregate.</param>
    public override void Fold(IEvent @event)
    {
        switch (@event.EventType)
        {
            case "Sprint.Created":
                When(JsonEvent.To(@event, SprintCreatedJsonSerializerContext.Default.SprintCreated));
                break;
            case "Sprint.WorkItemAdded":
                When(JsonEvent.To(@event, WorkItemAddedToSprintJsonSerializerContext.Default.WorkItemAddedToSprint));
                break;
            case "Sprint.WorkItemRemoved":
                When(JsonEvent.To(@event, WorkItemRemovedFromSprintJsonSerializerContext.Default.WorkItemRemovedFromSprint));
                break;
            case "Sprint.GoalUpdated":
                When(JsonEvent.To(@event, SprintGoalUpdatedJsonSerializerContext.Default.SprintGoalUpdated));
                break;
            case "Sprint.DatesChanged":
                When(JsonEvent.To(@event, SprintDatesChangedJsonSerializerContext.Default.SprintDatesChanged));
                break;
            case "Sprint.Started":
                WhenSprintStarted();
                break;
            case "Sprint.Completed":
                WhenSprintCompleted();
                break;
            case "Sprint.Cancelled":
                WhenSprintCancelled();
                break;
        }

        PostWhen(Stream.Document, @event);
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    protected override void GeneratedSetup()
    {
        Stream.RegisterEvent<SprintCreated>(
      "Sprint.Created",
      SprintCreatedJsonSerializerContext.Default.SprintCreated);
        Stream.RegisterEvent<WorkItemAddedToSprint>(
            "Sprint.WorkItemAdded",
            WorkItemAddedToSprintJsonSerializerContext.Default.WorkItemAddedToSprint);
        Stream.RegisterEvent<WorkItemRemovedFromSprint>(
            "Sprint.WorkItemRemoved",
            WorkItemRemovedFromSprintJsonSerializerContext.Default.WorkItemRemovedFromSprint);
        Stream.RegisterEvent<SprintGoalUpdated>(
            "Sprint.GoalUpdated",
            SprintGoalUpdatedJsonSerializerContext.Default.SprintGoalUpdated);
        Stream.RegisterEvent<SprintDatesChanged>(
            "Sprint.DatesChanged",
            SprintDatesChangedJsonSerializerContext.Default.SprintDatesChanged);
        Stream.RegisterEvent<SprintStarted>(
            "Sprint.Started",
            SprintStartedJsonSerializerContext.Default.SprintStarted);
        Stream.RegisterEvent<SprintCompleted>(
            "Sprint.Completed",
            SprintCompletedJsonSerializerContext.Default.SprintCompleted);
        Stream.RegisterEvent<SprintCancelled>(
            "Sprint.Cancelled",
            SprintCancelledJsonSerializerContext.Default.SprintCancelled);
        Stream.SetSnapShotType(SprintJsonSerializerContext.Default.SprintSnapshot);
        Stream.SetAggregateType(SprintJsonSerializerContext.Default.Sprint);

        // Freeze the EventTypeRegistry for optimized lookups (~50% faster)
        Stream.EventTypeRegistry.Freeze();
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    public override void ProcessSnapshot(object snapshot)
    {
        throw new NotImplementedException();
    }
}

// <auto-generated />
/// <summary>
/// Interface defining the public state properties of Sprint.
/// </summary>
public interface ISprint
{
    public String? Name { get; }
    public ProjectId? ProjectId { get; }
    public DateTime StartDate { get; }
    public DateTime EndDate { get; }
    public String? Goal { get; }
    public SprintStatus Status { get; }
    public DateTime CreatedAt { get; }
    public UserProfileId? CreatedBy { get; }
    public List<TaskFlow.Domain.ValueObjects.WorkItemId>? WorkItems { get; }
    public ObjectMetadata<TaskFlow.Domain.ValueObjects.SprintId>? Metadata { get; }
}

// <auto-generated />
/// <summary>
/// Snapshot record for persisting Sprint aggregate state.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public record SprintSnapshot : ISprint
{
    public required String? Name { get; init; }
    public required ProjectId? ProjectId { get; init; }
    public required DateTime StartDate { get; init; }
    public required DateTime EndDate { get; init; }
    public required String? Goal { get; init; }
    public required SprintStatus Status { get; init; }
    public required DateTime CreatedAt { get; init; }
    public required UserProfileId? CreatedBy { get; init; }
    public required List<TaskFlow.Domain.ValueObjects.WorkItemId>? WorkItems { get; init; }
    public required ObjectMetadata<TaskFlow.Domain.ValueObjects.SprintId>? Metadata { get; init; }
}

[JsonSerializable(typeof(SprintCreated))]
[JsonSerializable(typeof(WorkItemAddedToSprint))]
[JsonSerializable(typeof(WorkItemRemovedFromSprint))]
[JsonSerializable(typeof(SprintGoalUpdated))]
[JsonSerializable(typeof(SprintDatesChanged))]
[JsonSerializable(typeof(SprintStarted))]
[JsonSerializable(typeof(SprintCompleted))]
[JsonSerializable(typeof(SprintCancelled))]
[JsonSerializable(typeof(SprintSnapshot))]
[JsonSerializable(typeof(Sprint))]
[JsonSerializable(typeof(SprintId))]
[JsonSerializable(typeof(ErikLieben.FA.StronglyTypedIds.StronglyTypedId<Guid>))]
[JsonSerializable(typeof(ErikLieben.FA.StronglyTypedIds.StronglyTypedId<String>))]
[JsonSerializable(typeof(System.Enum))]
[JsonSerializable(typeof(System.Guid))]
[JsonSerializable(typeof(System.String))]
[JsonSerializable(typeof(TaskFlow.Domain.ValueObjects.SprintId))]
// <auto-generated />
/// <summary>
/// JSON serializer context for Sprint types.
/// </summary>
internal partial class SprintJsonSerializerContext : JsonSerializerContext
{
}

//<auto-generated />
/// <summary>
/// Factory interface for creating Sprint aggregate instances.
/// </summary>
public partial interface ISprintFactory : IAggregateFactory<Sprint, SprintId>
{
}

//<auto-generated />
/// <summary>
/// Factory for creating and loading Sprint aggregate instances from documents and event streams.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public partial class SprintFactory : ISprintFactory
{
    private readonly IEventStreamFactory eventStreamFactory;
    private readonly IObjectDocumentFactory objectDocumentFactory;
    private readonly IServiceProvider serviceProvider;

    /// <summary>
    /// Gets the object name used for document storage.
    /// </summary>
    public static string ObjectName => "sprint";

    /// <summary>
    /// Gets the object name used for document storage.
    /// </summary>
    /// <returns>The object name.</returns>
    public string GetObjectName()
    {
        return ObjectName;
    }

    /// <summary>
    /// Initializes a new instance of the SprintFactory class.
    /// </summary>
    /// <param name="serviceProvider">Service provider for dependency injection.</param>
    /// <param name="eventStreamFactory">Factory for creating event streams.</param>
    /// <param name="objectDocumentFactory">Factory for creating and managing object documents.</param>
    public SprintFactory(
      IServiceProvider serviceProvider,
      IEventStreamFactory eventStreamFactory,
      IObjectDocumentFactory objectDocumentFactory)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        ArgumentNullException.ThrowIfNull(eventStreamFactory);
        ArgumentNullException.ThrowIfNull(objectDocumentFactory);

        this.serviceProvider = serviceProvider;
        this.eventStreamFactory = eventStreamFactory;
        this.objectDocumentFactory = objectDocumentFactory;
    }

    /// <summary>
    /// Creates a Sprint instance from an event stream.
    /// </summary>
    /// <param name="eventStream">The event stream to create the aggregate from.</param>
    /// <returns>A new Sprint instance.</returns>
    public Sprint Create(IEventStream eventStream)
    {
        ArgumentNullException.ThrowIfNull(eventStream);

        // get the params required from DI

        return new Sprint(eventStream);
    }

    /// <summary>
    /// Creates a Sprint instance from an object document.
    /// </summary>
    /// <param name="document">The object document to create the aggregate from.</param>
    /// <returns>A new Sprint instance.</returns>
    public Sprint Create(IObjectDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        // get the params required from DI

        var eventStream = eventStreamFactory.Create(document);
        return new Sprint(eventStream);
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    /// <summary>
    /// Creates a new Sprint aggregate with the specified identifier.
    /// </summary>
    /// <param name="id">The identifier for the new aggregate.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A new Sprint instance.</returns>
    public async Task<Sprint> CreateAsync(SprintId id, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetOrCreateAsync(ObjectName, id.ToString(), null, "cosmosdb");

        // Apply aggregate-specific settings for new documents
        if (document.Active.CurrentStreamVersion == -1)
        {
            document.Active.StreamType = "cosmosdb";
            document.Active.DocumentType = "cosmosdb";
            await this.objectDocumentFactory.SetAsync(document);
        }
        var obj = Create(document);
        await obj.Fold();
        return obj;
    }

    /// <summary>
    /// Creates a new Sprint aggregate with the specified identifier and first event.
    /// </summary>
    /// <typeparam name="T">The type of the first event.</typeparam>
    /// <param name="id">The identifier for the new aggregate.</param>
    /// <param name="firstEvent">The first event to append to the aggregate's event stream.</param>
    /// <param name="metadata">Optional metadata to attach to the event.</param>
    /// <returns>A new Sprint instance with the event applied.</returns>
    protected async Task<Sprint> CreateAsync<T>(SprintId id, T firstEvent, ActionMetadata? metadata = null) where T : class
    {
        var document = await this.objectDocumentFactory.GetOrCreateAsync(ObjectName, id.ToString(), null, "cosmosdb");

        // Apply aggregate-specific settings for new documents
        if (document.Active.CurrentStreamVersion == -1)
        {
            document.Active.StreamType = "cosmosdb";
            document.Active.DocumentType = "cosmosdb";
            await this.objectDocumentFactory.SetAsync(document);
        }
        var eventStream = eventStreamFactory.Create(document);
        var obj = new Sprint(eventStream);
        await eventStream.Session(context => context.Append(firstEvent, metadata));
        await obj.Fold();
        return obj;
    }

    /// <summary>
    /// Gets an existing Sprint aggregate by identifier.
    /// </summary>
    /// <param name="id">The identifier of the aggregate to retrieve.</param>
    /// <param name="upToVersion">Optional maximum event version to fold. If null, loads to current state.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The loaded Sprint instance.</returns>
    [Obsolete("Use ISprintRepository.GetByIdAsync instead. This method will be removed in a future version.")]
    public async Task<Sprint> GetAsync(SprintId id, int? upToVersion = null, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetAsync(ObjectName, id.ToString(), null, "cosmosdb");

        // Create event stream
        var eventStream = eventStreamFactory.Create(document);

        // Create aggregate FIRST to register upcasters and event handlers
        var obj = new Sprint(eventStream);

        // Read events up to version WITH upcasting applied
        var events = await eventStream.ReadAsync(0, upToVersion);

        // Fold events into the aggregate
        foreach (var e in events)
        {
            obj.Fold(e);
        }

        return obj;
    }

    /// <summary>
    /// Gets an existing Sprint aggregate by identifier along with its document.
    /// </summary>
    /// <param name="id">The identifier of the aggregate to retrieve.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A tuple containing the loaded Sprint instance and its document.</returns>
    [Obsolete("Use ISprintRepository.GetByIdWithDocumentAsync instead. This method will be removed in a future version.")]
    public async Task<(Sprint, IObjectDocument)> GetWithDocumentAsync(SprintId id, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetAsync(ObjectName, id.ToString(), null, "cosmosdb");
        var obj = Create(document);
        await obj.Fold();
        return (obj, document);
    }

    /// <summary>
    /// Gets the first Sprint aggregate with the specified document tag.
    /// </summary>
    /// <param name="tag">The document tag to search for.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The first matching Sprint instance, or null if not found.</returns>
    [Obsolete("Use ISprintRepository.GetFirstByDocumentTagAsync instead. This method will be removed in a future version.")]
    public async Task<Sprint?> GetFirstByDocumentTag(string tag, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetFirstByObjectDocumentTag(ObjectName, tag);
        if (document == null)
        {
            return null;
        }
        var obj = Create(document);
        await obj.Fold();
        return obj;
    }

    /// <summary>
    /// Gets all Sprint aggregates with the specified document tag.
    /// </summary>
    /// <param name="tag">The document tag to search for.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A collection of all matching Sprint instances.</returns>
    [Obsolete("Use ISprintRepository.GetAllByDocumentTagAsync instead. This method will be removed in a future version.")]
    public async Task<IEnumerable<Sprint>> GetAllByDocumentTag(string tag, CancellationToken cancellationToken = default)
    {
        var documents = (await this.objectDocumentFactory.GetByObjectDocumentTag(ObjectName, tag));
        var items = new List<Sprint>();
        foreach (var document in documents)
        {
            var obj = Create(document);
            await obj.Fold();
            items.Add(obj);
        }
        return items;
    }
}

//<auto-generated />
public partial interface ISprintRepository
{
    /// <summary>
    /// Gets a paginated list of all Sprint object IDs using continuation tokens.
    /// </summary>
    Task<PagedResult<string>> GetObjectIdsAsync(
        string? continuationToken = null,
        int pageSize = 100,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a single aggregate by ID.
    /// </summary>
    /// <param name="upToVersion">Optional: The maximum event version to fold. If null, loads to current state.</param>
    Task<Sprint?> GetByIdAsync(
        SprintId id,
        int? upToVersion = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a single aggregate by ID along with its document.
    /// </summary>
    Task<(Sprint?, IObjectDocument?)> GetByIdWithDocumentAsync(
        SprintId id,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the first aggregate with the specified document tag.
    /// </summary>
    Task<Sprint?> GetFirstByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all aggregates with the specified document tag.
    /// </summary>
    Task<IEnumerable<Sprint>> GetAllByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Checks if an aggregate with the given ID exists.
    /// </summary>
    Task<bool> ExistsAsync(
        SprintId id,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the total count of aggregates.
    /// Warning: This may be expensive for large datasets.
    /// </summary>
    Task<long> CountAsync(CancellationToken cancellationToken = default);
}

//<auto-generated />
/// <summary>
/// Repository for querying and managing Sprint aggregates.
/// </summary>
public partial class SprintRepository : ISprintRepository
{
    private readonly ISprintFactory sprintFactory;
    private readonly IObjectDocumentFactory objectDocumentFactory;
    private readonly IObjectIdProvider objectIdProvider;

    /// <summary>
    /// Gets the object name used for document storage.
    /// </summary>
    public static string ObjectName => "sprint";

    /// <summary>
    /// Initializes a new instance of the SprintRepository class.
    /// </summary>
    /// <param name="sprintFactory">Factory for creating Sprint instances.</param>
    /// <param name="objectDocumentFactory">Factory for managing object documents.</param>
    /// <param name="objectIdProvider">Provider for querying object identifiers.</param>
    public SprintRepository(
        ISprintFactory sprintFactory,
        IObjectDocumentFactory objectDocumentFactory,
        IObjectIdProvider objectIdProvider)
    {
        ArgumentNullException.ThrowIfNull(sprintFactory);
        ArgumentNullException.ThrowIfNull(objectDocumentFactory);
        ArgumentNullException.ThrowIfNull(objectIdProvider);

        this.sprintFactory = sprintFactory;
        this.objectDocumentFactory = objectDocumentFactory;
        this.objectIdProvider = objectIdProvider;
    }

    public async Task<PagedResult<string>> GetObjectIdsAsync(
        string? continuationToken = null,
        int pageSize = 100,
        CancellationToken cancellationToken = default)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(pageSize, 1);
        ArgumentOutOfRangeException.ThrowIfGreaterThan(pageSize, 1000);

        return await objectIdProvider.GetObjectIdsAsync(
            ObjectName,
            continuationToken,
            pageSize,
            cancellationToken);
    }

    public async Task<Sprint?> GetByIdAsync(
        SprintId id,
        int? upToVersion = null,
        CancellationToken cancellationToken = default)
    {
        try
        {
            return await sprintFactory.GetAsync(id, upToVersion);
        }
        catch (Exception)
        {
            return null;
        }
    }

    public async Task<(Sprint?, IObjectDocument?)> GetByIdWithDocumentAsync(
        SprintId id,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var document = await objectDocumentFactory.GetAsync(ObjectName, id.ToString(), null, "cosmosdb");
            var obj = sprintFactory.Create(document);
            await obj.Fold();
            return (obj, document);
        }
        catch (Exception)
        {
            return (null, null);
        }
    }

    public async Task<Sprint?> GetFirstByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tag);

        var document = await objectDocumentFactory.GetFirstByObjectDocumentTag(ObjectName, tag);
        if (document == null)
        {
            return null;
        }

        var obj = sprintFactory.Create(document);
        await obj.Fold();
        return obj;
    }

    public async Task<IEnumerable<Sprint>> GetAllByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tag);

        var documents = await objectDocumentFactory.GetByObjectDocumentTag(ObjectName, tag);
        var items = new List<Sprint>();

        foreach (var document in documents)
        {
            var obj = sprintFactory.Create(document);
            await obj.Fold();
            items.Add(obj);
        }

        return items;
    }

    public async Task<bool> ExistsAsync(
        SprintId id,
        CancellationToken cancellationToken = default)
    {
        return await objectIdProvider.ExistsAsync(
            ObjectName,
            id.ToString(),
            cancellationToken);
    }

    public async Task<long> CountAsync(CancellationToken cancellationToken = default)
    {
        return await objectIdProvider.CountAsync(ObjectName, cancellationToken);
    }
}
