using ErikLieben.FA.ES;
using ErikLieben.FA.ES.Aggregates;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Processors;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.Sprint;
using TaskFlow.Domain.ValueObjects;
using TaskFlow.Domain.ValueObjects.Sprint;

#nullable enable

namespace TaskFlow.Domain.Aggregates;

//<auto-generated />
public partial interface ISprintRepository
{
    /// <summary>
    /// Gets a paginated list of all Sprint object IDs using continuation tokens.
    /// </summary>
    Task<PagedResult<string>> GetObjectIdsAsync(
        string? continuationToken = null,
        int pageSize = 100,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a single aggregate by ID.
    /// </summary>
    /// <param name="upToVersion">Optional: The maximum event version to fold. If null, loads to current state.</param>
    Task<Sprint?> GetByIdAsync(
        SprintId id,
        int? upToVersion = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a single aggregate by ID along with its document.
    /// </summary>
    Task<(Sprint?, IObjectDocument?)> GetByIdWithDocumentAsync(
        SprintId id,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the first aggregate with the specified document tag.
    /// </summary>
    Task<Sprint?> GetFirstByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all aggregates with the specified document tag.
    /// </summary>
    Task<IEnumerable<Sprint>> GetAllByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Checks if an aggregate with the given ID exists.
    /// </summary>
    Task<bool> ExistsAsync(
        SprintId id,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the total count of aggregates.
    /// Warning: This may be expensive for large datasets.
    /// </summary>
    Task<long> CountAsync(CancellationToken cancellationToken = default);
}

//<auto-generated />
/// <summary>
/// Repository for querying and managing Sprint aggregates.
/// </summary>
public partial class SprintRepository : ISprintRepository
{
    private readonly ISprintFactory sprintFactory;
    private readonly IObjectDocumentFactory objectDocumentFactory;
    private readonly IObjectIdProvider objectIdProvider;

    /// <summary>
    /// Gets the object name used for document storage.
    /// </summary>
    public static string ObjectName => "sprint";

    /// <summary>
    /// Initializes a new instance of the SprintRepository class.
    /// </summary>
    /// <param name="sprintFactory">Factory for creating Sprint instances.</param>
    /// <param name="objectDocumentFactory">Factory for managing object documents.</param>
    /// <param name="objectIdProvider">Provider for querying object identifiers.</param>
    public SprintRepository(
        ISprintFactory sprintFactory,
        IObjectDocumentFactory objectDocumentFactory,
        IObjectIdProvider objectIdProvider)
    {
        ArgumentNullException.ThrowIfNull(sprintFactory);
        ArgumentNullException.ThrowIfNull(objectDocumentFactory);
        ArgumentNullException.ThrowIfNull(objectIdProvider);

        this.sprintFactory = sprintFactory;
        this.objectDocumentFactory = objectDocumentFactory;
        this.objectIdProvider = objectIdProvider;
    }

    public async Task<PagedResult<string>> GetObjectIdsAsync(
        string? continuationToken = null,
        int pageSize = 100,
        CancellationToken cancellationToken = default)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(pageSize, 1);
        ArgumentOutOfRangeException.ThrowIfGreaterThan(pageSize, 1000);

        return await objectIdProvider.GetObjectIdsAsync(
            ObjectName,
            continuationToken,
            pageSize,
            cancellationToken);
    }

    public async Task<Sprint?> GetByIdAsync(
        SprintId id,
        int? upToVersion = null,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var document = await objectDocumentFactory.GetAsync(ObjectName, id.ToString(), null, "cosmosdb");
            var obj = sprintFactory.Create(document);

            if (upToVersion.HasValue)
            {
                var events = await obj.EventStream.ReadAsync(0, upToVersion);
                foreach (var e in events)
                {
                    obj.Fold(e);
                }
            }
            else
            {
                await obj.Fold();
            }

            return obj;
        }
        catch (Exception)
        {
            return null;
        }
    }

    public async Task<(Sprint?, IObjectDocument?)> GetByIdWithDocumentAsync(
        SprintId id,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var document = await objectDocumentFactory.GetAsync(ObjectName, id.ToString(), null, "cosmosdb");
            var obj = sprintFactory.Create(document);
            await obj.Fold();
            return (obj, document);
        }
        catch (Exception)
        {
            return (null, null);
        }
    }

    public async Task<Sprint?> GetFirstByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tag);

        var document = await objectDocumentFactory.GetFirstByObjectDocumentTag(ObjectName, tag);
        if (document == null)
        {
            return null;
        }

        var obj = sprintFactory.Create(document);
        await obj.Fold();
        return obj;
    }

    public async Task<IEnumerable<Sprint>> GetAllByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tag);

        var documents = await objectDocumentFactory.GetByObjectDocumentTag(ObjectName, tag);
        var items = new List<Sprint>();

        foreach (var document in documents)
        {
            var obj = sprintFactory.Create(document);
            await obj.Fold();
            items.Add(obj);
        }

        return items;
    }

    public async Task<bool> ExistsAsync(
        SprintId id,
        CancellationToken cancellationToken = default)
    {
        return await objectIdProvider.ExistsAsync(
            ObjectName,
            id.ToString(),
            cancellationToken);
    }

    public async Task<long> CountAsync(CancellationToken cancellationToken = default)
    {
        return await objectIdProvider.CountAsync(ObjectName, cancellationToken);
    }
}
