using ErikLieben.FA.ES;
using ErikLieben.FA.ES.Aggregates;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Processors;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.Sprint;
using TaskFlow.Domain.ValueObjects;
using TaskFlow.Domain.ValueObjects.Sprint;

#nullable enable

namespace TaskFlow.Domain.Aggregates;

// <auto-generated />
/// <summary>
/// Sprint aggregate root implementing event sourcing patterns.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public partial class Sprint : Aggregate, IBase, ISprint
{

    /// <summary>
    /// Gets the logical object name for this aggregate type (AOT-friendly static member).
    /// </summary>
    public static string ObjectName => "sprint";

    /// <summary>
    /// Creates a new instance of the aggregate from an event stream (AOT-friendly factory).
    /// </summary>
    /// <param name="stream">The event stream for the aggregate.</param>
    /// <returns>A new instance of the aggregate.</returns>
    public static Sprint Create(IEventStream stream) => new Sprint(stream);

    /// <summary>
    /// Applies an event to the aggregate state by dispatching to the appropriate When method.
    /// </summary>
    /// <param name="event">The event to apply to the aggregate.</param>
    public override void Fold(IEvent @event)
    {
        switch (@event.EventType)
        {
            case "Sprint.Created":
                When(JsonEvent.To(@event, SprintCreatedJsonSerializerContext.Default.SprintCreated));
                break;
            case "Sprint.WorkItemAdded":
                When(JsonEvent.To(@event, WorkItemAddedToSprintJsonSerializerContext.Default.WorkItemAddedToSprint));
                break;
            case "Sprint.WorkItemRemoved":
                When(JsonEvent.To(@event, WorkItemRemovedFromSprintJsonSerializerContext.Default.WorkItemRemovedFromSprint));
                break;
            case "Sprint.GoalUpdated":
                When(JsonEvent.To(@event, SprintGoalUpdatedJsonSerializerContext.Default.SprintGoalUpdated));
                break;
            case "Sprint.DatesChanged":
                When(JsonEvent.To(@event, SprintDatesChangedJsonSerializerContext.Default.SprintDatesChanged));
                break;
            case "Sprint.Started":
                WhenSprintStarted();
                break;
            case "Sprint.Completed":
                WhenSprintCompleted();
                break;
            case "Sprint.Cancelled":
                WhenSprintCancelled();
                break;
        }

        PostWhen(Stream.Document, @event);
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    protected override void GeneratedSetup()
    {
        Stream.RegisterEvent<SprintCreated>(
      "Sprint.Created",
      SprintCreatedJsonSerializerContext.Default.SprintCreated);
        Stream.RegisterEvent<WorkItemAddedToSprint>(
            "Sprint.WorkItemAdded",
            WorkItemAddedToSprintJsonSerializerContext.Default.WorkItemAddedToSprint);
        Stream.RegisterEvent<WorkItemRemovedFromSprint>(
            "Sprint.WorkItemRemoved",
            WorkItemRemovedFromSprintJsonSerializerContext.Default.WorkItemRemovedFromSprint);
        Stream.RegisterEvent<SprintGoalUpdated>(
            "Sprint.GoalUpdated",
            SprintGoalUpdatedJsonSerializerContext.Default.SprintGoalUpdated);
        Stream.RegisterEvent<SprintDatesChanged>(
            "Sprint.DatesChanged",
            SprintDatesChangedJsonSerializerContext.Default.SprintDatesChanged);
        Stream.RegisterEvent<SprintStarted>(
            "Sprint.Started",
            SprintStartedJsonSerializerContext.Default.SprintStarted);
        Stream.RegisterEvent<SprintCompleted>(
            "Sprint.Completed",
            SprintCompletedJsonSerializerContext.Default.SprintCompleted);
        Stream.RegisterEvent<SprintCancelled>(
            "Sprint.Cancelled",
            SprintCancelledJsonSerializerContext.Default.SprintCancelled);
        Stream.SetSnapShotType(SprintJsonSerializerContext.Default.SprintSnapshot);
        Stream.SetAggregateType(SprintJsonSerializerContext.Default.Sprint);

        // Freeze the EventTypeRegistry for optimized lookups (~50% faster)
        Stream.EventTypeRegistry.Freeze();
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    public override void ProcessSnapshot(object snapshot)
    {
        throw new NotImplementedException();
    }
}

// <auto-generated />
/// <summary>
/// Interface defining the public state properties of Sprint.
/// </summary>
public partial interface ISprint
{
    public String? Name { get; }
    public ProjectId? ProjectId { get; }
    public DateTime StartDate { get; }
    public DateTime EndDate { get; }
    public String? Goal { get; }
    public SprintStatus Status { get; }
    public DateTime CreatedAt { get; }
    public UserProfileId? CreatedBy { get; }
    public List<TaskFlow.Domain.ValueObjects.WorkItemId>? WorkItems { get; }
    public ObjectMetadata<TaskFlow.Domain.ValueObjects.SprintId>? Metadata { get; }
}

// <auto-generated />
/// <summary>
/// Snapshot record for persisting Sprint aggregate state.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public record SprintSnapshot : ISprint
{
    public required String? Name { get; init; }
    public required ProjectId? ProjectId { get; init; }
    public required DateTime StartDate { get; init; }
    public required DateTime EndDate { get; init; }
    public required String? Goal { get; init; }
    public required SprintStatus Status { get; init; }
    public required DateTime CreatedAt { get; init; }
    public required UserProfileId? CreatedBy { get; init; }
    public required List<TaskFlow.Domain.ValueObjects.WorkItemId>? WorkItems { get; init; }
    public required ObjectMetadata<TaskFlow.Domain.ValueObjects.SprintId>? Metadata { get; init; }
}

[JsonSerializable(typeof(SprintCreated))]
[JsonSerializable(typeof(WorkItemAddedToSprint))]
[JsonSerializable(typeof(WorkItemRemovedFromSprint))]
[JsonSerializable(typeof(SprintGoalUpdated))]
[JsonSerializable(typeof(SprintDatesChanged))]
[JsonSerializable(typeof(SprintStarted))]
[JsonSerializable(typeof(SprintCompleted))]
[JsonSerializable(typeof(SprintCancelled))]
[JsonSerializable(typeof(SprintSnapshot))]
[JsonSerializable(typeof(Sprint))]
[JsonSerializable(typeof(SprintId))]
[JsonSerializable(typeof(ErikLieben.FA.StronglyTypedIds.StronglyTypedId<Guid>))]
[JsonSerializable(typeof(ErikLieben.FA.StronglyTypedIds.StronglyTypedId<String>))]
[JsonSerializable(typeof(System.Enum))]
[JsonSerializable(typeof(System.Guid))]
[JsonSerializable(typeof(System.String))]
[JsonSerializable(typeof(TaskFlow.Domain.ValueObjects.SprintId))]
// <auto-generated />
/// <summary>
/// JSON serializer context for Sprint types.
/// </summary>
internal partial class SprintJsonSerializerContext : JsonSerializerContext
{
}

//<auto-generated />
/// <summary>
/// Factory interface for creating Sprint aggregate instances.
/// </summary>
public partial interface ISprintFactory : IAggregateFactory<Sprint, SprintId>
{
}
