using ErikLieben.FA.ES;
using ErikLieben.FA.ES.Aggregates;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Processors;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.TimeSheet;
using TaskFlow.Domain.ValueObjects;
using TaskFlow.Domain.ValueObjects.TimeSheet;

#nullable enable

namespace TaskFlow.Domain.Aggregates;

//<auto-generated />
/// <summary>
/// Factory for creating and loading TimeSheet aggregate instances from documents and event streams.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public partial class TimeSheetFactory : ITimeSheetFactory
{
    private readonly IEventStreamFactory eventStreamFactory;
    private readonly IObjectDocumentFactory objectDocumentFactory;
    private readonly IServiceProvider serviceProvider;

    /// <summary>
    /// Gets the object name used for document storage.
    /// </summary>
    public static string ObjectName => "timeSheet";

    /// <summary>
    /// Gets the object name used for document storage.
    /// </summary>
    /// <returns>The object name.</returns>
    public string GetObjectName()
    {
        return ObjectName;
    }

    /// <summary>
    /// Initializes a new instance of the TimeSheetFactory class.
    /// </summary>
    /// <param name="serviceProvider">Service provider for dependency injection.</param>
    /// <param name="eventStreamFactory">Factory for creating event streams.</param>
    /// <param name="objectDocumentFactory">Factory for creating and managing object documents.</param>
    public TimeSheetFactory(
      IServiceProvider serviceProvider,
      IEventStreamFactory eventStreamFactory,
      IObjectDocumentFactory objectDocumentFactory)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        ArgumentNullException.ThrowIfNull(eventStreamFactory);
        ArgumentNullException.ThrowIfNull(objectDocumentFactory);

        this.serviceProvider = serviceProvider;
        this.eventStreamFactory = eventStreamFactory;
        this.objectDocumentFactory = objectDocumentFactory;
    }

    /// <summary>
    /// Creates a TimeSheet instance from an event stream.
    /// </summary>
    /// <param name="eventStream">The event stream to create the aggregate from.</param>
    /// <returns>A new TimeSheet instance.</returns>
    public TimeSheet Create(IEventStream eventStream)
    {
        ArgumentNullException.ThrowIfNull(eventStream);

        // get the params required from DI

        return new TimeSheet(eventStream);
    }

    /// <summary>
    /// Creates a TimeSheet instance from an object document.
    /// </summary>
    /// <param name="document">The object document to create the aggregate from.</param>
    /// <returns>A new TimeSheet instance.</returns>
    public TimeSheet Create(IObjectDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        // get the params required from DI

        var eventStream = eventStreamFactory.Create(document);
        return new TimeSheet(eventStream);
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    /// <summary>
    /// Creates a new TimeSheet aggregate with the specified identifier.
    /// </summary>
    /// <param name="id">The identifier for the new aggregate.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A new TimeSheet instance.</returns>
    public async Task<TimeSheet> CreateAsync(TimeSheetId id, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetOrCreateAsync(ObjectName, id.ToString(), null, "appendblob");

        // Apply aggregate-specific settings for new documents
        if (document.Active.CurrentStreamVersion == -1)
        {
            document.Active.StreamType = "appendblob";
            document.Active.DocumentType = "appendblob";
            await this.objectDocumentFactory.SetAsync(document);
        }
        var obj = Create(document);
        await obj.Fold();
        return obj;
    }

    /// <summary>
    /// Creates a new TimeSheet aggregate with the specified identifier and first event.
    /// </summary>
    /// <typeparam name="T">The type of the first event.</typeparam>
    /// <param name="id">The identifier for the new aggregate.</param>
    /// <param name="firstEvent">The first event to append to the aggregate's event stream.</param>
    /// <param name="metadata">Optional metadata to attach to the event.</param>
    /// <returns>A new TimeSheet instance with the event applied.</returns>
    protected async Task<TimeSheet> CreateAsync<T>(TimeSheetId id, T firstEvent, ActionMetadata? metadata = null) where T : class
    {
        var document = await this.objectDocumentFactory.GetOrCreateAsync(ObjectName, id.ToString(), null, "appendblob");

        // Apply aggregate-specific settings for new documents
        if (document.Active.CurrentStreamVersion == -1)
        {
            document.Active.StreamType = "appendblob";
            document.Active.DocumentType = "appendblob";
            await this.objectDocumentFactory.SetAsync(document);
        }
        var eventStream = eventStreamFactory.Create(document);
        var obj = new TimeSheet(eventStream);
        await eventStream.Session(context => context.Append(firstEvent, metadata));
        await obj.Fold();
        return obj;
    }

    /// <summary>
    /// Gets an existing TimeSheet aggregate by identifier.
    /// </summary>
    /// <param name="id">The identifier of the aggregate to retrieve.</param>
    /// <param name="upToVersion">Optional maximum event version to fold. If null, loads to current state.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The loaded TimeSheet instance.</returns>
    [Obsolete("Use ITimeSheetRepository.GetByIdAsync instead. This method will be removed in a future version.")]
    public async Task<TimeSheet> GetAsync(TimeSheetId id, int? upToVersion = null, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetAsync(ObjectName, id.ToString(), null, "appendblob");

        // Create event stream
        var eventStream = eventStreamFactory.Create(document);

        // Create aggregate FIRST to register upcasters and event handlers
        var obj = new TimeSheet(eventStream);

        // Read events up to version WITH upcasting applied
        var events = await eventStream.ReadAsync(0, upToVersion);

        // Fold events into the aggregate
        foreach (var e in events)
        {
            obj.Fold(e);
        }

        return obj;
    }

    /// <summary>
    /// Gets an existing TimeSheet aggregate by identifier along with its document.
    /// </summary>
    /// <param name="id">The identifier of the aggregate to retrieve.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A tuple containing the loaded TimeSheet instance and its document.</returns>
    [Obsolete("Use ITimeSheetRepository.GetByIdWithDocumentAsync instead. This method will be removed in a future version.")]
    public async Task<(TimeSheet, IObjectDocument)> GetWithDocumentAsync(TimeSheetId id, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetAsync(ObjectName, id.ToString(), null, "appendblob");
        var obj = Create(document);
        await obj.Fold();
        return (obj, document);
    }

    /// <summary>
    /// Gets the first TimeSheet aggregate with the specified document tag.
    /// </summary>
    /// <param name="tag">The document tag to search for.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The first matching TimeSheet instance, or null if not found.</returns>
    [Obsolete("Use ITimeSheetRepository.GetFirstByDocumentTagAsync instead. This method will be removed in a future version.")]
    public async Task<TimeSheet?> GetFirstByDocumentTag(string tag, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetFirstByObjectDocumentTag(ObjectName, tag);
        if (document == null)
        {
            return null;
        }
        var obj = Create(document);
        await obj.Fold();
        return obj;
    }

    /// <summary>
    /// Gets all TimeSheet aggregates with the specified document tag.
    /// </summary>
    /// <param name="tag">The document tag to search for.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A collection of all matching TimeSheet instances.</returns>
    [Obsolete("Use ITimeSheetRepository.GetAllByDocumentTagAsync instead. This method will be removed in a future version.")]
    public async Task<IEnumerable<TimeSheet>> GetAllByDocumentTag(string tag, CancellationToken cancellationToken = default)
    {
        var documents = (await this.objectDocumentFactory.GetByObjectDocumentTag(ObjectName, tag));
        var items = new List<TimeSheet>();
        foreach (var document in documents)
        {
            var obj = Create(document);
            await obj.Fold();
            items.Add(obj);
        }
        return items;
    }
}
