using ErikLieben.FA.ES;
using ErikLieben.FA.ES.Aggregates;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Processors;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.UserProfile;
using TaskFlow.Domain.ValueObjects;

#nullable enable

namespace TaskFlow.Domain.Aggregates;

// <auto-generated />
/// <summary>
/// UserProfile aggregate root implementing event sourcing patterns.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public partial class UserProfile : Aggregate, IBase, IUserProfile
{

    /// <summary>
    /// Gets the logical object name for this aggregate type (AOT-friendly static member).
    /// </summary>
    public static string ObjectName => "userProfile";

    /// <summary>
    /// Creates a new instance of the aggregate from an event stream (AOT-friendly factory).
    /// </summary>
    /// <param name="stream">The event stream for the aggregate.</param>
    /// <returns>A new instance of the aggregate.</returns>
    public static UserProfile Create(IEventStream stream) => new UserProfile(stream);

    /// <summary>
    /// Applies an event to the aggregate state by dispatching to the appropriate When method.
    /// </summary>
    /// <param name="event">The event to apply to the aggregate.</param>
    public override void Fold(IEvent @event)
    {
        switch (@event.EventType)
        {
            case "UserProfile.Created":
                When(JsonEvent.To(@event, UserProfileCreatedJsonSerializerContext.Default.UserProfileCreated));
                break;
            case "UserProfile.Updated":
                When(JsonEvent.To(@event, UserProfileUpdatedJsonSerializerContext.Default.UserProfileUpdated));
                break;
        }

        PostWhen(Stream.Document, @event);
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    protected override void GeneratedSetup()
    {
        Stream.RegisterEvent<UserProfileCreated>(
      "UserProfile.Created",
      UserProfileCreatedJsonSerializerContext.Default.UserProfileCreated);
        Stream.RegisterEvent<UserProfileUpdated>(
            "UserProfile.Updated",
            UserProfileUpdatedJsonSerializerContext.Default.UserProfileUpdated);
        Stream.SetSnapShotType(UserProfileJsonSerializerContext.Default.UserProfileSnapshot);
        Stream.SetAggregateType(UserProfileJsonSerializerContext.Default.UserProfile);

        // Freeze the EventTypeRegistry for optimized lookups (~50% faster)
        Stream.EventTypeRegistry.Freeze();
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    public override void ProcessSnapshot(object snapshot)
    {
        throw new NotImplementedException();
    }
}

// <auto-generated />
/// <summary>
/// Interface defining the public state properties of UserProfile.
/// </summary>
public interface IUserProfile
{
    public String? DisplayName { get; }
    public String? Email { get; }
    public String? JobRole { get; }
    public DateTime CreatedAt { get; }
    public Nullable<System.DateTime> LastUpdatedAt { get; }
    public ObjectMetadata<TaskFlow.Domain.ValueObjects.UserProfileId>? Metadata { get; }
}

// <auto-generated />
/// <summary>
/// Snapshot record for persisting UserProfile aggregate state.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public record UserProfileSnapshot : IUserProfile
{
    public required String? DisplayName { get; init; }
    public required String? Email { get; init; }
    public required String? JobRole { get; init; }
    public required DateTime CreatedAt { get; init; }
    public required Nullable<System.DateTime> LastUpdatedAt { get; init; }
    public required ObjectMetadata<TaskFlow.Domain.ValueObjects.UserProfileId>? Metadata { get; init; }
}

[JsonSerializable(typeof(UserProfileCreated))]
[JsonSerializable(typeof(UserProfileUpdated))]
[JsonSerializable(typeof(UserProfileSnapshot))]
[JsonSerializable(typeof(UserProfile))]
[JsonSerializable(typeof(UserProfileId))]
[JsonSerializable(typeof(System.String))]
[JsonSerializable(typeof(TaskFlow.Domain.ValueObjects.UserProfileId))]
// <auto-generated />
/// <summary>
/// JSON serializer context for UserProfile types.
/// </summary>
internal partial class UserProfileJsonSerializerContext : JsonSerializerContext
{
}

//<auto-generated />
/// <summary>
/// Factory interface for creating UserProfile aggregate instances.
/// </summary>
public partial interface IUserProfileFactory : IAggregateFactory<UserProfile, UserProfileId>
{
}

//<auto-generated />
/// <summary>
/// Factory for creating and loading UserProfile aggregate instances from documents and event streams.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public partial class UserProfileFactory : IUserProfileFactory
{
    private readonly IEventStreamFactory eventStreamFactory;
    private readonly IObjectDocumentFactory objectDocumentFactory;
    private readonly IServiceProvider serviceProvider;

    /// <summary>
    /// Gets the object name used for document storage.
    /// </summary>
    public static string ObjectName => "userProfile";

    /// <summary>
    /// Gets the object name used for document storage.
    /// </summary>
    /// <returns>The object name.</returns>
    public string GetObjectName()
    {
        return ObjectName;
    }

    /// <summary>
    /// Initializes a new instance of the UserProfileFactory class.
    /// </summary>
    /// <param name="serviceProvider">Service provider for dependency injection.</param>
    /// <param name="eventStreamFactory">Factory for creating event streams.</param>
    /// <param name="objectDocumentFactory">Factory for creating and managing object documents.</param>
    public UserProfileFactory(
      IServiceProvider serviceProvider,
      IEventStreamFactory eventStreamFactory,
      IObjectDocumentFactory objectDocumentFactory)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        ArgumentNullException.ThrowIfNull(eventStreamFactory);
        ArgumentNullException.ThrowIfNull(objectDocumentFactory);

        this.serviceProvider = serviceProvider;
        this.eventStreamFactory = eventStreamFactory;
        this.objectDocumentFactory = objectDocumentFactory;
    }

    /// <summary>
    /// Creates a UserProfile instance from an event stream.
    /// </summary>
    /// <param name="eventStream">The event stream to create the aggregate from.</param>
    /// <returns>A new UserProfile instance.</returns>
    public UserProfile Create(IEventStream eventStream)
    {
        ArgumentNullException.ThrowIfNull(eventStream);

        // get the params required from DI

        return new UserProfile(eventStream);
    }

    /// <summary>
    /// Creates a UserProfile instance from an object document.
    /// </summary>
    /// <param name="document">The object document to create the aggregate from.</param>
    /// <returns>A new UserProfile instance.</returns>
    public UserProfile Create(IObjectDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        // get the params required from DI

        var eventStream = eventStreamFactory.Create(document);
        return new UserProfile(eventStream);
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    /// <summary>
    /// Creates a new UserProfile aggregate with the specified identifier.
    /// </summary>
    /// <param name="id">The identifier for the new aggregate.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A new UserProfile instance.</returns>
    public async Task<UserProfile> CreateAsync(UserProfileId id, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetOrCreateAsync(ObjectName, id.ToString(), "UserDataStore", null);

        // Apply aggregate-specific settings for new documents
        if (document.Active.CurrentStreamVersion == -1)
        {
            document.Active.DataStore = "UserDataStore";
            document.Active.StreamConnectionName = "UserDataStore";
            document.Active.DocumentStore = "UserDataStore";
            document.Active.DocumentConnectionName = "UserDataStore";
            document.Active.DocumentTagStore = "UserDataStore";
            document.Active.DocumentTagConnectionName = "UserDataStore";
            document.Active.StreamTagStore = "UserDataStore";
            document.Active.StreamTagConnectionName = "UserDataStore";
            document.Active.SnapShotStore = "UserDataStore";
            document.Active.SnapShotConnectionName = "UserDataStore";
            await this.objectDocumentFactory.SetAsync(document);
        }
        var obj = Create(document);
        await obj.Fold();
        return obj;
    }

    /// <summary>
    /// Creates a new UserProfile aggregate with the specified identifier and first event.
    /// </summary>
    /// <typeparam name="T">The type of the first event.</typeparam>
    /// <param name="id">The identifier for the new aggregate.</param>
    /// <param name="firstEvent">The first event to append to the aggregate's event stream.</param>
    /// <param name="metadata">Optional metadata to attach to the event.</param>
    /// <returns>A new UserProfile instance with the event applied.</returns>
    protected async Task<UserProfile> CreateAsync<T>(UserProfileId id, T firstEvent, ActionMetadata? metadata = null) where T : class
    {
        var document = await this.objectDocumentFactory.GetOrCreateAsync(ObjectName, id.ToString(), "UserDataStore", null);

        // Apply aggregate-specific settings for new documents
        if (document.Active.CurrentStreamVersion == -1)
        {
            document.Active.DataStore = "UserDataStore";
            document.Active.StreamConnectionName = "UserDataStore";
            document.Active.DocumentStore = "UserDataStore";
            document.Active.DocumentConnectionName = "UserDataStore";
            document.Active.DocumentTagStore = "UserDataStore";
            document.Active.DocumentTagConnectionName = "UserDataStore";
            document.Active.StreamTagStore = "UserDataStore";
            document.Active.StreamTagConnectionName = "UserDataStore";
            document.Active.SnapShotStore = "UserDataStore";
            document.Active.SnapShotConnectionName = "UserDataStore";
            await this.objectDocumentFactory.SetAsync(document);
        }
        var eventStream = eventStreamFactory.Create(document);
        var obj = new UserProfile(eventStream);
        await eventStream.Session(context => context.Append(firstEvent, metadata));
        await obj.Fold();
        return obj;
    }

    /// <summary>
    /// Gets an existing UserProfile aggregate by identifier.
    /// </summary>
    /// <param name="id">The identifier of the aggregate to retrieve.</param>
    /// <param name="upToVersion">Optional maximum event version to fold. If null, loads to current state.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The loaded UserProfile instance.</returns>
    [Obsolete("Use IUserProfileRepository.GetByIdAsync instead. This method will be removed in a future version.")]
    public async Task<UserProfile> GetAsync(UserProfileId id, int? upToVersion = null, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetAsync(ObjectName, id.ToString(), "UserDataStore", null);

        // Create event stream
        var eventStream = eventStreamFactory.Create(document);

        // Create aggregate FIRST to register upcasters and event handlers
        var obj = new UserProfile(eventStream);

        // Read events up to version WITH upcasting applied
        var events = await eventStream.ReadAsync(0, upToVersion);

        // Fold events into the aggregate
        foreach (var e in events)
        {
            obj.Fold(e);
        }

        return obj;
    }

    /// <summary>
    /// Gets an existing UserProfile aggregate by identifier along with its document.
    /// </summary>
    /// <param name="id">The identifier of the aggregate to retrieve.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A tuple containing the loaded UserProfile instance and its document.</returns>
    [Obsolete("Use IUserProfileRepository.GetByIdWithDocumentAsync instead. This method will be removed in a future version.")]
    public async Task<(UserProfile, IObjectDocument)> GetWithDocumentAsync(UserProfileId id, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetAsync(ObjectName, id.ToString(), "UserDataStore", null);
        var obj = Create(document);
        await obj.Fold();
        return (obj, document);
    }

    /// <summary>
    /// Gets the first UserProfile aggregate with the specified document tag.
    /// </summary>
    /// <param name="tag">The document tag to search for.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The first matching UserProfile instance, or null if not found.</returns>
    [Obsolete("Use IUserProfileRepository.GetFirstByDocumentTagAsync instead. This method will be removed in a future version.")]
    public async Task<UserProfile?> GetFirstByDocumentTag(string tag, CancellationToken cancellationToken = default)
    {
        var document = await this.objectDocumentFactory.GetFirstByObjectDocumentTag(ObjectName, tag, "UserDataStore", "UserDataStore");
        if (document == null)
        {
            return null;
        }
        var obj = Create(document);
        await obj.Fold();
        return obj;
    }

    /// <summary>
    /// Gets all UserProfile aggregates with the specified document tag.
    /// </summary>
    /// <param name="tag">The document tag to search for.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A collection of all matching UserProfile instances.</returns>
    [Obsolete("Use IUserProfileRepository.GetAllByDocumentTagAsync instead. This method will be removed in a future version.")]
    public async Task<IEnumerable<UserProfile>> GetAllByDocumentTag(string tag, CancellationToken cancellationToken = default)
    {
        var documents = (await this.objectDocumentFactory.GetByObjectDocumentTag(ObjectName, tag, "UserDataStore", "UserDataStore"));
        var items = new List<UserProfile>();
        foreach (var document in documents)
        {
            var obj = Create(document);
            await obj.Fold();
            items.Add(obj);
        }
        return items;
    }
}

//<auto-generated />
public partial interface IUserProfileRepository
{
    /// <summary>
    /// Gets a paginated list of all UserProfile object IDs using continuation tokens.
    /// </summary>
    Task<PagedResult<string>> GetObjectIdsAsync(
        string? continuationToken = null,
        int pageSize = 100,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a single aggregate by ID.
    /// </summary>
    /// <param name="upToVersion">Optional: The maximum event version to fold. If null, loads to current state.</param>
    Task<UserProfile?> GetByIdAsync(
        UserProfileId id,
        int? upToVersion = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a single aggregate by ID along with its document.
    /// </summary>
    Task<(UserProfile?, IObjectDocument?)> GetByIdWithDocumentAsync(
        UserProfileId id,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the first aggregate with the specified document tag.
    /// </summary>
    Task<UserProfile?> GetFirstByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all aggregates with the specified document tag.
    /// </summary>
    Task<IEnumerable<UserProfile>> GetAllByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Checks if an aggregate with the given ID exists.
    /// </summary>
    Task<bool> ExistsAsync(
        UserProfileId id,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the total count of aggregates.
    /// Warning: This may be expensive for large datasets.
    /// </summary>
    Task<long> CountAsync(CancellationToken cancellationToken = default);
}

//<auto-generated />
/// <summary>
/// Repository for querying and managing UserProfile aggregates.
/// </summary>
public partial class UserProfileRepository : IUserProfileRepository
{
    private readonly IUserProfileFactory userprofileFactory;
    private readonly IObjectDocumentFactory objectDocumentFactory;
    private readonly IObjectIdProvider objectIdProvider;

    /// <summary>
    /// Gets the object name used for document storage.
    /// </summary>
    public static string ObjectName => "userProfile";

    /// <summary>
    /// Initializes a new instance of the UserProfileRepository class.
    /// </summary>
    /// <param name="userprofileFactory">Factory for creating UserProfile instances.</param>
    /// <param name="objectDocumentFactory">Factory for managing object documents.</param>
    /// <param name="objectIdProvider">Provider for querying object identifiers.</param>
    public UserProfileRepository(
        IUserProfileFactory userprofileFactory,
        IObjectDocumentFactory objectDocumentFactory,
        IObjectIdProvider objectIdProvider)
    {
        ArgumentNullException.ThrowIfNull(userprofileFactory);
        ArgumentNullException.ThrowIfNull(objectDocumentFactory);
        ArgumentNullException.ThrowIfNull(objectIdProvider);

        this.userprofileFactory = userprofileFactory;
        this.objectDocumentFactory = objectDocumentFactory;
        this.objectIdProvider = objectIdProvider;
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public async Task<PagedResult<string>> GetObjectIdsAsync(
        string? continuationToken = null,
        int pageSize = 100,
        CancellationToken cancellationToken = default)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(pageSize, 1);
        ArgumentOutOfRangeException.ThrowIfGreaterThan(pageSize, 1000);

        return await objectIdProvider.GetObjectIdsAsync(
            ObjectName,
            continuationToken,
            pageSize,
            cancellationToken);
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public async Task<UserProfile?> GetByIdAsync(
        UserProfileId id,
        int? upToVersion = null,
        CancellationToken cancellationToken = default)
    {
        try
        {
            return await userprofileFactory.GetAsync(id, upToVersion);
        }
        catch (Exception)
        {
            return null;
        }
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public async Task<(UserProfile?, IObjectDocument?)> GetByIdWithDocumentAsync(
        UserProfileId id,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var document = await objectDocumentFactory.GetAsync(ObjectName, id.ToString(), "UserDataStore", null);
            var obj = userprofileFactory.Create(document);
            await obj.Fold();
            return (obj, document);
        }
        catch (Exception)
        {
            return (null, null);
        }
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public async Task<UserProfile?> GetFirstByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tag);

        var document = await objectDocumentFactory.GetFirstByObjectDocumentTag(ObjectName, tag, "UserDataStore", "UserDataStore");
        if (document == null)
        {
            return null;
        }

        var obj = userprofileFactory.Create(document);
        await obj.Fold();
        return obj;
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public async Task<IEnumerable<UserProfile>> GetAllByDocumentTagAsync(
        string tag,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tag);

        var documents = await objectDocumentFactory.GetByObjectDocumentTag(ObjectName, tag, "UserDataStore", "UserDataStore");
        var items = new List<UserProfile>();

        foreach (var document in documents)
        {
            var obj = userprofileFactory.Create(document);
            await obj.Fold();
            items.Add(obj);
        }

        return items;
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public async Task<bool> ExistsAsync(
        UserProfileId id,
        CancellationToken cancellationToken = default)
    {
        return await objectIdProvider.ExistsAsync(
            ObjectName,
            id.ToString(),
            cancellationToken);
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public async Task<long> CountAsync(CancellationToken cancellationToken = default)
    {
        return await objectIdProvider.CountAsync(ObjectName, cancellationToken);
    }
}
