using ErikLieben.FA.ES;
using ErikLieben.FA.ES.Aggregates;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Processors;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.UserProfile;
using TaskFlow.Domain.ValueObjects;

#nullable enable

namespace TaskFlow.Domain.Aggregates;

// <auto-generated />
/// <summary>
/// UserProfile aggregate root implementing event sourcing patterns.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public partial class UserProfile : Aggregate, IBase, IUserProfile
{

    /// <summary>
    /// Gets the logical object name for this aggregate type (AOT-friendly static member).
    /// </summary>
    public static string ObjectName => "userProfile";

    /// <summary>
    /// Creates a new instance of the aggregate from an event stream (AOT-friendly factory).
    /// </summary>
    /// <param name="stream">The event stream for the aggregate.</param>
    /// <returns>A new instance of the aggregate.</returns>
    public static UserProfile Create(IEventStream stream) => new UserProfile(stream);

    /// <summary>
    /// Applies an event to the aggregate state by dispatching to the appropriate When method.
    /// </summary>
    /// <param name="event">The event to apply to the aggregate.</param>
    public override void Fold(IEvent @event)
    {
        switch (@event.EventType)
        {
            case "UserProfile.Created":
                When(JsonEvent.To(@event, UserProfileCreatedJsonSerializerContext.Default.UserProfileCreated));
                break;
            case "UserProfile.Updated":
                When(JsonEvent.To(@event, UserProfileUpdatedJsonSerializerContext.Default.UserProfileUpdated));
                break;
        }

        PostWhen(Stream.Document, @event);
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    protected override void GeneratedSetup()
    {
        Stream.RegisterEvent<UserProfileCreated>(
      "UserProfile.Created",
      UserProfileCreatedJsonSerializerContext.Default.UserProfileCreated);
        Stream.RegisterEvent<UserProfileUpdated>(
            "UserProfile.Updated",
            UserProfileUpdatedJsonSerializerContext.Default.UserProfileUpdated);
        Stream.SetSnapShotType(UserProfileJsonSerializerContext.Default.UserProfileSnapshot);
        Stream.SetAggregateType(UserProfileJsonSerializerContext.Default.UserProfile);

        // Freeze the EventTypeRegistry for optimized lookups (~50% faster)
        Stream.EventTypeRegistry.Freeze();
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    public override void ProcessSnapshot(object snapshot)
    {
        throw new NotImplementedException();
    }
}

// <auto-generated />
/// <summary>
/// Interface defining the public state properties of UserProfile.
/// </summary>
public partial interface IUserProfile
{
    public String? DisplayName { get; }
    public String? Email { get; }
    public String? JobRole { get; }
    public DateTime CreatedAt { get; }
    public Nullable<System.DateTime> LastUpdatedAt { get; }
    public ObjectMetadata<TaskFlow.Domain.ValueObjects.UserProfileId>? Metadata { get; }
}

// <auto-generated />
/// <summary>
/// Snapshot record for persisting UserProfile aggregate state.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public record UserProfileSnapshot : IUserProfile
{
    public required String? DisplayName { get; init; }
    public required String? Email { get; init; }
    public required String? JobRole { get; init; }
    public required DateTime CreatedAt { get; init; }
    public required Nullable<System.DateTime> LastUpdatedAt { get; init; }
    public required ObjectMetadata<TaskFlow.Domain.ValueObjects.UserProfileId>? Metadata { get; init; }
}

[JsonSerializable(typeof(UserProfileCreated))]
[JsonSerializable(typeof(UserProfileUpdated))]
[JsonSerializable(typeof(UserProfileSnapshot))]
[JsonSerializable(typeof(UserProfile))]
[JsonSerializable(typeof(UserProfileId))]
[JsonSerializable(typeof(System.String))]
[JsonSerializable(typeof(TaskFlow.Domain.ValueObjects.UserProfileId))]
// <auto-generated />
/// <summary>
/// JSON serializer context for UserProfile types.
/// </summary>
internal partial class UserProfileJsonSerializerContext : JsonSerializerContext
{
}

//<auto-generated />
/// <summary>
/// Factory interface for creating UserProfile aggregate instances.
/// </summary>
public partial interface IUserProfileFactory : IAggregateFactory<UserProfile, UserProfileId>
{
}
