using ErikLieben.FA.ES;
using ErikLieben.FA.ES.Aggregates;
using ErikLieben.FA.ES.Documents;
using ErikLieben.FA.ES.Processors;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using TaskFlow.Domain.Events.WorkItem;
using TaskFlow.Domain.ValueObjects;
using TaskFlow.Domain.ValueObjects.WorkItem;

#nullable enable

namespace TaskFlow.Domain.Aggregates;

// <auto-generated />
/// <summary>
/// WorkItem aggregate root implementing event sourcing patterns.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public partial class WorkItem : Aggregate, IBase, IWorkItem
{

    /// <summary>
    /// Gets the logical object name for this aggregate type (AOT-friendly static member).
    /// </summary>
    public static string ObjectName => "workItem";

    /// <summary>
    /// Creates a new instance of the aggregate from an event stream (AOT-friendly factory).
    /// </summary>
    /// <param name="stream">The event stream for the aggregate.</param>
    /// <returns>A new instance of the aggregate.</returns>
    public static WorkItem Create(IEventStream stream) => new WorkItem(stream);

    /// <summary>
    /// Applies an event to the aggregate state by dispatching to the appropriate When method.
    /// </summary>
    /// <param name="event">The event to apply to the aggregate.</param>
    public override void Fold(IEvent @event)
    {
        switch (@event.EventType)
        {
            case "WorkItem.Planned":
                When(JsonEvent.To(@event, WorkItemPlannedJsonSerializerContext.Default.WorkItemPlanned));
                break;
            case "WorkItem.ResponsibilityAssigned":
                When(JsonEvent.To(@event, ResponsibilityAssignedJsonSerializerContext.Default.ResponsibilityAssigned));
                break;
            case "WorkItem.ResponsibilityRelinquished":
                When(JsonEvent.To(@event, ResponsibilityRelinquishedJsonSerializerContext.Default.ResponsibilityRelinquished));
                break;
            case "WorkItem.WorkCommenced":
                When(JsonEvent.To(@event, WorkCommencedJsonSerializerContext.Default.WorkCommenced));
                break;
            case "WorkItem.WorkCompleted":
                When(JsonEvent.To(@event, WorkCompletedJsonSerializerContext.Default.WorkCompleted));
                break;
            case "WorkItem.Revived":
                When(JsonEvent.To(@event, WorkItemRevivedJsonSerializerContext.Default.WorkItemRevived));
                break;
            case "WorkItem.Reprioritized":
                When(JsonEvent.To(@event, WorkItemReprioritizedJsonSerializerContext.Default.WorkItemReprioritized));
                break;
            case "WorkItem.EffortReestimated":
                When(JsonEvent.To(@event, EffortReestimatedJsonSerializerContext.Default.EffortReestimated));
                break;
            case "WorkItem.RequirementsRefined":
                When(JsonEvent.To(@event, RequirementsRefinedJsonSerializerContext.Default.RequirementsRefined));
                break;
            case "WorkItem.FeedbackProvided":
                When(JsonEvent.To(@event, FeedbackProvidedJsonSerializerContext.Default.FeedbackProvided));
                break;
            case "WorkItem.Relocated":
                When(JsonEvent.To(@event, WorkItemRelocatedJsonSerializerContext.Default.WorkItemRelocated));
                break;
            case "WorkItem.Retagged":
                When(JsonEvent.To(@event, WorkItemRetaggedJsonSerializerContext.Default.WorkItemRetagged));
                break;
            case "WorkItem.DeadlineEstablished":
                When(JsonEvent.To(@event, DeadlineEstablishedJsonSerializerContext.Default.DeadlineEstablished));
                break;
            case "WorkItem.DeadlineRemoved":
                When(JsonEvent.To(@event, DeadlineRemovedJsonSerializerContext.Default.DeadlineRemoved));
                break;
            case "WorkItem.MovedBackFromCompletedToInProgress":
                When(JsonEvent.To(@event, MovedBackFromCompletedToInProgressJsonSerializerContext.Default.MovedBackFromCompletedToInProgress));
                break;
            case "WorkItem.MovedBackFromCompletedToPlanned":
                When(JsonEvent.To(@event, MovedBackFromCompletedToPlannedJsonSerializerContext.Default.MovedBackFromCompletedToPlanned));
                break;
            case "WorkItem.MovedBackFromInProgressToPlanned":
                When(JsonEvent.To(@event, MovedBackFromInProgressToPlannedJsonSerializerContext.Default.MovedBackFromInProgressToPlanned));
                break;
            case "WorkItem.DragMarkedAsAccidental":
                When(JsonEvent.To(@event, DragMarkedAsAccidentalJsonSerializerContext.Default.DragMarkedAsAccidental));
                break;
        }

        PostWhen(Stream.Document, @event);
    }

    [GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
    [ExcludeFromCodeCoverage]
    protected override void GeneratedSetup()
    {
        Stream.RegisterEvent<WorkItemPlanned>(
      "WorkItem.Planned",
      WorkItemPlannedJsonSerializerContext.Default.WorkItemPlanned);
        Stream.RegisterEvent<ResponsibilityAssigned>(
            "WorkItem.ResponsibilityAssigned",
            ResponsibilityAssignedJsonSerializerContext.Default.ResponsibilityAssigned);
        Stream.RegisterEvent<ResponsibilityRelinquished>(
            "WorkItem.ResponsibilityRelinquished",
            ResponsibilityRelinquishedJsonSerializerContext.Default.ResponsibilityRelinquished);
        Stream.RegisterEvent<WorkCommenced>(
            "WorkItem.WorkCommenced",
            WorkCommencedJsonSerializerContext.Default.WorkCommenced);
        Stream.RegisterEvent<WorkCompleted>(
            "WorkItem.WorkCompleted",
            WorkCompletedJsonSerializerContext.Default.WorkCompleted);
        Stream.RegisterEvent<WorkItemRevived>(
            "WorkItem.Revived",
            WorkItemRevivedJsonSerializerContext.Default.WorkItemRevived);
        Stream.RegisterEvent<WorkItemReprioritized>(
            "WorkItem.Reprioritized",
            WorkItemReprioritizedJsonSerializerContext.Default.WorkItemReprioritized);
        Stream.RegisterEvent<EffortReestimated>(
            "WorkItem.EffortReestimated",
            EffortReestimatedJsonSerializerContext.Default.EffortReestimated);
        Stream.RegisterEvent<RequirementsRefined>(
            "WorkItem.RequirementsRefined",
            RequirementsRefinedJsonSerializerContext.Default.RequirementsRefined);
        Stream.RegisterEvent<FeedbackProvided>(
            "WorkItem.FeedbackProvided",
            FeedbackProvidedJsonSerializerContext.Default.FeedbackProvided);
        Stream.RegisterEvent<WorkItemRelocated>(
            "WorkItem.Relocated",
            WorkItemRelocatedJsonSerializerContext.Default.WorkItemRelocated);
        Stream.RegisterEvent<WorkItemRetagged>(
            "WorkItem.Retagged",
            WorkItemRetaggedJsonSerializerContext.Default.WorkItemRetagged);
        Stream.RegisterEvent<DeadlineEstablished>(
            "WorkItem.DeadlineEstablished",
            DeadlineEstablishedJsonSerializerContext.Default.DeadlineEstablished);
        Stream.RegisterEvent<DeadlineRemoved>(
            "WorkItem.DeadlineRemoved",
            DeadlineRemovedJsonSerializerContext.Default.DeadlineRemoved);
        Stream.RegisterEvent<MovedBackFromCompletedToInProgress>(
            "WorkItem.MovedBackFromCompletedToInProgress",
            MovedBackFromCompletedToInProgressJsonSerializerContext.Default.MovedBackFromCompletedToInProgress);
        Stream.RegisterEvent<MovedBackFromCompletedToPlanned>(
            "WorkItem.MovedBackFromCompletedToPlanned",
            MovedBackFromCompletedToPlannedJsonSerializerContext.Default.MovedBackFromCompletedToPlanned);
        Stream.RegisterEvent<MovedBackFromInProgressToPlanned>(
            "WorkItem.MovedBackFromInProgressToPlanned",
            MovedBackFromInProgressToPlannedJsonSerializerContext.Default.MovedBackFromInProgressToPlanned);
        Stream.RegisterEvent<DragMarkedAsAccidental>(
            "WorkItem.DragMarkedAsAccidental",
            DragMarkedAsAccidentalJsonSerializerContext.Default.DragMarkedAsAccidental);
        Stream.SetSnapShotType(WorkItemJsonSerializerContext.Default.WorkItemSnapshot);
        Stream.SetAggregateType(WorkItemJsonSerializerContext.Default.WorkItem);

        // Freeze the EventTypeRegistry for optimized lookups (~50% faster)
        Stream.EventTypeRegistry.Freeze();
    }
}

// <auto-generated />
/// <summary>
/// Interface defining the public state properties of WorkItem.
/// </summary>
public partial interface IWorkItem
{
    public Guid WorkItemId { get; }
    public String? ProjectId { get; }
    public String? Title { get; }
    public String? Description { get; }
    public WorkItemPriority Priority { get; }
    public WorkItemStatus Status { get; }
    public String? AssignedTo { get; }
    public Nullable<System.DateTime> Deadline { get; }
    public Nullable<System.Int32> EstimatedHours { get; }
    public List<System.String>? Tags { get; }
    public List<TaskFlow.Domain.ValueObjects.WorkItem.WorkItemComment>? Comments { get; }
    public List<TaskFlow.Domain.ValueObjects.WorkItem.LocalizedTitle>? TitleTranslations { get; }
    public ObjectMetadata<TaskFlow.Domain.ValueObjects.WorkItemId>? Metadata { get; }
}

// <auto-generated />
/// <summary>
/// Snapshot record for persisting WorkItem aggregate state.
/// </summary>
[GeneratedCode("ErikLieben.FA.ES", "1.0.0")]
[ExcludeFromCodeCoverage]
public record WorkItemSnapshot : IWorkItem
{
    public required Guid WorkItemId { get; init; }
    public required String? ProjectId { get; init; }
    public required String? Title { get; init; }
    public required String? Description { get; init; }
    public required WorkItemPriority Priority { get; init; }
    public required WorkItemStatus Status { get; init; }
    public required String? AssignedTo { get; init; }
    public required Nullable<System.DateTime> Deadline { get; init; }
    public required Nullable<System.Int32> EstimatedHours { get; init; }
    public required List<System.String>? Tags { get; init; }
    public required List<TaskFlow.Domain.ValueObjects.WorkItem.WorkItemComment>? Comments { get; init; }
    public required List<TaskFlow.Domain.ValueObjects.WorkItem.LocalizedTitle>? TitleTranslations { get; init; }
    public required ObjectMetadata<TaskFlow.Domain.ValueObjects.WorkItemId>? Metadata { get; init; }
}

[JsonSerializable(typeof(WorkItemPlanned))]
[JsonSerializable(typeof(ResponsibilityAssigned))]
[JsonSerializable(typeof(ResponsibilityRelinquished))]
[JsonSerializable(typeof(WorkCommenced))]
[JsonSerializable(typeof(WorkCompleted))]
[JsonSerializable(typeof(WorkItemRevived))]
[JsonSerializable(typeof(WorkItemReprioritized))]
[JsonSerializable(typeof(EffortReestimated))]
[JsonSerializable(typeof(RequirementsRefined))]
[JsonSerializable(typeof(FeedbackProvided))]
[JsonSerializable(typeof(WorkItemRelocated))]
[JsonSerializable(typeof(WorkItemRetagged))]
[JsonSerializable(typeof(DeadlineEstablished))]
[JsonSerializable(typeof(DeadlineRemoved))]
[JsonSerializable(typeof(MovedBackFromCompletedToInProgress))]
[JsonSerializable(typeof(MovedBackFromCompletedToPlanned))]
[JsonSerializable(typeof(MovedBackFromInProgressToPlanned))]
[JsonSerializable(typeof(DragMarkedAsAccidental))]
[JsonSerializable(typeof(WorkItemSnapshot))]
[JsonSerializable(typeof(WorkItem))]
[JsonSerializable(typeof(WorkItemId))]
[JsonSerializable(typeof(System.Enum))]
[JsonSerializable(typeof(System.String))]
[JsonSerializable(typeof(TaskFlow.Domain.ValueObjects.WorkItemId))]
// <auto-generated />
/// <summary>
/// JSON serializer context for WorkItem types.
/// </summary>
internal partial class WorkItemJsonSerializerContext : JsonSerializerContext
{
}

//<auto-generated />
/// <summary>
/// Factory interface for creating WorkItem aggregate instances.
/// </summary>
public partial interface IWorkItemFactory : IAggregateFactory<WorkItem, WorkItemId>
{
}
