#pragma warning disable S4136 // Method overloads should be adjacent - organized by functionality for builder pattern

namespace ErikLieben.FA.ES.Testing.Builders.Data;

/// <summary>
/// Provides a base class for fluent event builders with sensible defaults.
/// </summary>
/// <typeparam name="TEvent">The event type to build.</typeparam>
/// <typeparam name="TBuilder">The concrete builder type (for fluent chaining).</typeparam>
public abstract class EventBuilder<TEvent, TBuilder>
    where TEvent : IEvent
    where TBuilder : EventBuilder<TEvent, TBuilder>
{
    /// <summary>
    /// Builds the event with the configured values.
    /// </summary>
    /// <returns>The built event instance.</returns>
    protected abstract TEvent Build();

    /// <summary>
    /// Implicitly converts the builder to the event type by calling Build().
    /// </summary>
    /// <param name="builder">The builder to convert.</param>
    public static implicit operator TEvent(EventBuilder<TEvent, TBuilder> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        return builder.Build();
    }

    /// <summary>
    /// Returns the concrete builder type for fluent chaining.
    /// </summary>
    /// <returns>The builder instance cast to its concrete type.</returns>
    protected TBuilder This() => (TBuilder)this;
}

/// <summary>
/// Provides a fluent interface for building lists of events.
/// </summary>
/// <typeparam name="TEvent">The event type.</typeparam>
public class EventListBuilder<TEvent> where TEvent : IEvent
{
    private readonly List<TEvent> _events = new();

    /// <summary>
    /// Adds an event to the list.
    /// </summary>
    /// <param name="event">The event to add.</param>
    /// <returns>The builder for method chaining.</returns>
    public EventListBuilder<TEvent> Add(TEvent @event)
    {
        _events.Add(@event);
        return this;
    }

    /// <summary>
    /// Adds multiple events to the list.
    /// </summary>
    /// <param name="events">The events to add.</param>
    /// <returns>The builder for method chaining.</returns>
    public EventListBuilder<TEvent> AddRange(params TEvent[] events)
    {
        _events.AddRange(events);
        return this;
    }

    /// <summary>
    /// Adds events generated by a builder.
    /// </summary>
    /// <typeparam name="TBuilder">The builder type.</typeparam>
    /// <param name="builder">The builder to execute.</param>
    /// <returns>The builder for method chaining.</returns>
    public EventListBuilder<TEvent> Add<TBuilder>(EventBuilder<TEvent, TBuilder> builder)
        where TBuilder : EventBuilder<TEvent, TBuilder>
    {
        _events.Add(builder);
        return this;
    }

    /// <summary>
    /// Adds a specified number of events generated by a factory function.
    /// </summary>
    /// <param name="count">The number of events to add.</param>
    /// <param name="factory">The factory function to generate events.</param>
    /// <returns>The builder for method chaining.</returns>
    public EventListBuilder<TEvent> AddMany(int count, Func<int, TEvent> factory)
    {
        for (int i = 0; i < count; i++)
        {
            _events.Add(factory(i));
        }
        return this;
    }

    /// <summary>
    /// Builds the event list.
    /// </summary>
    /// <returns>The list of events.</returns>
    public List<TEvent> Build() => _events;

    /// <summary>
    /// Builds the event array.
    /// </summary>
    /// <returns>The array of events.</returns>
    public TEvent[] BuildArray() => _events.ToArray();

    /// <summary>
    /// Implicitly converts the builder to a list.
    /// </summary>
    public static implicit operator List<TEvent>(EventListBuilder<TEvent> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        return builder.Build();
    }

    /// <summary>
    /// Implicitly converts the builder to an array.
    /// </summary>
    public static implicit operator TEvent[](EventListBuilder<TEvent> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        return builder.BuildArray();
    }
}

/// <summary>
/// Provides helper methods for creating event lists.
/// </summary>
public static class EventBuilderExtensions
{
    /// <summary>
    /// Creates a new event list builder.
    /// </summary>
    /// <typeparam name="TEvent">The event type.</typeparam>
    /// <returns>A new event list builder.</returns>
    public static EventListBuilder<TEvent> Events<TEvent>() where TEvent : IEvent
    {
        return new EventListBuilder<TEvent>();
    }
}
